package cmp.tests.evpn;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Pattern;

import cmp.infra.CmpRouter;
import cmp.infra.Session.ICmpCliCmd;
import cmp.infra.Session.SessionMode;
import cmp.infra.Session.SessionType;
import cmp.infra.common.General;
import cmp.infra.common.GlobalParam;
import cmp.infra.ixia.Ixia;
import cmp.infra.ixia.IxiaFunctions;
import cmp.infra.reporter.CompassReporter;
import cmp.infra.reporter.loggerImp;

/**
 * Verification helpers for the generated EVPN suite.
 *
 * Mirrors the shape of cmp.tests.vpls.VplsUtils: the test class stays a
 * readable sequence of numbered steps and every assertion lives here.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class EvpnUtils implements loggerImp {

    /** intPool in the SUT file that backs the attachment circuits. */
    private static final String AC_POOL = "data1";

    /**
     * Where the attachment circuits start in that pool.
     *
     * Non-zero when a link is spent on the EVPN core: pc-3080's data1 pool is
     * three DUT<->IXIA links, and binding the EVI from index 0 put it on the
     * core port, which is L3 and not l2-transport.
     */
    private static final int AC_POOL_OFFSET = 0;

    /** Index into the SUT's `general/vlans` list for the AC VLAN. */
    private static final int AC_VLAN_INDEX = 0;

    /**
     * The attachment circuit as THIS testbed defines it, e.g.
     * "x-eth 0/0/8.100" - the SUT's intPool entry plus the sub-interface.
     *
     * A vlan-based EVI will not accept the bare port; see EVPN_Base.cfg.
     */
    public String acInterface(int index) throws Exception {
        return cmp.getIntPool(AC_POOL).getInter(index).getIntName()
               + "." + acVlan();
    }

    /**
     * The same circuit in the form the device PRINTS it: no space.
     *
     * DEVICE QUIRK, verified on pc-3080 8.7.0 LAB 22. Configuration accepts
     * the spaced form:
     *     l2-services evpn evi-1 interface x-eth 0/0/8.3380      OK
     * but the show command's `source` filter does not:
     *     ... mac-address-table name evi-1 source x-eth 0/0/8.3380
     *         syntax error: unknown argument
     *     ... mac-address-table name evi-1 source x-eth0/0/8.3380   OK
     *
     * Same interface, same device, two spellings - which is why the capture
     * half and the assertion half of this step disagreed for a whole run.
     */
    public String acInterfaceCompact(int index) throws Exception {
        return acInterface(index).replace(" ", "");
    }

    /**
     * The VLAN the attachment circuits carry, taken from the SUT file.
     *
     * Both sides must agree or no frame ever reaches the service: the DUT
     * sub-interface is created as <port>.<vlan>, and the IXIA vport is tagged
     * with the same value by the `vlan` rows in bringUpParams.crt. Reading it
     * from the SUT rather than hard-coding it is what keeps that true on a
     * testbed whose VLAN is different.
     */
    public String acVlan() throws Exception {
        return General.getInstanceByName().vlans[AC_VLAN_INDEX].getNumber();
    }

    /**
     * Run a configuration command and REQUIRE the device to accept it.
     *
     * `CmpRouter.configAndValidate` commits and warns when the commit had
     * nothing to do. That is the right default for their suites, but it means
     * a command the CLI rejected outright leaves the test green: nothing was
     * staged, so there is nothing to commit, so there is only a warning. Here
     * a rejected command is a failed step.
     */
    public void configAndVerifyAccepted(ICmpCliCmd command) throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);
        if (wasRejected(output)) {
            CompassReporter.fail("Device REJECTED '" + command.toString()
                    + "': " + String.valueOf(output).trim());
            throw new Exception("device rejected the command: " + command.toString());
        }
        cmp.commitAndVerification(command.getCmdSessionType(),
                GlobalParam.LOAD_CONF_FILE_TIMEOUT_DEFAULT_MSEC);
    }

    /** Did the CLI refuse the command it was given? */
    private boolean wasRejected(String output) {
        if (output == null) {
            return false;
        }
        // Their own pattern first, then the plain reading of the same thing,
        // so a change in the framework's regexp cannot quietly turn this
        // assertion off.
        if (Pattern.compile(GlobalParam.CLI_COMMAND_SYNTAX_ERROR_REGEXP)
                   .matcher(output).find()) {
            return true;
        }
        String low = output.toLowerCase();
        return low.contains("syntax error")
               || low.contains("% invalid input")
               || low.contains("is not a valid value");
    }


    private final EvpnParams params;
    private final CmpRouter cmp;
    private final Ixia ixia;

    public EvpnUtils(EvpnParams params, CmpRouter cmp, Ixia ixia) {
        this.params = params;
        this.cmp = cmp;
        this.ixia = ixia;
    }

    /**
     * Run a show command and assert every expected line (a regex) appears in
     * the output, polling until the verify timeout. Modelled on
     * ShowVplsDetail.verifyShowVplsDetail.
     *
     * An EMPTY expectation array means "not yet validated against a real
     * device": the command is still run and its output reported, but the
     * result is a warning, never a pass.
     */
    /**
     * Assert the given lines are GONE from the command's output.
     *
     * The mirror of verifyShowLines, for steps whose whole point is that
     * something stopped being there: MACs after the aging time, a Type-2
     * after withdrawal. Those cannot be expressed by a capture - `ate
     * capture` records state while it EXISTS and refuses empty output, so the
     * captured lines are exactly the rows that ought to disappear. Asserting
     * their presence asserts that aging never happened, which is how TC03
     * failed while the device was behaving correctly.
     *
     * Falsifiable in the right direction: it fails if the rows are still
     * there, and it refuses to pass on an empty expectation, because
     * "nothing was supposed to vanish" proves nothing.
     */
    public void verifyShowLinesAbsent(ICmpCliCmd command, String[] goneLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);
        if (goneLines == null || goneLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - nothing asserted absent.");
            logMsg.info(output);
            return;
        }
        java.util.List<String> stillThere = new java.util.ArrayList<String>();
        for (String pattern : goneLines) {
            java.util.regex.Pattern p = java.util.regex.Pattern.compile(pattern);
            if (p.matcher(output).find()) {
                stillThere.add(pattern);
            }
        }
        falsifiableAssertions++;
        CompassReporter.passFailByCondition(stillThere.isEmpty(),
                "The output of " + command.toString()
                        + " no longer contains the expected-gone lines.",
                "The output of " + command.toString()
                        + " STILL contains lines that should have gone: "
                        + stillThere);
    }

    public void verifyShowLines(ICmpCliCmd command, String[] expectedLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);

        if (expectedLines == null || expectedLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - output captured for "
                    + "review, nothing asserted.");
            logMsg.info(output);
            return;
        }

        Set<String> missing = new LinkedHashSet<String>();
        boolean asExpected = false;
        long endTime = System.currentTimeMillis() + params.VERIFY_TIMEOUT_IN_MSEC;

        while (!asExpected && System.currentTimeMillis() < endTime) {
            missing.clear();
            asExpected = true;
            for (int i = 0; i < expectedLines.length; i++) {
                String expected = expectedLines[i];
                if (output == null
                        || !Pattern.compile(expected).matcher(output).find()) {
                    missing.add(expected);
                    asExpected = false;
                }
            }
            if (!asExpected) {
                Thread.sleep(params.VERIFY_INTERVAL_IN_MSEC);
                output = cmp.runCommandAndSwitch(command.toString(), command);
            }
        }

        falsifiableAssertions++;
        CompassReporter.passFailByCondition(asExpected,
                "The output of " + command.toString() + " is as expected.",
                "The output of " + command.toString()
                        + " is not as expected. Missing lines: " + missing);
    }

    /**
     * Build the suite's traffic items on the chassis.
     *
     * Exaware's own suites load a prebuilt binary .ixncfg at bring-up and only
     * suspend/unsuspend what it contains. That binary cannot be generated from
     * documents, so this suite stands up its own traffic over TCL instead -
     * the same chassis objects, no file to be handed.
     *
     * Idempotency is the chassis's business: call this once, before the first
     * setTrafficItemState. Every argument comes from EvpnParams, so a different
     * rig is a params change, not a code change.
     *
     * Argument order is VERIFIED against the proc signatures in
     * cmp-infra-project/src/main/java/cmp/infra/tcl/ixia_lib.tcl (2026-08-12),
     * not merely against the $arg help strings.
     *
     * LIMIT - the SOURCE MAC cannot be set from this library. ixia_lib.tcl
     * offers editTrafficRawDestMacAddr and no source equivalent, and
     * configTrafficItemStream takes only destinationMacMode. EVPN learns from
     * SOURCE MACs, so the FLOW-030 precondition that AC2 and AC3 emit the same
     * source MAC - which is what makes AC2 -> AC3 a local move rather than two
     * distinct hosts - cannot be expressed here. Those items still need either
     * a prebuilt .ixncfg or a new src-MAC proc in ixia_lib.tcl, which is
     * Exaware's file to extend. The per-item source MAC is carried in
     * EvpnParams so it is ready the moment either arrives.
     */
    public void createTrafficItems() throws Exception {
        // The vports have to exist before they can be tagged or used as
        // endpoints. Their suites get them from the .crt's interface rows,
        // which Ixia.loadConfigurationFile applies while loading an .ixncfg -
        // a file this suite deliberately does not have. Whatever vports happen
        // to be left in the chassis session from an earlier run are not ours.
        assignAcVports();
        tagVportsWithAcVlan();
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            String name = ti[0], srcVport = ti[1], dstVport = ti[2], srcMac = ti[3];
            logMsg.info("Creating IXIA traffic item " + name
                    + " (" + srcVport + " -> " + dstVport + ")");
            // Source MAC is set below, after the item exists.
            // "null" - not "" - is how their TCL spells an unset argument:
            // every proc in ixia_lib.tcl guards with
            // `if {[string match $arg null] != 1}`. An empty Java string
            // collapses during TCL word-splitting and the proc is called with
            // too few arguments, which answers `wrong # args` while
            // performFunctions still reports "ended without errors".
            ixia.performFunctions(IxiaFunctions.CONFIGURE_NEW_TRAFFIC_ITEM.args(
                    name, "true", "null", "l2L3", "false", "false", "raw",
                    name, "interleaved", "null", "false", "false", "oneToOne"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_ENDPOINTS.args(
                    name, "1", srcVport, "null", "null", "null", "null", "null",
                    "null", dstVport, "null", "null", "null", "null", "null",
                    "null", "null", "null", "null", name, "null", "null"));
            bindRawEndpoints(name, srcVport, dstVport);
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_STREAM.args(
                    name, "1", "goodCRC", "manual", name, "8", "auto", "false"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_FRAME_RATE.args(
                    name, "stream", "1", "framesPerSecond",
                    params.TRAFFIC_RATE_FPS, "bytes", "bitsPerSec", "false"));
        }
        // A raw item's frame is whatever its protocol stack says, and that
        // stack is ethernet + fcs: UNTAGGED. Tagging the vport's interface
        // does not change it - that governs protocol emulation, not raw frame
        // content. Untagged frames never match a `vlan-id` sub-interface, so
        // the DUT counted 219k frames on the port and 0 on the circuit, and
        // the EVI learnt nothing while every call reported success.
        tagTrafficItemsWithAcVlan();

        // GENERATE binds the physical MACs and interfaces onto each raw item -
        // their own enum says so ("generate traffic item to apply physical mac
        // and interfaces to traffic source and destanation"). Without it the
        // items are configured but unresolved, and nothing is transmitted. It
        // runs BEFORE the source MAC is set; generating afterwards would
        // overwrite it.
        ixia.performFunctions(IxiaFunctions.GENERATE_TRAFFIC);

        // EVPN learns from SOURCE MACs, and ixia_lib.tcl exposes only
        // editTrafficRawDestMacAddr. It does not need a new proc: that one is a
        // single ixNet setAtt on the ethernet-1 stack, and the source field
        // sits beside the destination field on the same path. So the same
        // assignment is issued here as raw TCL, into the session where
        // ixia_lib.tcl is already sourced - their file is not modified.
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            setTrafficItemSourceMac(ti[0], ti[3]);
        }
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic items built on the chassis");
    }

    /**
     * Point a raw traffic item's endpoints at the vports, and verify it.
     *
     * `configTrafficItemEndpoints` only emits the `/vport:{id}/protocols` form
     * that a RAW item requires when it decides the source vport's interface
     * has a VLAN - and it decides that with
     * `ixNet getAtt [ixNet getL $vport interface]/vlan -vlanEnable`, which is
     * only a valid path when the vport has EXACTLY ONE interface. A vport
     * carrying more than one makes that read fail, the heuristic falls through
     * to the interface-list form, and the chassis answers
     * "ERROR-6301-The endpoint is not correct for this type of trafficItem" -
     * which performFunctions reports as a warning and the run survives.
     *
     * Rather than depend on that heuristic, set the endpoints explicitly and
     * read them back.
     */
    public void bindRawEndpoints(String trafficItemName, String srcVport,
                                 String dstVport) throws Exception {
        String readBack = ixia.runCommand(new RawTcl(
                "set ti [getTraffic \"" + trafficItemName + "\"] ; "
                + "set es [lindex [ixNet getL $ti endpointSet] 0] ; "
                + "ixNet setMultiAttr $es "
                +   "-sources [list $ixia(" + srcVport + ")/protocols] "
                +   "-destinations [list $ixia(" + dstVport + ")/protocols] ; "
                + "ixNet commit ; "
                + "puts \"\" ; "
                + "puts \"ENDPOINTS=[ixNet getAtt $es -sources]"
                +   "|[ixNet getAtt $es -destinations]\" ; "
                + "puts \"\""));

        boolean bound = readBack != null && readBack.contains("/protocols")
                && !readBack.contains("ERROR");
        CompassReporter.passFailByCondition(bound,
                trafficItemName + ": endpoints bound to " + srcVport + " -> "
                        + dstVport + ".",
                trafficItemName + ": endpoints NOT bound (" + oneLine(readBack)
                        + ") - the item will transmit nothing.");
        if (!bound) {
            throw new Exception("could not bind endpoints for " + trafficItemName);
        }
    }

    /**
     * Set a traffic item's source MAC, and CHECK the chassis took it.
     *
     * Mirrors ixia_lib.tcl's editTrafficRawDestMacAddr, with
     * ethernet.header.sourceAddress-1 in place of destinationAddress-1, and
     * reuses that file's own getTraffic helper. The value is read back rather
     * than assumed: an unapplied source MAC would leave the MAC-move flows
     * asserting something that never happened.
     */
    /**
     * Push a VLAN header onto every raw traffic item, carrying the AC VLAN.
     *
     * DEVICE-VERIFIED on pc-3080: with the header appended the circuit
     * counters move off zero and the EVI learns; without it they stay at zero
     * while the port counts hundreds of thousands of frames.
     *
     * Reads the stacks back afterwards rather than trusting the append.
     */
    public void tagTrafficItemsWithAcVlan() throws Exception {
        String vlan = acVlan();
        String tcl =
            "set tpl {} ; "
            + "foreach t [ixNet getL [ixNet getRoot]/traffic protocolTemplate] { "
            +   "if {[string equal -nocase [ixNet getAtt $t -displayName] {VLAN}]} { "
            +     "set tpl $t } } ; "
            + "set tagged 0 ; set stacks {} ; "
            + "foreach ti [ixNet getL [ixNet getRoot]/traffic trafficItem] { "
            +   "foreach ce [ixNet getL $ti configElement] { "
            +     "set has 0 ; "
            +     "foreach st [ixNet getL $ce stack] { "
            +       "if {[string match {*vlan*} $st]} { set has 1 } } ; "
            +     "if {$has == 0 && $tpl ne {}} { "
            +       "ixNet exec appendProtocol [lindex [ixNet getL $ce stack] 0] $tpl ; "
            +       "ixNet commit } ; "
            +     "foreach st [ixNet getL $ce stack] { "
            +       "if {![string match {*vlan*} $st]} { continue } ; "
            +       "incr tagged ; "
            +       "foreach fld [ixNet getL $st field] { "
            +         "if {[string match -nocase {*vlan-id*} "
            +           "[ixNet getAtt $fld -displayName]]} { "
            +           "ixNet setMultiAttr $fld -singleValue " + vlan
            +             " -fieldValue " + vlan + " -valueType singleValue } } } ; "
            +     "ixNet commit ; "
            +     "append stacks [ixNet getL $ce stack] } } ; "
            + "puts \"\" ; "
            + "puts \"VLANTAGGED=$tagged VLANID=" + vlan + "\" ; "
            + "puts \"\"";
        String readBack = ixia.runCommand(new RawTcl(tcl));
        boolean tagged = readBack != null && readBack.contains("VLANTAGGED=")
                && !readBack.contains("VLANTAGGED=0");
        CompassReporter.passFailByCondition(tagged,
                "Traffic items carry the AC VLAN " + vlan + " ("
                        + oneLine(readBack) + ").",
                "Traffic items were NOT VLAN-tagged (" + oneLine(readBack)
                        + ") - untagged frames never reach a vlan-id "
                        + "sub-interface, so the EVI will learn nothing.");
        if (!tagged) {
            throw new Exception("could not VLAN-tag the traffic items");
        }
    }

    public void setTrafficItemSourceMac(String trafficItemName, String mac)
            throws Exception {
        // Find the field by NAME, do not guess its index. ixia_lib.tcl writes
        // the destination MAC to `ethernet.header.destinationAddress-1`, and
        // the obvious mirror `...sourceAddress-1` does not exist - the chassis
        // answers "ERROR-7009-Could not find the requested item" with a
        // NullReferenceException in StackFieldHandler.InsertMissingField,
        // because field suffixes are positions within the stack, not names.
        // So walk the ethernet stack's fields and match on the display name.
        String tcl =
            "set ti [getTraffic \"" + trafficItemName + "\"] ; "
            + "set names {} ; set done 0 ; "
            + "foreach ce [ixNet getL $ti configElement] { "
            +   "foreach st [ixNet getL $ce stack] { "
            +     "if {![string match *ethernet* $st]} { continue } ; "
            +     "foreach fld [ixNet getL $st field] { "
            +       "set nm [ixNet getAtt $fld -displayName] ; "
            +       "lappend names $nm ; "
            +       "if {[string match -nocase {*source*} $nm]} { "
            +         "ixNet setMultiAttr $fld -singleValue " + mac
            +           " -fieldValue " + mac + " -valueType singleValue ; "
            +         "incr done } } } } ; "
            + "ixNet commit ; "
            + "set got {} ; "
            + "foreach ce [ixNet getL $ti configElement] { "
            +   "foreach st [ixNet getL $ce stack] { "
            +     "if {![string match *ethernet* $st]} { continue } ; "
            +     "foreach fld [ixNet getL $st field] { "
            +       "if {[string match -nocase {*source*} "
            +         "[ixNet getAtt $fld -displayName]]} { "
            +         "append got [ixNet getAtt $fld -singleValue] } } } } ; "
            + "puts \"\" ; "
            + "puts \"SRCMAC=$got SET=$done FIELDS=$names\" ; "
            + "puts \"\"";
        String readBack = ixia.runCommand(new RawTcl(tcl));

        boolean applied = readBack != null
                && readBack.toLowerCase().contains("srcmac=" + mac.toLowerCase());
        CompassReporter.passFailByCondition(applied,
                trafficItemName + ": source MAC " + mac + " applied on the chassis.",
                trafficItemName + ": source MAC " + mac + " was NOT applied - the"
                        + " chassis reports " + oneLine(readBack)
                        + ". Any assertion that depends on this source MAC is"
                        + " unmet.");
    }

    /**
     * A raw TCL command for the IXIA session.
     *
     * Deliberately NOT an EvpnCommands constant: that enum is validated
     * against the EVPN CLI documentation at generation time, and TCL sent to
     * IxNetwork has no place in it.
     */
    private static final class RawTcl implements ICmpCliCmd {
        private final String tcl;

        RawTcl(String tcl) {
            this.tcl = tcl;
        }

        @Override
        public ICmpCliCmd args(Object... args) {
            return this;
        }

        @Override
        public String toString() {
            return this.tcl;
        }

        @Override
        public String stripArgs() {
            return this.tcl;
        }

        @Override
        public SessionMode getCmdSessionMode() {
            return SessionMode.CLI;
        }

        @Override
        public SessionType getCmdSessionType() {
            return SessionType.MGMT;
        }
    }

    /**
     * Enable the AC VLAN on every IXIA vport, and verify the chassis took it.
     *
     * Two things depend on this and both fail silently without it:
     *
     *  * frames must carry the AC VLAN or they never reach the sub-interface
     *    the EVI is bound to;
     *  * a RAW traffic item only accepts endpoints of the form
     *    `/vport:{id}/protocols`, and `configTrafficItemEndpoints` only builds
     *    that form when the vport's interface has a VLAN enabled. Without it
     *    the chassis answers "ERROR-6301-The endpoint is not correct for this
     *    type of trafficItem" - and performFunctions still reports the call as
     *    "ended without errors".
     *
     * The .crt carries `vlan` rows for the same purpose, but they are applied
     * by `Ixia.loadConfigurationFile`, which only runs for a device that has a
     * configuration file row - and this suite deliberately references no
     * .ixncfg. So the tagging is done here, where it is also verified.
     */
    public void assignAcVports() throws Exception {
        // `loadIxiaObj` names $ixia(vport1..N) from the vports ALREADY present
        // in the IxNetwork configuration (`ixNet getL [ixNet getRoot] vport`).
        // A session that never loaded an .ixncfg has however many a previous
        // run happened to leave behind, so the names the suite uses may simply
        // not exist - "can't read ixia(vport3): no such element in array".
        // Create them up to the HIGHEST vport the suite names, then reload the
        // object map. Counting only the ACs is not enough once a link is spent
        // on the core: the ACs are then vport2 and vport3, so creating two
        // vports leaves $ixia(vport3) undefined and the chassis answers
        // "can't read ixia(vport3): no such element in array".
        int want = AC_POOL_OFFSET + params.AC_VPORTS.length;
        String created = ixia.runCommand(new RawTcl(
                "set n [llength [ixNet getL [ixNet getRoot] vport]] ; "
                + "while {$n < " + want + "} { ixNet add [ixNet getRoot] vport ; "
                + "incr n } ; ixNet commit ; "
                + "puts \"\" ; "
                + "puts \"VPORTS=[llength [ixNet getL [ixNet getRoot] vport]]\" ; "
                + "puts \"\""));
        boolean enough = created != null && created.contains("VPORTS=")
                && !created.contains("VPORTS=0");
        CompassReporter.passFailByCondition(enough,
                "IXIA has at least " + want + " vports (" + oneLine(created) + ").",
                "IXIA does not have " + want + " vports (" + oneLine(created)
                        + ") - the traffic items cannot be built.");
        if (!enough) {
            throw new Exception("could not create the IXIA vports");
        }
        ixia.performFunctions(IxiaFunctions.LOAD_IXIA_OBJECT);

        for (int i = 0; i < params.AC_VPORTS.length; i++) {
            int poolIdx = i + AC_POOL_OFFSET;
            String card = ixia.getIntPool(AC_POOL).getInter(poolIdx).getCard();
            String port = ixia.getIntPool(AC_POOL).getInter(poolIdx).getPort();
            logMsg.info("Assigning " + params.AC_VPORTS[i]
                    + " to card " + card + " port " + port);
            ixia.performFunctions(
                    IxiaFunctions.ASSIGN_VPORT_$_WITH_CARD_$_AND_PORT_$.args(
                            params.AC_VPORTS[i], card, port, "true"));
        }
    }

    /**
     * Enable the AC VLAN on every IXIA vport, and verify the chassis took it.
     */
    public void tagVportsWithAcVlan() throws Exception {
        String vlan = acVlan();
        for (String vport : params.AC_VPORTS) {
            // NOT IxiaFunctions.SET_AND_VERIFY_INTERFACE_$_VLAN_$: its proc
            // does `ixNet getL $vport vlan`, and the chassis rejects that -
            // "is not a valid child of /vport (possible options are: l1Config
            // capture protocols discoveredNeighbor interface ...)". The VLAN
            // hangs off the vport's INTERFACE, which is how their own
            // configTrafficItemEndpoints reaches it ($int/vlan). A vport with
            // no interface object gets one first; their suites get theirs from
            // the .ixncfg we deliberately do not load.
            String tcl =
                "set vp $ixia(" + vport + ") ; "
                + "set il [ixNet getL $vp interface] ; "
                + "if {[llength $il] == 0} { "
                +   "ixNet add $vp interface ; ixNet commit ; "
                +   "set il [ixNet getL $vp interface] ; "
                +   "ixNet setAtt [lindex $il 0] -enabled true ; ixNet commit "
                + "} ; "
                + "set int [lindex $il 0] ; "
                + "ixNet setMultiAtt $int/vlan -vlanEnable true ; ixNet commit ; "
                + "ixNet setMultiAtt $int/vlan -vlanId " + vlan + " ; ixNet commit ; "
                + "puts \"\" ; "
                + "puts \"ACVLAN=[ixNet getAtt $int/vlan -vlanId]"
                +   "/[ixNet getAtt $int/vlan -vlanEnable]\" ; "
                + "puts \"\"";
            String readBack = ixia.runCommand(new RawTcl(tcl));

            boolean ok = readBack != null
                    && readBack.contains("ACVLAN=" + vlan + "/true");
            CompassReporter.passFailByCondition(ok,
                    vport + ": VLAN " + vlan + " enabled on the IXIA interface.",
                    vport + ": VLAN " + vlan + " was NOT enabled (chassis said "
                            + oneLine(readBack) + ") - raw traffic endpoints "
                            + "will be rejected and no frame will reach the EVI.");
            if (!ok) {
                throw new Exception("could not tag " + vport + " with VLAN " + vlan);
            }
        }
    }

    /**
     * Start the traffic engine.
     *
     * Unsuspending an item is not the same as transmitting. Their suites load
     * an .ixncfg whose traffic is already running and only suspend/unsuspend
     * it; a suite that builds its own items must start them, or the chassis
     * holds three correctly configured items and sends nothing.
     */
    public void startTraffic() throws Exception {
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        ixia.performFunctions(IxiaFunctions.START_TRAFFIC);
        logMsg.info("Traffic started");
    }

    /** Stop the traffic engine. */
    public void stopTraffic() throws Exception {
        ixia.performFunctions(IxiaFunctions.STOP_TRAFFIC);
        logMsg.info("Traffic stopped");
    }

    /** Enable (unsuspend) or disable (suspend) one named IXIA traffic item. */
    public void setTrafficItemState(String trafficItemName, boolean enabled)
            throws Exception {
        ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_$_STATE_$
                .args(trafficItemName, String.valueOf(enabled)));
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        if (enabled) {
            // ENABLING AN ITEM IS NOT TRANSMITTING. `-enabled true` plus
            // `trafficApply` leaves the chassis configured and silent: every
            // DUT circuit counted zero frames and the EVI learnt nothing,
            // while each call reported success. Transmission needs an
            // explicit global start.
            ixia.performFunctions(IxiaFunctions.START_TRAFFIC);
            // ...and "start" is a request, not evidence. Read the state back
            // before any assertion depends on frames having moved.
            String state = ixia.runCommand(new RawTcl(
                    "puts \"\" ; "
                    + "puts \"TRAFFICSTATE=[ixNet getAtt "
                    + "[ixNet getRoot]/traffic -state]\" ; "
                    + "puts \"\""));
            boolean running = state != null
                    && state.toLowerCase().contains("trafficstate=started");
            CompassReporter.passFailByCondition(running,
                    "Traffic is transmitting (" + oneLine(state) + ").",
                    "Traffic did NOT start (" + oneLine(state)
                            + ") - no frame reaches the EVI and nothing can "
                            + "be learnt.");
            if (!running) {
                throw new Exception("traffic did not start");
            }
        }
        logMsg.info("Traffic item " + trafficItemName + " enabled=" + enabled);
    }

    /**
     * How many assertions ran that COULD have failed.
     *
     * A suite that verified nothing must not be able to report success, so
     * this is counted rather than assumed, and checked at the end of the test.
     */
    private int falsifiableAssertions = 0;

    /**
     * Fail the test if nothing was actually verified.
     *
     * Called at the end of every generated test. A run in which every
     * verification step warned - because its expectation has never been
     * captured from a device - is not a pass; it is a run that proved the
     * plumbing works and checked no behaviour. Reporting that as green is how
     * a test suite stops being worth anything.
     */
    public void assertSomethingWasVerified() throws Exception {
        if (falsifiableAssertions == 0) {
            CompassReporter.fail("INCONCLUSIVE: this test made no assertion "
                    + "that could have failed. Every verification step ran its "
                    + "command and reported a warning, so the run says nothing "
                    + "about the feature. Capture the expectations "
                    + "(ate capture) and regenerate.");
            throw new Exception("no falsifiable assertion was made");
        }
        logMsg.info("Falsifiable assertions made: " + falsifiableAssertions);
    }

    /** Capture the current output of a command, for later no-change comparison. */
    public String snapshot(ICmpCliCmd command) throws Exception {
        return cmp.runCommandAndSwitch(command.toString(), command);
    }

    /**
     * Assert a command's output has NOT changed since the snapshot. Used for
     * the negative assertion that a purely local MAC move between two ACs on
     * the same PE triggers no new Type-2 advertisement.
     */
    public void verifyOutputUnchanged(String before, ICmpCliCmd command,
                                      String what) throws Exception {
        String after = cmp.runCommandAndSwitch(command.toString(), command);

        // An empty baseline makes this assertion vacuous: "nothing changed"
        // is trivially true when there was nothing to change, so it passes on
        // a device where the feature never worked. Seen for real - the
        // "no new Type-2 after a local MAC move" check compared
        // "% No entries found." with "% No entries found." and reported a pass.
        if (isEmptyTable(before)) {
            CompassReporter.warning(what + ": NOT ASSERTED - the baseline was "
                    + "empty (" + oneLine(before) + "), so 'unchanged' could "
                    + "not have failed. This needs a peer and traffic before it "
                    + "means anything.");
            return;
        }

        boolean unchanged = before.equals(after);
        falsifiableAssertions++;
        CompassReporter.passFailByCondition(unchanged,
                what + ": unchanged, as expected.",
                what + ": CHANGED unexpectedly.");
    }

    /** Did the device answer with no rows at all? */
    private boolean isEmptyTable(String output) {
        if (output == null) {
            return true;
        }
        String low = output.toLowerCase();
        return low.trim().isEmpty() || low.contains("no entries found");
    }

    /** Collapse output to one line, for a readable report message. */
    private String oneLine(String output) {
        if (output == null) {
            return "null";
        }
        String s = output.replace('\r', ' ').replace('\n', ' ').trim();
        return s.length() > 240 ? s.substring(0, 240) + "..." : s;
    }

    /**
     * IXIA per-port / per-flow statistics assertion.
     *
     * Left as an explicit gap: the expected rows depend on the port naming and
     * offered rate inside the .ixncfg that Exaware build for this rig, and
     * ShowIxiaStatistics drives them from a RowDataTable populated out of the
     * suite params table. Wiring that needs the real .ixncfg.
     */
    public void verifyIxiaStatistics(String what, String[] expectedRows)
            throws Exception {
        if (expectedRows == null || expectedRows.length == 0) {
            CompassReporter.warning("IXIA statistics check '" + what
                    + "' is not wired yet - needs the .ixncfg port naming and "
                    + "a RowDataTable in EvpnParams. See "
                    + "ShowIxiaStatistics.verifyDataPlanPortStatistics.");
            return;
        }
        CompassReporter.warning("IXIA statistics check '" + what
                + "' has expectations but no table binding yet.");
    }

    /** Sleep, reporting the wait so the run log explains the gap. */
    public void waitSeconds(int seconds, String why) throws Exception {
        logMsg.info("Waiting " + seconds + " sec: " + why);
        Thread.sleep(seconds * 1000L);
    }
}
