"""TestScript IR → JSystem/Java source for Exaware's `cmp-tests-project`.

Emits the four artifacts a real suite in that repo consists of (see
`.claude/skills/exaware-framework`):

  1. `TCnn_*.java`      — `extends CmpTestCase`, one `@Test`, steps rendered as
                          `CompassReporter.stopAndStartLevel(++level + ". …")`
  2. `EvpnParams.java`  — `implements ISuiteParams`; every expected value
  3. `EvpnUtils.java`   — the verify helpers the tests call
  4. `EvpnCommands.java`— `implements ICmpCliCmd`; the CLI templates

Conventions are copied from `cmp/tests/vpls`, which is the closest existing
analog (`TC05_VplsMacAgingTime` is a MAC-aging test driven by suspending and
unsuspending IXIA traffic items — structurally the same shape as the M2 flows).

Target is Java 8 (`maven-compiler-plugin` source/target 1.8), so: no `var`,
no `List.of`, no diamond-less generics shortcuts.

**Steps carrying `todo` emit `CompassReporter.warning(...)`, never a passing
assertion.** An expected-value table that nobody has validated against real
device output must not be able to report a green run.
"""
from __future__ import annotations

from dataclasses import dataclass

from ate.codegen.commands import all_commands
from ate.codegen.lab import LabProfile
from ate.codegen.script_ir import Step, StepKind, TestScript

PACKAGE = "cmp.tests.evpn"
GENERATED_BY = (
    "Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI "
    "doc and RFC 7432bis."
)


@dataclass
class JavaFile:
    """One emitted source file, addressed by its package-relative path."""

    path: str          # "cmp/tests/evpn/EvpnUtils.java"
    content: str

    @property
    def class_name(self) -> str:
        return self.path.rsplit("/", 1)[-1][: -len(".java")]


#: The plan's prose uses typographic characters that have no place in Java
#: source — Exaware's tree is plain ASCII throughout. Fold rather than escape,
#: so the run report stays readable.
_ASCII_FOLD = {
    "→": "->", "←": "<-", "↔": "<->",
    "—": "-", "–": "-", "‑": "-",
    "§": "section ", "≥": ">=", "≤": "<=",
    "‘": "'", "’": "'", "“": '"', "”": '"',
    "…": "...", " ": " ", "·": "-",
}


def _ascii(s: str) -> str:
    for bad, good in _ASCII_FOLD.items():
        s = s.replace(bad, good)
    return s.encode("ascii", "replace").decode("ascii")


def _jstr(s: str) -> str:
    """Render a Python string as an ASCII-safe Java string literal."""
    out = _ascii(s).replace("\\", "\\\\").replace('"', '\\"')
    return '"' + out.replace("\n", "\\n") + '"'


def _wrap_javadoc(text: str, indent: str = " ") -> list[str]:
    """Wrap prose into javadoc continuation lines at ~76 columns."""
    words = _ascii(text).split()
    lines: list[str] = []
    cur = ""
    for w in words:
        if len(cur) + len(w) + 1 > 74:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return [f"{indent}* {ln}" for ln in lines]


def _header(summary: str, extra: list[str] | None = None) -> str:
    body = ["/**"] + _wrap_javadoc(summary)
    if extra:
        body.append(" *")
        for e in extra:
            body += _wrap_javadoc(e)
    body.append(" *")
    body += _wrap_javadoc(GENERATED_BY)
    body.append(" */")
    return "\n".join(body)


# ── EvpnCommands ────────────────────────────────────────────────────────────

def emit_commands() -> JavaFile:
    lines = [
        f"package {PACKAGE};",
        "",
        "import cmp.infra.Session.ICmpCliCmd;",
        "import cmp.infra.Session.SessionMode;",
        "import cmp.infra.Session.SessionType;",
        "",
        _header(
            "EVPN CLI command templates.",
            [
                "Kept as a standalone enum rather than appended to "
                "cmp.tests.common.Commands: every CmpRouter entry point takes "
                "the ICmpCliCmd interface, so this is a drop-in, and the "
                "shared 1220-line Commands enum stays free of merge conflicts.",
                "Every constant below traces to a command in the EVPN CLI "
                "doc; the documented syntax is quoted above each one.",
            ],
        ),
        "public enum EvpnCommands implements ICmpCliCmd {",
        "",
    ]
    registry = all_commands()
    for i, cmd in enumerate(registry):
        sep = "," if i < len(registry) - 1 else ";"
        lines.append(_ascii(
            f"    /** CLI doc: {cmd.source} - {cmd.doc_syntax} */"))
        if cmd.doc_suspect:
            lines.append("    // WARNING -- verify against the DUT before "
                         "first run:")
            for ln in _wrap_javadoc(cmd.doc_suspect, indent="    ")[:6]:
                lines.append("    //" + ln[5:])
        mode = "" if cmd.mode == "SessionMode.CLI" else f", {cmd.mode}"
        lines.append(f"    {cmd.key}({_jstr(cmd.template)}{mode}){sep}")
        lines.append("")

    lines += [
        "    private final String format;",
        "    private String formattedStr;",
        "    private SessionMode cmpSessionMode = SessionMode.CLI;",
        "    private SessionType cmpSessionType = SessionType.MGMT;",
        "",
        "    private EvpnCommands(String format) {",
        "        this.format = format;",
        "        this.formattedStr = format;",
        "    }",
        "",
        "    private EvpnCommands(String format, SessionMode cmpSessionMode) {",
        "        this.format = format;",
        "        this.formattedStr = format;",
        "        this.cmpSessionMode = cmpSessionMode;",
        "    }",
        "",
        "    @Override",
        "    public EvpnCommands args(Object... args) {",
        "        this.formattedStr = String.format(this.format, args);",
        "        return this;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return this.formattedStr;",
        "    }",
        "",
        "    @Override",
        "    public String stripArgs() {",
        "        int specialCharIndex = this.format.indexOf('%');",
        "        if (specialCharIndex > 0) {",
        "            return this.format.substring(0, specialCharIndex).trim();",
        "        }",
        "        return this.format;",
        "    }",
        "",
        "    @Override",
        "    public SessionMode getCmdSessionMode() {",
        "        return this.cmpSessionMode;",
        "    }",
        "",
        "    @Override",
        "    public SessionType getCmdSessionType() {",
        "        return this.cmpSessionType;",
        "    }",
        "}",
        "",
    ]
    return JavaFile(path="cmp/tests/evpn/EvpnCommands.java",
                    content="\n".join(lines))


# ── EvpnParams ──────────────────────────────────────────────────────────────

#: Regex metacharacters that appear in ordinary device output and would
#: otherwise change what an expectation means. `Local Label: 40960` is
#: harmless; `Move Interval: 180 seconds (default)` is not — an unescaped `(`
#: turns the line into a capture group and the match silently stops meaning
#: what it says.
_RE_META = set(r".^$*+?()[]{}|\\")


def _line_to_regex(line: str) -> str:
    """A captured line as a regex that matches THAT line and little else.

    Two deliberate choices:

    * every metacharacter is escaped, so the expectation asserts the text the
      device actually printed rather than an accident of punctuation;
    * runs of whitespace become `\\s+`, because these tables are column-padded
      and the padding shifts with the width of neighbouring values. Asserting
      the exact number of spaces would make the test fail on a longer EVI name
      while the behaviour it checks is unchanged.
    """
    out = []
    for chunk in line.strip().split():
        out.append("".join("\\" + c if c in _RE_META else c for c in chunk))
    return "\\s+".join(out)


def _captured_expectation(key: str, st: Step, cap: dict) -> list[str]:
    """One expectation constant, filled from real device output.

    The provenance is part of the artifact, not a commit message: an
    expectation whose origin is unknown cannot be reviewed, and these are the
    lines that decide whether a test passes.
    """
    lines = [
        _ascii(f"    /** {st.id} - {st.text}"),
        _ascii(f"     *  Captured from {cap.get('host', '?')} "
               f"({cap.get('build', '?')}) on {cap.get('captured_at', '?')}"),
        _ascii(f"     *  Command: {cap.get('command', '?')}"),
        "     */",
        f"    public final String[] {key} = new String[] {{",
    ]
    body = cap.get("lines") or []
    for i, raw in enumerate(body):
        sep = "," if i < len(body) - 1 else ""
        lines.append(f"        {_jstr(_line_to_regex(raw))}{sep}")
    lines.append("    };")
    return lines


def emit_params(scripts: list[TestScript], lab: LabProfile,
                captures: dict | None = None) -> JavaFile:
    """Expected values and lab bindings.

    Every `expect_key` referenced by a step becomes a `String[]` constant. Keys
    whose step is marked `todo` are emitted **empty**, with the reason inline —
    `EvpnUtils` treats an empty expectation as "not yet validated" and reports
    a warning rather than a pass.
    """
    seen: dict[str, Step] = {}
    for sc in scripts:
        for st in sc.steps:
            if st.expect_key and st.expect_key not in seen:
                seen[st.expect_key] = st

    lines = [
        f"package {PACKAGE};",
        "",
        "import common.params.ISuiteParams;",
        "import common.params.SuiteTableParams;",
        "",
        _header(
            "Expected values and lab bindings for the EVPN suite.",
            [
                f"Lab profile: {lab.id} — {lab.description}",
                "Constants that are EMPTY are expectations that could not be "
                "derived from the SFS/CLI documents — they need real device "
                "output. EvpnUtils reports a warning for an empty expectation "
                "instead of passing, so an unvalidated table can never show a "
                "green run.",
            ],
        ),
        "public class EvpnParams implements ISuiteParams {",
        "",
        "    // ---- lab bindings (overridden from the SUT file at run time) ----",
        f"    public final String EVI_NAME = {_jstr(lab.evi_name)};",
        f"    public final String BGP_NEIGHBOR = {_jstr(lab.bgp_neighbor)};",
    ]
    for ac in lab.acs:
        lines.append(
            f"    public final String {ac.name}_INTERFACE = "
            f"{_jstr(ac.interface)};")
    for ac in lab.acs:
        lines.append(
            f"    public final String {ac.name}_VPORT = {_jstr(ac.vport)};")
    for ti in lab.traffic_items:
        lines.append(
            f"    public final String {ti.name} = {_jstr(ti.name)};"
            f"  // {ti.src} -> {ti.dst}")
    lines.append("")
    lines.append("    // ---- traffic-item build parameters ----")
    lines.append("    // Their suites load these from a prebuilt .ixncfg; we build")
    lines.append("    // them over TCL instead, so the suite needs no binary file.")
    for ti in lab.traffic_items:
        src, dst = lab.ac(ti.src), lab.ac(ti.dst)
        lines.append(
            f"    public final String {ti.name}_SRC_VPORT = {_jstr(src.vport)};")
        lines.append(
            f"    public final String {ti.name}_DST_VPORT = {_jstr(dst.vport)};")
        lines.append(
            f"    public final String {ti.name}_SRC_MAC = {_jstr(ti.src_mac)};")
    same = [t.name for t in lab.traffic_items]
    shared = [t.name for t in lab.traffic_items
              if sum(1 for o in lab.traffic_items if o.src_mac == t.src_mac) > 1]
    if shared:
        lines.append(
            "    /** " + " and ".join(shared) + " share a source MAC on purpose:")
        lines.append(
            "     *  that is what makes moving between those ACs a LOCAL MAC move")
        lines.append(
            "     *  on one PE, which must not re-advertise a Type-2 route. */")
    _ = same
    lines.append("")
    lines.append("    /** {name, srcVport, dstVport, srcMac} per item, for")
    lines.append("     *  EvpnUtils.createTrafficItems(). */")
    lines.append("    public final String[][] TRAFFIC_ITEM_BUILD = {")
    for ti in lab.traffic_items:
        src, dst = lab.ac(ti.src), lab.ac(ti.dst)
        lines.append(
            f"        {{{_jstr(ti.name)}, {_jstr(src.vport)}, "
            f"{_jstr(dst.vport)}, {_jstr(ti.src_mac)}}},")
    lines.append("    };")
    lines.append("    /** IXIA vports backing the ACs, in AC order. */")
    lines.append("    public final String[] AC_VPORTS = {"
                 + ", ".join(_jstr(ac.vport) for ac in lab.acs) + "};")
    lines.append("    public final String TRAFFIC_RATE_FPS = \"1000\";")

    lines += [
        "",
        "    // ---- timing ----",
        f"    public final long VERIFY_TIMEOUT_IN_MSEC = {lab.verify_timeout_ms}L;",
        f"    public final long VERIFY_INTERVAL_IN_MSEC = {lab.verify_interval_ms}L;",
        "    /** TODO: confirm the EVPN MAC-aging default with Exaware; the",
        "     *  VPLS suite tunes this per platform with a wide deviation. */",
        f"    public final int MAC_AGING_TIME_IN_SEC = {lab.mac_aging_seconds};",
        "",
        "    // ---- expected output ----",
    ]
    for key in sorted(seen):
        st = seen[key]
        cap = (captures or {}).get(key)
        if cap:
            lines += _captured_expectation(key, st, cap)
        elif st.todo:
            lines.append(_ascii(
                f"    /** {st.id} - NOT YET VALIDATED. {st.todo} */"))
            lines.append(f"    public final String[] {key} = new String[] {{}};")
        else:
            lines.append(_ascii(f"    /** {st.id} - {st.text} */"))
            lines.append(f"    public final String[] {key} = new String[] {{}};")
        lines.append("")

    lines += [
        "    @Override",
        "    public SuiteTableParams[] getSuiteParamsTableToUpdate() {",
        "        return new SuiteTableParams[] {};",
        "    }",
        "",
        "    @Override",
        "    public SuiteTableParams[] getSuitesTablesToPrint() {",
        "        return new SuiteTableParams[] {};",
        "    }",
        "}",
        "",
    ]
    return JavaFile(path="cmp/tests/evpn/EvpnParams.java",
                    content="\n".join(lines))


# ── EvpnUtils ───────────────────────────────────────────────────────────────

_UTILS_BODY = '''
    private final EvpnParams params;
    private final CmpRouter cmp;
    private final Ixia ixia;

    public EvpnUtils(EvpnParams params, CmpRouter cmp, Ixia ixia) {
        this.params = params;
        this.cmp = cmp;
        this.ixia = ixia;
    }

    /**
     * Run a show command and assert every expected line (a regex) appears in
     * the output, polling until the verify timeout. Modelled on
     * ShowVplsDetail.verifyShowVplsDetail.
     *
     * An EMPTY expectation array means "not yet validated against a real
     * device": the command is still run and its output reported, but the
     * result is a warning, never a pass.
     */
    public void verifyShowLines(ICmpCliCmd command, String[] expectedLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);

        if (expectedLines == null || expectedLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - output captured for "
                    + "review, nothing asserted.");
            logMsg.info(output);
            return;
        }

        Set<String> missing = new LinkedHashSet<String>();
        boolean asExpected = false;
        long endTime = System.currentTimeMillis() + params.VERIFY_TIMEOUT_IN_MSEC;

        while (!asExpected && System.currentTimeMillis() < endTime) {
            missing.clear();
            asExpected = true;
            for (int i = 0; i < expectedLines.length; i++) {
                String expected = expectedLines[i];
                if (output == null
                        || !Pattern.compile(expected).matcher(output).find()) {
                    missing.add(expected);
                    asExpected = false;
                }
            }
            if (!asExpected) {
                Thread.sleep(params.VERIFY_INTERVAL_IN_MSEC);
                output = cmp.runCommandAndSwitch(command.toString(), command);
            }
        }

        falsifiableAssertions++;
        CompassReporter.passFailByCondition(asExpected,
                "The output of " + command.toString() + " is as expected.",
                "The output of " + command.toString()
                        + " is not as expected. Missing lines: " + missing);
    }

    /**
     * Build the suite's traffic items on the chassis.
     *
     * Exaware's own suites load a prebuilt binary .ixncfg at bring-up and only
     * suspend/unsuspend what it contains. That binary cannot be generated from
     * documents, so this suite stands up its own traffic over TCL instead -
     * the same chassis objects, no file to be handed.
     *
     * Idempotency is the chassis's business: call this once, before the first
     * setTrafficItemState. Every argument comes from EvpnParams, so a different
     * rig is a params change, not a code change.
     *
     * Argument order is VERIFIED against the proc signatures in
     * cmp-infra-project/src/main/java/cmp/infra/tcl/ixia_lib.tcl (2026-08-12),
     * not merely against the $arg help strings.
     *
     * LIMIT - the SOURCE MAC cannot be set from this library. ixia_lib.tcl
     * offers editTrafficRawDestMacAddr and no source equivalent, and
     * configTrafficItemStream takes only destinationMacMode. EVPN learns from
     * SOURCE MACs, so the FLOW-030 precondition that AC2 and AC3 emit the same
     * source MAC - which is what makes AC2 -> AC3 a local move rather than two
     * distinct hosts - cannot be expressed here. Those items still need either
     * a prebuilt .ixncfg or a new src-MAC proc in ixia_lib.tcl, which is
     * Exaware's file to extend. The per-item source MAC is carried in
     * EvpnParams so it is ready the moment either arrives.
     */
    public void createTrafficItems() throws Exception {
        // The vports have to exist before they can be tagged or used as
        // endpoints. Their suites get them from the .crt's interface rows,
        // which Ixia.loadConfigurationFile applies while loading an .ixncfg -
        // a file this suite deliberately does not have. Whatever vports happen
        // to be left in the chassis session from an earlier run are not ours.
        assignAcVports();
        tagVportsWithAcVlan();
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            String name = ti[0], srcVport = ti[1], dstVport = ti[2], srcMac = ti[3];
            logMsg.info("Creating IXIA traffic item " + name
                    + " (" + srcVport + " -> " + dstVport + ")");
            // Source MAC is set below, after the item exists.
            // "null" - not "" - is how their TCL spells an unset argument:
            // every proc in ixia_lib.tcl guards with
            // `if {[string match $arg null] != 1}`. An empty Java string
            // collapses during TCL word-splitting and the proc is called with
            // too few arguments, which answers `wrong # args` while
            // performFunctions still reports "ended without errors".
            ixia.performFunctions(IxiaFunctions.CONFIGURE_NEW_TRAFFIC_ITEM.args(
                    name, "true", "null", "l2L3", "false", "false", "raw",
                    name, "interleaved", "null", "false", "false", "oneToOne"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_ENDPOINTS.args(
                    name, "1", srcVport, "null", "null", "null", "null", "null",
                    "null", dstVport, "null", "null", "null", "null", "null",
                    "null", "null", "null", "null", name, "null", "null"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_STREAM.args(
                    name, "1", "goodCRC", "manual", name, "8", "auto", "false"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_FRAME_RATE.args(
                    name, "stream", "1", "framesPerSecond",
                    params.TRAFFIC_RATE_FPS, "bytes", "bitsPerSec", "false"));
        }
        // GENERATE binds the physical MACs and interfaces onto each raw item -
        // their own enum says so ("generate traffic item to apply physical mac
        // and interfaces to traffic source and destanation"). Without it the
        // items are configured but unresolved, and nothing is transmitted. It
        // runs BEFORE the source MAC is set; generating afterwards would
        // overwrite it.
        ixia.performFunctions(IxiaFunctions.GENERATE_TRAFFIC);

        // EVPN learns from SOURCE MACs, and ixia_lib.tcl exposes only
        // editTrafficRawDestMacAddr. It does not need a new proc: that one is a
        // single ixNet setAtt on the ethernet-1 stack, and the source field
        // sits beside the destination field on the same path. So the same
        // assignment is issued here as raw TCL, into the session where
        // ixia_lib.tcl is already sourced - their file is not modified.
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            setTrafficItemSourceMac(ti[0], ti[3]);
        }
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic items built on the chassis");
    }

    /**
     * Set a traffic item's source MAC, and CHECK the chassis took it.
     *
     * Mirrors ixia_lib.tcl's editTrafficRawDestMacAddr, with
     * ethernet.header.sourceAddress-1 in place of destinationAddress-1, and
     * reuses that file's own getTraffic helper. The value is read back rather
     * than assumed: an unapplied source MAC would leave the MAC-move flows
     * asserting something that never happened.
     */
    public void setTrafficItemSourceMac(String trafficItemName, String mac)
            throws Exception {
        final String field = "$ce/stack:\\\"ethernet-1\\\"/field:"
                + "\\\"ethernet.header.sourceAddress-1\\\"";
        ixia.runCommand(new RawTcl(
                "foreach ce [ixNet getL [getTraffic \\\"" + trafficItemName
                + "\\\"] configElement] { ixNet setAtt " + field
                + " -singleValue " + mac + " } ; ixNet commit"));

        // TclCli.runTclCommand returns only what lies BETWEEN the first and
        // last newline of the response. A single-line answer therefore comes
        // back as the empty string - which reads as "the chassis reported
        // nothing" when in fact it answered. Print the value on its own line.
        String readBack = ixia.runCommand(new RawTcl(
                "set out {} ; foreach ce [ixNet getL [getTraffic \\\""
                + trafficItemName + "\\\"] configElement] { append out ["
                + "ixNet getAtt " + field + " -singleValue] } ; "
                + "puts \\\"\\\" ; puts \\\"SRCMAC=$out\\\" ; puts \\\"\\\""));

        boolean applied = readBack != null
                && readBack.toLowerCase().contains(mac.toLowerCase());
        CompassReporter.passFailByCondition(applied,
                trafficItemName + ": source MAC " + mac + " applied on the chassis.",
                trafficItemName + ": source MAC " + mac + " was NOT applied - the"
                        + " chassis reports " + String.valueOf(readBack).trim()
                        + ". Any assertion that depends on this source MAC is"
                        + " unmet.");
    }

    /**
     * A raw TCL command for the IXIA session.
     *
     * Deliberately NOT an EvpnCommands constant: that enum is validated
     * against the EVPN CLI documentation at generation time, and TCL sent to
     * IxNetwork has no place in it.
     */
    private static final class RawTcl implements ICmpCliCmd {
        private final String tcl;

        RawTcl(String tcl) {
            this.tcl = tcl;
        }

        @Override
        public ICmpCliCmd args(Object... args) {
            return this;
        }

        @Override
        public String toString() {
            return this.tcl;
        }

        @Override
        public String stripArgs() {
            return this.tcl;
        }

        @Override
        public SessionMode getCmdSessionMode() {
            return SessionMode.CLI;
        }

        @Override
        public SessionType getCmdSessionType() {
            return SessionType.MGMT;
        }
    }

    /**
     * Enable the AC VLAN on every IXIA vport, and verify the chassis took it.
     *
     * Two things depend on this and both fail silently without it:
     *
     *  * frames must carry the AC VLAN or they never reach the sub-interface
     *    the EVI is bound to;
     *  * a RAW traffic item only accepts endpoints of the form
     *    `/vport:{id}/protocols`, and `configTrafficItemEndpoints` only builds
     *    that form when the vport's interface has a VLAN enabled. Without it
     *    the chassis answers "ERROR-6301-The endpoint is not correct for this
     *    type of trafficItem" - and performFunctions still reports the call as
     *    "ended without errors".
     *
     * The .crt carries `vlan` rows for the same purpose, but they are applied
     * by `Ixia.loadConfigurationFile`, which only runs for a device that has a
     * configuration file row - and this suite deliberately references no
     * .ixncfg. So the tagging is done here, where it is also verified.
     */
    public void assignAcVports() throws Exception {
        for (int i = 0; i < params.AC_VPORTS.length; i++) {
            String card = ixia.getIntPool(AC_POOL).getInter(i).getCard();
            String port = ixia.getIntPool(AC_POOL).getInter(i).getPort();
            logMsg.info("Assigning " + params.AC_VPORTS[i]
                    + " to card " + card + " port " + port);
            ixia.performFunctions(
                    IxiaFunctions.ASSIGN_VPORT_$_WITH_CARD_$_AND_PORT_$.args(
                            params.AC_VPORTS[i], card, port, "true"));
        }
    }

    /**
     * Enable the AC VLAN on every IXIA vport, and verify the chassis took it.
     */
    public void tagVportsWithAcVlan() throws Exception {
        String vlan = acVlan();
        for (String vport : params.AC_VPORTS) {
            // NOT IxiaFunctions.SET_AND_VERIFY_INTERFACE_$_VLAN_$: its proc
            // does `ixNet getL $vport vlan`, and the chassis rejects that -
            // "is not a valid child of /vport (possible options are: l1Config
            // capture protocols discoveredNeighbor interface ...)". The VLAN
            // hangs off the vport's INTERFACE, which is how their own
            // configTrafficItemEndpoints reaches it ($int/vlan). A vport with
            // no interface object gets one first; their suites get theirs from
            // the .ixncfg we deliberately do not load.
            String tcl =
                "set vp $ixia(" + vport + ") ; "
                + "set il [ixNet getL $vp interface] ; "
                + "if {[llength $il] == 0} { "
                +   "ixNet add $vp interface ; ixNet commit ; "
                +   "set il [ixNet getL $vp interface] ; "
                +   "ixNet setAtt [lindex $il 0] -enabled true ; ixNet commit "
                + "} ; "
                + "set int [lindex $il 0] ; "
                + "ixNet setMultiAtt $int/vlan -vlanEnable true ; ixNet commit ; "
                + "ixNet setMultiAtt $int/vlan -vlanId " + vlan + " ; ixNet commit ; "
                + "puts \\\"\\\" ; "
                + "puts \\\"ACVLAN=[ixNet getAtt $int/vlan -vlanId]"
                +   "/[ixNet getAtt $int/vlan -vlanEnable]\\\" ; "
                + "puts \\\"\\\"";
            String readBack = ixia.runCommand(new RawTcl(tcl));

            boolean ok = readBack != null
                    && readBack.contains("ACVLAN=" + vlan + "/true");
            CompassReporter.passFailByCondition(ok,
                    vport + ": VLAN " + vlan + " enabled on the IXIA interface.",
                    vport + ": VLAN " + vlan + " was NOT enabled (chassis said "
                            + oneLine(readBack) + ") - raw traffic endpoints "
                            + "will be rejected and no frame will reach the EVI.");
            if (!ok) {
                throw new Exception("could not tag " + vport + " with VLAN " + vlan);
            }
        }
    }

    /**
     * Start the traffic engine.
     *
     * Unsuspending an item is not the same as transmitting. Their suites load
     * an .ixncfg whose traffic is already running and only suspend/unsuspend
     * it; a suite that builds its own items must start them, or the chassis
     * holds three correctly configured items and sends nothing.
     */
    public void startTraffic() throws Exception {
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        ixia.performFunctions(IxiaFunctions.START_TRAFFIC);
        logMsg.info("Traffic started");
    }

    /** Stop the traffic engine. */
    public void stopTraffic() throws Exception {
        ixia.performFunctions(IxiaFunctions.STOP_TRAFFIC);
        logMsg.info("Traffic stopped");
    }

    /** Enable (unsuspend) or disable (suspend) one named IXIA traffic item. */
    public void setTrafficItemState(String trafficItemName, boolean enabled)
            throws Exception {
        ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_$_STATE_$
                .args(trafficItemName, String.valueOf(enabled)));
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic item " + trafficItemName + " enabled=" + enabled);
    }

    /**
     * How many assertions ran that COULD have failed.
     *
     * A suite that verified nothing must not be able to report success, so
     * this is counted rather than assumed, and checked at the end of the test.
     */
    private int falsifiableAssertions = 0;

    /**
     * Fail the test if nothing was actually verified.
     *
     * Called at the end of every generated test. A run in which every
     * verification step warned - because its expectation has never been
     * captured from a device - is not a pass; it is a run that proved the
     * plumbing works and checked no behaviour. Reporting that as green is how
     * a test suite stops being worth anything.
     */
    public void assertSomethingWasVerified() throws Exception {
        if (falsifiableAssertions == 0) {
            CompassReporter.fail("INCONCLUSIVE: this test made no assertion "
                    + "that could have failed. Every verification step ran its "
                    + "command and reported a warning, so the run says nothing "
                    + "about the feature. Capture the expectations "
                    + "(ate capture) and regenerate.");
            throw new Exception("no falsifiable assertion was made");
        }
        logMsg.info("Falsifiable assertions made: " + falsifiableAssertions);
    }

    /** Capture the current output of a command, for later no-change comparison. */
    public String snapshot(ICmpCliCmd command) throws Exception {
        return cmp.runCommandAndSwitch(command.toString(), command);
    }

    /**
     * Assert a command's output has NOT changed since the snapshot. Used for
     * the negative assertion that a purely local MAC move between two ACs on
     * the same PE triggers no new Type-2 advertisement.
     */
    public void verifyOutputUnchanged(String before, ICmpCliCmd command,
                                      String what) throws Exception {
        String after = cmp.runCommandAndSwitch(command.toString(), command);

        // An empty baseline makes this assertion vacuous: "nothing changed"
        // is trivially true when there was nothing to change, so it passes on
        // a device where the feature never worked. Seen for real - the
        // "no new Type-2 after a local MAC move" check compared
        // "% No entries found." with "% No entries found." and reported a pass.
        if (isEmptyTable(before)) {
            CompassReporter.warning(what + ": NOT ASSERTED - the baseline was "
                    + "empty (" + oneLine(before) + "), so 'unchanged' could "
                    + "not have failed. This needs a peer and traffic before it "
                    + "means anything.");
            return;
        }

        boolean unchanged = before.equals(after);
        falsifiableAssertions++;
        CompassReporter.passFailByCondition(unchanged,
                what + ": unchanged, as expected.",
                what + ": CHANGED unexpectedly.");
    }

    /** Did the device answer with no rows at all? */
    private boolean isEmptyTable(String output) {
        if (output == null) {
            return true;
        }
        String low = output.toLowerCase();
        return low.trim().isEmpty() || low.contains("no entries found");
    }

    /** Collapse output to one line, for a readable report message. */
    private String oneLine(String output) {
        if (output == null) {
            return "null";
        }
        String s = output.replace('\\r', ' ').replace('\\n', ' ').trim();
        return s.length() > 60 ? s.substring(0, 60) + "..." : s;
    }

    /**
     * IXIA per-port / per-flow statistics assertion.
     *
     * Left as an explicit gap: the expected rows depend on the port naming and
     * offered rate inside the .ixncfg that Exaware build for this rig, and
     * ShowIxiaStatistics drives them from a RowDataTable populated out of the
     * suite params table. Wiring that needs the real .ixncfg.
     */
    public void verifyIxiaStatistics(String what, String[] expectedRows)
            throws Exception {
        if (expectedRows == null || expectedRows.length == 0) {
            CompassReporter.warning("IXIA statistics check '" + what
                    + "' is not wired yet - needs the .ixncfg port naming and "
                    + "a RowDataTable in EvpnParams. See "
                    + "ShowIxiaStatistics.verifyDataPlanPortStatistics.");
            return;
        }
        CompassReporter.warning("IXIA statistics check '" + what
                + "' has expectations but no table binding yet.");
    }

    /** Sleep, reporting the wait so the run log explains the gap. */
    public void waitSeconds(int seconds, String why) throws Exception {
        logMsg.info("Waiting " + seconds + " sec: " + why);
        Thread.sleep(seconds * 1000L);
    }
'''


def _ac_binding_java(lab: LabProfile) -> str:
    """Resolve attachment circuits from the SUT, and never accept a rejection.

    Two lessons from running TC01 against pc-3080 (8.7.0 LAB 22):

    1. The interface names in the lab profile are PLACEHOLDERS. The `.cfg`
       always knew that — `bringUpParams.crt` binds `int1`/`int2`/`int3` to the
       SUT's intPool — but the Java steps used the placeholder text verbatim,
       so they sent `agg-eth-1.100` to a box whose ports are `x-eth 0/0/8`.
       The interface has to come from the same place the `.cfg` gets it: the
       SUT file. Then one suite runs on any testbed, which is the point.

    2. Those three rejected commands did not fail the test. The device
       answered `syntax error: "-1.100" is not a valid value`, nothing was
       staged, the commit reported "No modifications to commit", and the
       framework's own `configAndValidate` turns that into a WARNING. The run
       was green while configuring nothing. A test that passes without doing
       its work is worse than no test, so a configuration step here asserts
       that the device accepted the command.
    """
    pool = lab.ac_pool
    vlan_index = lab.ac_vlan_index
    return _ascii(f'''
    /** intPool in the SUT file that backs the attachment circuits. */
    private static final String AC_POOL = "{pool}";

    /** Index into the SUT's `general/vlans` list for the AC VLAN. */
    private static final int AC_VLAN_INDEX = {vlan_index};

    /**
     * The attachment circuit as THIS testbed defines it, e.g.
     * "x-eth 0/0/8.100" — the SUT's intPool entry plus the sub-interface.
     *
     * A vlan-based EVI will not accept the bare port; see EVPN_Base.cfg.
     */
    public String acInterface(int index) throws Exception {{
        return cmp.getIntPool(AC_POOL).getInter(index).getIntName()
               + "." + acVlan();
    }}

    /**
     * The VLAN the attachment circuits carry, taken from the SUT file.
     *
     * Both sides must agree or no frame ever reaches the service: the DUT
     * sub-interface is created as <port>.<vlan>, and the IXIA vport is tagged
     * with the same value by the `vlan` rows in bringUpParams.crt. Reading it
     * from the SUT rather than hard-coding it is what keeps that true on a
     * testbed whose VLAN is different.
     */
    public String acVlan() throws Exception {{
        return General.getInstanceByName().vlans[AC_VLAN_INDEX].getNumber();
    }}

    /**
     * Run a configuration command and REQUIRE the device to accept it.
     *
     * `CmpRouter.configAndValidate` commits and warns when the commit had
     * nothing to do. That is the right default for their suites, but it means
     * a command the CLI rejected outright leaves the test green: nothing was
     * staged, so there is nothing to commit, so there is only a warning. Here
     * a rejected command is a failed step.
     */
    public void configAndVerifyAccepted(ICmpCliCmd command) throws Exception {{
        String output = cmp.runCommandAndSwitch(command.toString(), command);
        if (wasRejected(output)) {{
            CompassReporter.fail("Device REJECTED '" + command.toString()
                    + "': " + String.valueOf(output).trim());
            throw new Exception("device rejected the command: " + command.toString());
        }}
        cmp.commitAndVerification(command.getCmdSessionType(),
                GlobalParam.LOAD_CONF_FILE_TIMEOUT_DEFAULT_MSEC);
    }}

    /** Did the CLI refuse the command it was given? */
    private boolean wasRejected(String output) {{
        if (output == null) {{
            return false;
        }}
        // Their own pattern first, then the plain reading of the same thing,
        // so a change in the framework's regexp cannot quietly turn this
        // assertion off.
        if (Pattern.compile(GlobalParam.CLI_COMMAND_SYNTAX_ERROR_REGEXP)
                   .matcher(output).find()) {{
            return true;
        }}
        String low = output.toLowerCase();
        return low.contains("syntax error")
               || low.contains("% invalid input")
               || low.contains("is not a valid value");
    }}
''')


def emit_utils(lab: LabProfile) -> JavaFile:
    lines = [
        f"package {PACKAGE};",
        "",
        "import java.util.LinkedHashSet;",
        "import java.util.Set;",
        "import java.util.regex.Pattern;",
        "",
        "import cmp.infra.CmpRouter;",
        "import cmp.infra.Session.ICmpCliCmd;",
        "import cmp.infra.Session.SessionMode;",
        "import cmp.infra.Session.SessionType;",
        "import cmp.infra.common.General;",
        "import cmp.infra.common.GlobalParam;",
        "import cmp.infra.ixia.Ixia;",
        "import cmp.infra.ixia.IxiaFunctions;",
        "import cmp.infra.reporter.CompassReporter;",
        "import cmp.infra.reporter.loggerImp;",
        "",
        _header(
            "Verification helpers for the generated EVPN suite.",
            [
                "Mirrors the shape of cmp.tests.vpls.VplsUtils: the test class "
                "stays a readable sequence of numbered steps and every "
                "assertion lives here.",
            ],
        ),
        "public class EvpnUtils implements loggerImp {",
        _ac_binding_java(lab),
        _UTILS_BODY.rstrip(),
        "}",
        "",
    ]
    return JavaFile(path="cmp/tests/evpn/EvpnUtils.java",
                    content="\n".join(lines))


# ── test classes ────────────────────────────────────────────────────────────

def _arg_expr(arg: str, lab: LabProfile) -> str:
    """One step argument as Java.

    Interface names are the exception to "arguments are literals". The lab
    profile spells an attachment circuit `agg-eth-1.100`, but that is a
    PLACEHOLDER: which port the circuit lives on is a property of the testbed,
    and pc-3080's are `x-eth 0/0/8`. Sending the placeholder text to the device
    is how three configuration commands came back
    `syntax error: "-1.100" is not a valid value`. Resolve it from the SUT
    instead, exactly as the `.cfg` does through `bringUpParams.crt`.
    """
    for i, ac in enumerate(lab.acs):
        if arg == ac.ac_interface:
            return f"evpnUtils.acInterface({i})"
    return _jstr(arg)


def _render_step(step: Step, lab: LabProfile,
                 captured: set[str] | None = None) -> list[str]:
    """One IR step → its Java lines (level banner + the call)."""
    out: list[str] = []
    if step.req_ids:
        out.append(_ascii(
            f"        // {step.id} - covers {', '.join(step.req_ids)}"))
    else:
        out.append(f"        // {step.id}")
    out.append("        CompassReporter.stopAndStartLevel(++level + "
               f"{_jstr('. ' + step.text)});")

    args = ", ".join(_arg_expr(a, lab) for a in step.args)
    cmd_expr = f"EvpnCommands.{step.command}" + (f".args({args})" if args else "")

    if step.kind is StepKind.CONFIG:
        out.append(f"        evpnUtils.configAndVerifyAccepted({cmd_expr});")
    elif step.kind in (StepKind.VERIFY_CLI, StepKind.VERIFY_ROUTE):
        expect = (f"testParams.{step.expect_key}" if step.expect_key
                  else "new String[] {}")
        out.append(f"        evpnUtils.verifyShowLines({cmd_expr}, {expect});")
    elif step.kind is StepKind.TRAFFIC_CREATE:
        out.append("        evpnUtils.createTrafficItems();")
    elif step.kind is StepKind.TRAFFIC_STATE:
        for ti in step.traffic_items:
            flag = "true" if step.enabled else "false"
            out.append(f"        evpnUtils.setTrafficItemState("
                       f"testParams.{ti}, {flag});")
    elif step.kind is StepKind.TRAFFIC_START:
        out.append("        evpnUtils.setTrafficItemState("
                   "testParams.TI_AC1_TO_AC2, true);")
        out.append("        evpnUtils.startTraffic();")
    elif step.kind is StepKind.TRAFFIC_STOP:
        for ti in step.traffic_items:
            out.append(f"        evpnUtils.setTrafficItemState("
                       f"testParams.{ti}, false);")
        out.append("        evpnUtils.stopTraffic();")
    elif step.kind is StepKind.WAIT:
        out.append(f"        evpnUtils.waitSeconds("
                   f"testParams.MAC_AGING_TIME_IN_SEC, {_jstr(step.text)});")
    elif step.kind is StepKind.VERIFY_IXIA:
        expect = (f"testParams.{step.expect_key}" if step.expect_key
                  else "new String[] {}")
        out.append(f"        evpnUtils.verifyIxiaStatistics("
                   f"{_jstr(step.text)}, {expect});")
    elif step.kind is StepKind.VERIFY_NO_EVENT:
        # Snapshot steps are emitted by `emit_test` (they need to assign into a
        # method-scoped local); anything else compares against that snapshot.
        out.append("        evpnUtils.verifyOutputUnchanged(routesBefore, "
                   f"{cmd_expr}, {_jstr(step.text)});")

    # A step whose expectation has since been captured from a device is no
    # longer "awaiting real device output", so it must not keep saying so. The
    # warning exists to stop an unvalidated table looking green; once the table
    # is real, the assertion speaks for itself.
    if step.todo and not (captured and step.expect_key in captured):
        out.append(f"        CompassReporter.warning({_jstr(step.id + ': ' + step.todo)});")
    out.append("")
    return out


def emit_test(script: TestScript, lab: LabProfile,
               captured: set[str] | None = None) -> JavaFile:
    extra = [script.summary]
    if script.depends_on:
        extra.append(
            "Prerequisite: " + ", ".join(script.depends_on)
            + ". Those flows must have run (or their configuration be present "
              "in the bring-up) before this test.")
    if script.covered_req_ids:
        extra.append("Covers: " + ", ".join(script.covered_req_ids) + ".")
    todos = script.open_todos
    if todos:
        extra.append(
            f"{len(todos)} of {len(script.steps)} steps still need real device "
            "output before their assertions are meaningful; those steps report "
            "a warning rather than a pass.")

    needs_snapshot = any(
        s.kind is StepKind.VERIFY_NO_EVENT and s.text.lower().startswith("snapshot")
        for s in script.steps)

    lines = [
        f"package {PACKAGE};",
        "",
        "import org.junit.Test;",
        "",
        "import cmp.infra.CmpRouter;",
        "import cmp.infra.CmpTestCase;",
        "import cmp.infra.bringUp.DevicesSut;",
        "import cmp.infra.ixia.Ixia;",
        "import cmp.infra.reporter.CompassReporter;",
        "",
        _header(f"{script.flow_id} - {script.title}", extra),
        f"public class {script.class_name} extends CmpTestCase {{",
        "",
        "    @Test",
        f"    public void {script.method_name}() throws Exception {{",
        "",
        f"        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.{lab.dut});",
        f"        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.{lab.ixia});",
        "        EvpnParams testParams = (EvpnParams) getSuiteParams();",
        "        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);",
        "",
        "        int level = 0;",
    ]
    if needs_snapshot:
        lines.append("        String routesBefore = null;")
    lines.append("")

    for step in script.steps:
        if (step.kind is StepKind.VERIFY_NO_EVENT
                and step.text.lower().startswith("snapshot")):
            args = ", ".join(_jstr(a) for a in step.args)
            cmd_expr = (f"EvpnCommands.{step.command}"
                        + (f".args({args})" if args else ""))
            lines.append(_ascii(
                f"        // {step.id} - covers {', '.join(step.req_ids)}"))
            lines.append("        CompassReporter.stopAndStartLevel("
                         f"++level + {_jstr('. ' + step.text)});")
            lines.append(f"        routesBefore = evpnUtils.snapshot({cmd_expr});")
            lines.append("")
            continue
        lines += _render_step(step, lab, captured)

    lines += [
        "        // PIPELINE RULE: a test that verified nothing is not a pass.",
        "        evpnUtils.assertSomethingWasVerified();",
        "        CompassReporter.stopLevel();",
        "    }",
        "}",
        "",
    ]
    return JavaFile(path=f"cmp/tests/evpn/{script.class_name}.java",
                    content="\n".join(lines))


def emit_all(scripts: list[TestScript], lab: LabProfile,
             captures: dict | None = None) -> list[JavaFile]:
    """Every artifact of the suite.

    `captures` maps an expect_key to one usable `ate capture` result. Keys it
    covers become real assertions carrying their provenance; keys it does not
    stay empty and keep warning.
    """
    captured = set(captures or {})
    files = [emit_commands(), emit_params(scripts, lab, captures),
             emit_utils(lab)]
    files += [emit_test(s, lab, captured) for s in scripts]
    return files
