# GENERATED by ate codegen - do not edit by hand.
#
# EVPN traffic items for lab profile 'lab-1dut-3ac-core'.
#
# WHY THIS FILE EXISTS
#   Exaware, 2026-09-08: a traffic item is expected to be human
#   readable, and ours were only readable as Java argument lists.
#   Everything the chassis is asked to build is stated below.
#
# WHAT IT PRODUCES
#   EVPN_3AC_CORE.ixncfg  - an IxNetwork save of exactly these items,
#   written by IxNetwork itself. Drop it into configurations/ixia/,
#   name it in LabProfile.ixncfg, regenerate, and bringUpParams.crt
#   loads it: from then on the suite only suspends and unsuspends
#   named items, which is the VPLS suite's idiom.
#
# HOW TO RUN IT (once, on the IXIA app server)
#   tclsh> source /var/tmp/ate-run/ixia_lib.tcl
#   tclsh> source /var/tmp/ate-run/EVPN_traffic.tcl
#   The path must be one BOTH the JVM host and the app server can
#   see. A path only the JVM host has is why ixia_lib.tcl silently
#   failed to load for a fortnight and 34 procs answered
#   'invalid command name' while the framework reported success.
#
# TOPOLOGY (from ate/codegen/lab.py, the same source the .cfg uses)
#   core  vport1   L3 29.60.0.2 -> 29.60.0.1   (no raw traffic on this port)
#   AC1   vport2   VLAN 1001  DUT int2.1001
#   AC2   vport3   VLAN 1002  DUT int3.1002
#   AC3   vport3   VLAN 1003  DUT int3.1003
#
#   vport3 carries more than one attachment circuit. They are
#   told apart by the VLAN tag on the frame, which is why every
#   item below pushes its own VLAN header. Exaware, 2026-09-08:
#   "An AC can reside as a tagged interface."

# ---------------------------------------------------------------
# Helpers. Two things ixia_lib.tcl does not do, kept in one place
# and used identically by the generated Java (EvpnUtils), so the
# file and the suite cannot build different traffic.
# ---------------------------------------------------------------

# Push a VLAN header onto a RAW item and set its VLAN ID.
#
# A raw item's frame is whatever its protocol stack says, and that
# stack is ethernet + fcs: UNTAGGED. Untagged frames never match a
# `vlan-id` sub-interface, so on pc-3080 the DUT port counted 219k
# frames while the circuit counted 0 and the EVI learnt nothing.
proc ateTagItemVlan {itemName vlan} {
    set tpl {}
    foreach t [ixNet getL [ixNet getRoot]/traffic protocolTemplate] {
        if {[string equal -nocase [ixNet getAtt $t -displayName] {VLAN}]} {
            set tpl $t
        }
    }
    set ti [getTraffic $itemName]
    foreach ce [ixNet getL $ti configElement] {
        set has 0
        foreach st [ixNet getL $ce stack] {
            if {[string match {*vlan*} $st]} { set has 1 }
        }
        if {$has == 0 && $tpl ne {}} {
            ixNet exec appendProtocol [lindex [ixNet getL $ce stack] 0] $tpl
            ixNet commit
        }
        foreach st [ixNet getL $ce stack] {
            if {![string match {*vlan*} $st]} { continue }
            foreach fld [ixNet getL $st field] {
                if {[string match -nocase {*vlan-id*} \
                        [ixNet getAtt $fld -displayName]]} {
                    ixNet setMultiAttr $fld -singleValue $vlan \
                        -fieldValue $vlan -valueType singleValue
                }
            }
        }
    }
    ixNet commit
}

# Set a RAW item's SOURCE MAC.
#
# ixia_lib.tcl has editTrafficRawDestMacAddr and no source twin, and
# EVPN learns from source MACs. The obvious mirror
# `ethernet.header.sourceAddress-1` does NOT exist: the suffix is the
# field's POSITION in the stack, so the source field is -2. Match on
# the display name instead of counting.
proc ateSetItemSrcMac {itemName mac} {
    set ti [getTraffic $itemName]
    foreach ce [ixNet getL $ti configElement] {
        foreach st [ixNet getL $ce stack] {
            if {![string match *ethernet* $st]} { continue }
            foreach fld [ixNet getL $st field] {
                if {[string match -nocase {*source*} \
                        [ixNet getAtt $fld -displayName]]} {
                    ixNet setMultiAttr $fld -singleValue $mac \
                        -fieldValue $mac -valueType singleValue
                }
            }
        }
    }
    ixNet commit
}

# ---------------------------------------------------------------
# The traffic items.
# ---------------------------------------------------------------

set ateFrameRateFps 1000

# TI_AC1_TO_AC2
#   AC1 (vport2, VLAN 1001) -> AC2 (vport3, VLAN 1002)
#   source MAC 00:00:01:00:00:01
configNewTrafficItem TI_AC1_TO_AC2 true null l2L3 false false raw TI_AC1_TO_AC2 interleaved null false false oneToOne
configTrafficItemEndpoints TI_AC1_TO_AC2 1 vport2 null null null null null null vport3 null null null null null null null null null TI_AC1_TO_AC2 null null
configTrafficItemStream TI_AC1_TO_AC2 1 goodCRC manual TI_AC1_TO_AC2 8 auto false
configTrafficItemFrameRate TI_AC1_TO_AC2 stream 1 framesPerSecond $ateFrameRateFps bytes bitsPerSec false
ateTagItemVlan TI_AC1_TO_AC2 1001

# TI_AC2_TO_AC1
#   AC2 (vport3, VLAN 1002) -> AC1 (vport2, VLAN 1001)
#   source MAC 00:00:02:00:00:01
#   shares that source MAC with TI_AC3_TO_AC1 on purpose: that is
#   what makes moving between those circuits a LOCAL MAC move on one
#   PE, which must not re-advertise a Type-2 route.
configNewTrafficItem TI_AC2_TO_AC1 true null l2L3 false false raw TI_AC2_TO_AC1 interleaved null false false oneToOne
configTrafficItemEndpoints TI_AC2_TO_AC1 1 vport3 null null null null null null vport2 null null null null null null null null null TI_AC2_TO_AC1 null null
configTrafficItemStream TI_AC2_TO_AC1 1 goodCRC manual TI_AC2_TO_AC1 8 auto false
configTrafficItemFrameRate TI_AC2_TO_AC1 stream 1 framesPerSecond $ateFrameRateFps bytes bitsPerSec false
ateTagItemVlan TI_AC2_TO_AC1 1002

# TI_AC3_TO_AC1
#   AC3 (vport3, VLAN 1003) -> AC1 (vport2, VLAN 1001)
#   source MAC 00:00:02:00:00:01
#   shares that source MAC with TI_AC2_TO_AC1 on purpose: that is
#   what makes moving between those circuits a LOCAL MAC move on one
#   PE, which must not re-advertise a Type-2 route.
configNewTrafficItem TI_AC3_TO_AC1 true null l2L3 false false raw TI_AC3_TO_AC1 interleaved null false false oneToOne
configTrafficItemEndpoints TI_AC3_TO_AC1 1 vport3 null null null null null null vport2 null null null null null null null null null TI_AC3_TO_AC1 null null
configTrafficItemStream TI_AC3_TO_AC1 1 goodCRC manual TI_AC3_TO_AC1 8 auto false
configTrafficItemFrameRate TI_AC3_TO_AC1 stream 1 framesPerSecond $ateFrameRateFps bytes bitsPerSec false
ateTagItemVlan TI_AC3_TO_AC1 1003

# GENERATE binds the physical MACs and interfaces onto each raw item.
# Without it the items are configured but unresolved and nothing is
# transmitted. It runs BEFORE the source MACs are set, because
# generating afterwards overwrites them.
ixNet exec generate [ixNet getL [ixNet getRoot]/traffic trafficItem]

ateSetItemSrcMac TI_AC1_TO_AC2 00:00:01:00:00:01
ateSetItemSrcMac TI_AC2_TO_AC1 00:00:02:00:00:01
ateSetItemSrcMac TI_AC3_TO_AC1 00:00:02:00:00:01

ixNet exec apply [ixNet getRoot]/traffic

# ---------------------------------------------------------------
# Save what was just built, so the suite can load it instead of
# building it. This is the step that produces the .ixncfg - the one
# piece of the VPLS idiom we could not reach from documents.
#
# Fetch the file off the app server afterwards and commit it under
# cmp/tests/evpn/configurations/ixia/.
# ---------------------------------------------------------------
set ateSavePath "/var/tmp/ate-run/EVPN_3AC_CORE.ixncfg"
ixNet exec saveConfig [ixNet writeTo $ateSavePath -overwrite true]
puts "SAVED=$ateSavePath"
