# GENERATED by ate codegen - do not edit by hand.
#
# Tester side of the core link for lab profile 'lab-1dut-3ac-core'.
# The DUT side of this same link is EVPN_Base.cfg; both are rendered
# from ate/codegen/lab.py, so they cannot drift apart.
#
# EVPN objects are deliberately NOT built here: emulating an EVPN
# speaker needs a BGP EVPN licence this chassis does not have, and
# the current TCs assert the EVPN address family in the session's
# CAPABILITIES, which the DUT advertises on its own.

package require IxTclNetwork
set vp /vport:1
set intf $vp/interface:1

# routed interface facing the DUT
ixNet setAtt $intf -enabled true -description lab-1dut-3ac-core-core
ixNet commit
set v4 [ixNet add $intf ipv4]
ixNet setAtt $v4 -ip 29.60.0.2 -gateway 29.60.0.1 -maskWidth 24
ixNet commit

# OSPF - must match the DUT's area and network type or the
# adjacency forms as EXSTART and never reaches FULL.
set ospf $vp/protocols/ospf
ixNet setAtt $ospf -enabled true
ixNet commit
set rtr [lindex [ixNet remapIds [ixNet add $ospf router]] 0]
ixNet setAtt $rtr -enabled true -routerId 29.60.0.2
ixNet commit
set oi [ixNet add $rtr interface]
ixNet setAtt $oi -enabled true -interfaces $intf -areaId 0 -networkType pointToPoint -metric 1 -mtu 1500 -connectedToDut true
ixNet commit

# LDP - transport labels for the EVPN service
set ldp $vp/protocols/ldp
ixNet setAtt $ldp -enabled true
ixNet commit
set lr [lindex [ixNet remapIds [ixNet add $ldp router]] 0]
ixNet setAtt $lr -enabled true -routerId 29.60.0.2
ixNet commit
set li [ixNet add $lr interface]
ixNet setAtt $li -enabled true -protocolInterface $intf -discoveryMode basic -labelSpaceId 0
ixNet commit

# BGP - ipv4-unicast only; see the note on EVPN above.
set bgp $vp/protocols/bgp
ixNet setAtt $bgp -enabled true
ixNet commit
set nr [lindex [ixNet remapIds [ixNet add $bgp neighborRange]] 0]
ixNet setAtt $nr -enabled true -evpn false -ipV4Unicast true -type internal -dutIpAddress 29.60.0.1 -localIpAddress 29.60.0.2 -localAsNumber 3029 -interfaces $intf -enableBgpId true -bgpId 29.60.0.2
ixNet commit

# take the port and start, then READ BACK - a start that returns
# without error is not evidence the protocol is running.
catch {ixNet exec connectPorts [list $vp]}
after 20000
if {[catch {ixNet exec start $vp/protocols/ospf} e]} { puts "START-OSPF-FAIL: $e" }
if {[catch {ixNet exec start $vp/protocols/ldp} e]} { puts "START-LDP-FAIL: $e" }
if {[catch {ixNet exec start $vp/protocols/bgp} e]} { puts "START-BGP-FAIL: $e" }
after 40000
puts "OSPF-RUNNING=[ixNet getAtt $vp/protocols/ospf -runningState]"
puts "LDP-RUNNING=[ixNet getAtt $vp/protocols/ldp -runningState]"
puts "BGP-RUNNING=[ixNet getAtt $vp/protocols/bgp -runningState]"
