package cmp.tests.evpn;

import common.params.ISuiteParams;
import common.params.SuiteTableParams;

/**
 * Expected values and lab bindings for the EVPN suite.
 *
 * Lab profile: lab-1dut-3ac - Single DUT, three IXIA ports as local ACs on
 * one EVI, plus a BGP EVPN session to a remote PE. AC2 and AC3 source
 * identical MACs so that shifting traffic from AC2 to AC3 is a purely local
 * MAC move.
 * Constants that are EMPTY are expectations that could not be derived from
 * the SFS/CLI documents - they need real device output. EvpnUtils reports a
 * warning for an empty expectation instead of passing, so an unvalidated
 * table can never show a green run.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class EvpnParams implements ISuiteParams {

    // ---- lab bindings (overridden from the SUT file at run time) ----
    public final String EVI_NAME = "evi-1";
    public final String BGP_NEIGHBOR = "PE2";
    public final String AC1_INTERFACE = "agg-eth-1";
    public final String AC2_INTERFACE = "agg-eth-2";
    public final String AC3_INTERFACE = "agg-eth-3";
    public final String AC1_VPORT = "vport1";
    public final String AC2_VPORT = "vport2";
    public final String AC3_VPORT = "vport3";
    public final String TI_AC1_TO_AC2 = "TI_AC1_TO_AC2";  // AC1 -> AC2
    public final String TI_AC2_TO_AC1 = "TI_AC2_TO_AC1";  // AC2 -> AC1
    public final String TI_AC3_TO_AC1 = "TI_AC3_TO_AC1";  // AC3 -> AC1

    // ---- traffic-item build parameters ----
    // Their suites load these from a prebuilt .ixncfg; we build
    // them over TCL instead, so the suite needs no binary file.
    public final String TI_AC1_TO_AC2_SRC_VPORT = "vport1";
    public final String TI_AC1_TO_AC2_DST_VPORT = "vport2";
    public final String TI_AC1_TO_AC2_SRC_MAC = "00:00:01:00:00:01";
    public final String TI_AC2_TO_AC1_SRC_VPORT = "vport2";
    public final String TI_AC2_TO_AC1_DST_VPORT = "vport1";
    public final String TI_AC2_TO_AC1_SRC_MAC = "00:00:02:00:00:01";
    public final String TI_AC3_TO_AC1_SRC_VPORT = "vport3";
    public final String TI_AC3_TO_AC1_DST_VPORT = "vport1";
    public final String TI_AC3_TO_AC1_SRC_MAC = "00:00:02:00:00:01";
    /** TI_AC2_TO_AC1 and TI_AC3_TO_AC1 share a source MAC on purpose:
     *  that is what makes moving between those ACs a LOCAL MAC move
     *  on one PE, which must not re-advertise a Type-2 route. */

    /** {name, srcVport, dstVport, srcMac} per item, for
     *  EvpnUtils.createTrafficItems(). */
    public final String[][] TRAFFIC_ITEM_BUILD = {
        {"TI_AC1_TO_AC2", "vport1", "vport2", "00:00:01:00:00:01"},
        {"TI_AC2_TO_AC1", "vport2", "vport1", "00:00:02:00:00:01"},
        {"TI_AC3_TO_AC1", "vport3", "vport1", "00:00:02:00:00:01"},
    };
    /** IXIA vports backing the ACs, in AC order. */
    public final String[] AC_VPORTS = {"vport1", "vport2", "vport3"};
    public final String TRAFFIC_RATE_FPS = "1000";

    // ---- timing ----
    public final long VERIFY_TIMEOUT_IN_MSEC = 30000L;
    public final long VERIFY_INTERVAL_IN_MSEC = 5000L;
    /** TODO: confirm the EVPN MAC-aging default with Exaware; the
     *  VPLS suite tunes this per platform with a wide deviation. */
    public final int MAC_AGING_TIME_IN_SEC = 300;

    // ---- expected output ----
    /** FLOW-010.S08 - Verify evi-1 is up and all three ACs are bound
     *  Captured from 10.3.80.1 (8.7.0: LAB 22) on 2026-08-13T00:19:29
     *  Command: show evpn detail
     */
    public final String[] FLOW010_S08_EVPN_DETAIL_LINES = new String[] {
        "EVPN\\s+name:\\s+evi-1",
        "Advertise\\s+MAC\\s+Addresses:\\s+Enabled",
        "ES\\s+DF\\s+Waiting\\s+Time:\\s+3\\s+seconds",
        "Export-rt:\\s+65000:1",
        "Import-rt:\\s+65000:1",
        "Service\\s+Type:\\s+vlan-based",
        "Host\\s+MAC\\s+Address\\s+Duplicate\\s+Detection:\\s+Disabled",
        "Move\\s+Interval:\\s+180\\s+seconds",
        "Move\\s+Counter:\\s+5",
        "Freeze\\s+Time:\\s+30\\s+seconds",
        "MAC\\s+Aging\\s+Time:\\s+300\\s+seconds",
        "MAC\\s+Limit:\\s+65520",
        "Unknown\\s+MAC\\s+Flooding:\\s+Disabled",
        "Control\\s+Word:\\s+Disabled",
        "Local\\s+Interfaces:",
        "INTERFACE\\s+ESI\\s+ES\\s+LABEL",
        "--------------------------------------------------------",
        "x-eth0/0/8\\.100\\s+-\\s+-",
        "x-eth0/0/18\\.100\\s+-\\s+-",
        "x-eth0/0/26\\.100\\s+-\\s+-"
    };

    /** FLOW-010.S09 - NOT YET VALIDATED. Needs real `show evpn mac-address-table` output. */
    public final String[] FLOW010_S09_MAC_TABLE_EMPTY_LINES = new String[] {};

    /** FLOW-010.S10 - NOT YET VALIDATED. Needs real output of the route table above. */
    public final String[] FLOW010_S10_TYPE3_ADVERTISED_LINES = new String[] {};

    /** FLOW-030.S03 - NOT YET VALIDATED. Expected per-port rx rows depend on the .ixncfg port naming and offered rate. */
    public final String[] FLOW030_S03_FLOOD_TO_AC2_AC3_ROWS = new String[] {};

    /** FLOW-030.S04 - NOT YET VALIDATED. Needs real MAC-table output plus the AC1 source-MAC range. */
    public final String[] FLOW030_S04_AC1_MACS_LEARNT_LINES = new String[] {};

    /** FLOW-030.S05 - NOT YET VALIDATED. Needs real output of the route table above. */
    public final String[] FLOW030_S05_AC1_TYPE2_ADVERTISED_LINES = new String[] {};

    /** FLOW-030.S07 - NOT YET VALIDATED. Expected rows depend on .ixncfg port naming. */
    public final String[] FLOW030_S07_NO_FLOOD_TO_AC3_ROWS = new String[] {};

    /** FLOW-030.S09 - NOT YET VALIDATED. Needs real MAC-table output plus the AC2 source-MAC range. */
    public final String[] FLOW030_S09_AC2_MACS_LEARNT_LINES = new String[] {};

    /** FLOW-030.S10 - NOT YET VALIDATED. Needs real output of the route table above. */
    public final String[] FLOW030_S10_AC2_TYPE2_ADVERTISED_LINES = new String[] {};

    /** FLOW-030.S12 - NOT YET VALIDATED. Expected rows depend on .ixncfg port naming. */
    public final String[] FLOW030_S12_UNICAST_TO_AC2_ROWS = new String[] {};

    /** FLOW-030.S15 - NOT YET VALIDATED. Needs real MAC-table output. */
    public final String[] FLOW030_S15_MACS_MOVED_TO_AC3_LINES = new String[] {};

    /** FLOW-030.S17 - NOT YET VALIDATED. Expected rows depend on .ixncfg port naming. */
    public final String[] FLOW030_S17_UNICAST_TO_AC3_ROWS = new String[] {};

    /** FLOW-031.S04 - NOT YET VALIDATED. Needs real MAC-table output. */
    public final String[] FLOW031_S04_MACS_AGED_OUT_LINES = new String[] {};

    /** FLOW-031.S05 - NOT YET VALIDATED. Needs real BGP EVPN table output. */
    public final String[] FLOW031_S05_TYPE2_WITHDRAWN_LINES = new String[] {};

    /** FLOW-031.S06 - Verify the BUM routing table still lists the flood list
     *  Captured from 10.3.80.1 (8.7.0: LAB 22) on 2026-08-13T00:19:29
     *  Command: show evpn broadcast-domains name evi-1
     */
    public final String[] FLOW031_S06_BUM_BROADCAST_DOMAIN_LINES = new String[] {
        "EVPN\\s+Name:\\s+evi-1,\\s+Service\\s+Type:\\s+vlan-based",
        "Local\\s+BUM\\s+Label:\\s+32768",
        "Local\\s+Interfaces:",
        "x-eth0/0/8\\.100",
        "x-eth0/0/18\\.100",
        "x-eth0/0/26\\.100"
    };

    @Override
    public SuiteTableParams[] getSuiteParamsTableToUpdate() {
        return new SuiteTableParams[] {};
    }

    @Override
    public SuiteTableParams[] getSuitesTablesToPrint() {
        return new SuiteTableParams[] {};
    }
}
