package cmp.tests.evpn;

import cmp.infra.Session.ICmpCliCmd;
import cmp.infra.Session.SessionMode;
import cmp.infra.Session.SessionType;

/**
 * EVPN CLI command templates.
 *
 * Kept as a standalone enum rather than appended to
 * cmp.tests.common.Commands: every CmpRouter entry point takes the
 * ICmpCliCmd interface, so this is a drop-in, and the shared 1220-line
 * Commands enum stays free of merge conflicts.
 * Every constant below traces to a command in the EVPN CLI doc; the
 * documented syntax is quoted above each one.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public enum EvpnCommands implements ICmpCliCmd {

    /** CLI doc: evpn - evpn evpn-name [service-type {vlan-based | vlan-bundle | vlan-aware-bundle | port-based}] */
    CONFIGURE_L2_SERVICES_EVPN_$_SERVICE_TYPE_$("l2-services evpn %s service-type %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: evpn - no evpn */
    CONFIGURE_NO_L2_SERVICES_EVPN_$("no l2-services evpn %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: auto-discovery - auto-discovery */
    CONFIGURE_L2_SERVICES_EVPN_$_AUTO_DISCOVERY("l2-services evpn %s auto-discovery", SessionMode.CLI_CONFIGURE),

    /** CLI doc: import-rt - import-rt route-target */
    CONFIGURE_L2_SERVICES_EVPN_$_IMPORT_RT_$("l2-services evpn %s import-rt %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: export-rt - export-rt route-target */
    CONFIGURE_L2_SERVICES_EVPN_$_EXPORT_RT_$("l2-services evpn %s export-rt %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: interface (VPLS/EVPN) - interface if-name */
    CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$("l2-services evpn %s interface %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: mac-aging-time - mac-aging-time seconds */
    CONFIGURE_L2_SERVICES_EVPN_$_MAC_AGING_TIME_$("l2-services evpn %s mac-aging-time %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: mac-aging-time - no mac-aging-time */
    CONFIGURE_NO_L2_SERVICES_EVPN_$_MAC_AGING_TIME("no l2-services evpn %s mac-aging-time", SessionMode.CLI_CONFIGURE),

    /** CLI doc: unknown-mac-flooding - unknow-mac-flooding enable | disable */
    // WARNING -- verify against the DUT before first run:
    // CLI doc spells this 'unknow-mac-flooding' (missing 'n') in the syntax AND
    // in both parameter descriptions, while the heading says
    // 'unknown-mac-flooding'. Consistent misspelling usually means the product
    // itself has it, so the template follows the SYNTAX verbatim. Not exercised
    // by any current step, so it blocks nothing; confirm before a step starts
    // using it.
    CONFIGURE_L2_SERVICES_EVPN_$_UNKNOWN_MAC_FLOODING_$("l2-services evpn %s unknow-mac-flooding %s", SessionMode.CLI_CONFIGURE),

    /** CLI doc: show evpn global - show evpn global [name evpn-name] */
    SHOW_EVPN_GLOBAL("show evpn global"),

    /** CLI doc: show evpn global - show evpn global [name evpn-name] */
    SHOW_EVPN_GLOBAL_NAME_$("show evpn global name %s"),

    /** CLI doc: show evpn summary - show evpn summary [name evpn-name] */
    SHOW_EVPN_SUMMARY_NAME_$("show evpn summary name %s"),

    /** CLI doc: show evpn mac address-table - show evpn mac-address-table [name evpn-name [source interface | mac mac-address]] */
    SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$("show evpn mac address-table name %s"),

    /** CLI doc: show evpn mac address-table - show evpn mac-address-table [name evpn-name [source interface | mac mac-address]] */
    SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$("show evpn mac address-table name %s source %s"),

    /** CLI doc: show evpn bum routing-table - show evpn bum routing-table [name evpn-name [vlan-id vlan-id]] */
    SHOW_EVPN_BUM_ROUTING_TABLE_NAME_$("show evpn bum routing-table name %s"),

    /** CLI doc: clear evpn mac address-table - clear evpn mac address-table [name evpn-name [source interface | mac mac-address]] */
    CLEAR_EVPN_MAC_ADDRESS_TABLE_NAME_$("clear evpn mac address-table name %s"),

    /** CLI doc: show bgp l2vpn evpn table evi - show bgp l2vpn evpn table evi [evi-name evi-name [evpn-prefix]] [brief | detail] */
    SHOW_BGP_L2VPN_EVPN_TABLE_EVI_NAME_$_DETAIL("show bgp l2vpn evpn table evi evi-name %s detail"),

    /** CLI doc: show bgp l2vpn evpn neighbors advertised/received routes - show bgp l2vpn evpn neighbors {advertised-routes | received-routes} [neighbor-ip [evpn-prefix]] [brief | detail] */
    SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL("show bgp l2vpn evpn neighbors advertised-routes %s detail");

    private final String format;
    private String formattedStr;
    private SessionMode cmpSessionMode = SessionMode.CLI;
    private SessionType cmpSessionType = SessionType.MGMT;

    private EvpnCommands(String format) {
        this.format = format;
        this.formattedStr = format;
    }

    private EvpnCommands(String format, SessionMode cmpSessionMode) {
        this.format = format;
        this.formattedStr = format;
        this.cmpSessionMode = cmpSessionMode;
    }

    @Override
    public EvpnCommands args(Object... args) {
        this.formattedStr = String.format(this.format, args);
        return this;
    }

    @Override
    public String toString() {
        return this.formattedStr;
    }

    @Override
    public String stripArgs() {
        int specialCharIndex = this.format.indexOf('%');
        if (specialCharIndex > 0) {
            return this.format.substring(0, specialCharIndex).trim();
        }
        return this.format;
    }

    @Override
    public SessionMode getCmdSessionMode() {
        return this.cmpSessionMode;
    }

    @Override
    public SessionType getCmdSessionType() {
        return this.cmpSessionType;
    }
}
