package cmp.tests.evpn;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Pattern;

import cmp.infra.CmpRouter;
import cmp.infra.Session.ICmpCliCmd;
import cmp.infra.Session.SessionMode;
import cmp.infra.Session.SessionType;
import cmp.infra.common.GlobalParam;
import cmp.infra.ixia.Ixia;
import cmp.infra.ixia.IxiaFunctions;
import cmp.infra.reporter.CompassReporter;
import cmp.infra.reporter.loggerImp;

/**
 * Verification helpers for the generated EVPN suite.
 *
 * Mirrors the shape of cmp.tests.vpls.VplsUtils: the test class stays a
 * readable sequence of numbered steps and every assertion lives here.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class EvpnUtils implements loggerImp {

    /** intPool in the SUT file that backs the attachment circuits. */
    private static final String AC_POOL = "data1";

    /** Sub-interface each attachment circuit is created as. */
    private static final int AC_SUBINTERFACE = 100;

    /**
     * The attachment circuit as THIS testbed defines it, e.g.
     * "x-eth 0/0/8.100" - the SUT's intPool entry plus the sub-interface.
     *
     * A vlan-based EVI will not accept the bare port; see EVPN_Base.cfg.
     */
    public String acInterface(int index) throws Exception {
        return cmp.getIntPool(AC_POOL).getInter(index).getIntName()
               + "." + AC_SUBINTERFACE;
    }

    /**
     * Run a configuration command and REQUIRE the device to accept it.
     *
     * `CmpRouter.configAndValidate` commits and warns when the commit had
     * nothing to do. That is the right default for their suites, but it means
     * a command the CLI rejected outright leaves the test green: nothing was
     * staged, so there is nothing to commit, so there is only a warning. Here
     * a rejected command is a failed step.
     */
    public void configAndVerifyAccepted(ICmpCliCmd command) throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);
        if (wasRejected(output)) {
            CompassReporter.fail("Device REJECTED '" + command.toString()
                    + "': " + String.valueOf(output).trim());
            throw new Exception("device rejected the command: " + command.toString());
        }
        cmp.commitAndVerification(command.getCmdSessionType(),
                GlobalParam.LOAD_CONF_FILE_TIMEOUT_DEFAULT_MSEC);
    }

    /** Did the CLI refuse the command it was given? */
    private boolean wasRejected(String output) {
        if (output == null) {
            return false;
        }
        // Their own pattern first, then the plain reading of the same thing,
        // so a change in the framework's regexp cannot quietly turn this
        // assertion off.
        if (Pattern.compile(GlobalParam.CLI_COMMAND_SYNTAX_ERROR_REGEXP)
                   .matcher(output).find()) {
            return true;
        }
        String low = output.toLowerCase();
        return low.contains("syntax error")
               || low.contains("% invalid input")
               || low.contains("is not a valid value");
    }


    private final EvpnParams params;
    private final CmpRouter cmp;
    private final Ixia ixia;

    public EvpnUtils(EvpnParams params, CmpRouter cmp, Ixia ixia) {
        this.params = params;
        this.cmp = cmp;
        this.ixia = ixia;
    }

    /**
     * Run a show command and assert every expected line (a regex) appears in
     * the output, polling until the verify timeout. Modelled on
     * ShowVplsDetail.verifyShowVplsDetail.
     *
     * An EMPTY expectation array means "not yet validated against a real
     * device": the command is still run and its output reported, but the
     * result is a warning, never a pass.
     */
    public void verifyShowLines(ICmpCliCmd command, String[] expectedLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);

        if (expectedLines == null || expectedLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - output captured for "
                    + "review, nothing asserted.");
            logMsg.info(output);
            return;
        }

        Set<String> missing = new LinkedHashSet<String>();
        boolean asExpected = false;
        long endTime = System.currentTimeMillis() + params.VERIFY_TIMEOUT_IN_MSEC;

        while (!asExpected && System.currentTimeMillis() < endTime) {
            missing.clear();
            asExpected = true;
            for (int i = 0; i < expectedLines.length; i++) {
                String expected = expectedLines[i];
                if (output == null
                        || !Pattern.compile(expected).matcher(output).find()) {
                    missing.add(expected);
                    asExpected = false;
                }
            }
            if (!asExpected) {
                Thread.sleep(params.VERIFY_INTERVAL_IN_MSEC);
                output = cmp.runCommandAndSwitch(command.toString(), command);
            }
        }

        falsifiableAssertions++;
        CompassReporter.passFailByCondition(asExpected,
                "The output of " + command.toString() + " is as expected.",
                "The output of " + command.toString()
                        + " is not as expected. Missing lines: " + missing);
    }

    /**
     * Build the suite's traffic items on the chassis.
     *
     * Exaware's own suites load a prebuilt binary .ixncfg at bring-up and only
     * suspend/unsuspend what it contains. That binary cannot be generated from
     * documents, so this suite stands up its own traffic over TCL instead -
     * the same chassis objects, no file to be handed.
     *
     * Idempotency is the chassis's business: call this once, before the first
     * setTrafficItemState. Every argument comes from EvpnParams, so a different
     * rig is a params change, not a code change.
     *
     * Argument order is VERIFIED against the proc signatures in
     * cmp-infra-project/src/main/java/cmp/infra/tcl/ixia_lib.tcl (2026-08-12),
     * not merely against the $arg help strings.
     *
     * LIMIT - the SOURCE MAC cannot be set from this library. ixia_lib.tcl
     * offers editTrafficRawDestMacAddr and no source equivalent, and
     * configTrafficItemStream takes only destinationMacMode. EVPN learns from
     * SOURCE MACs, so the FLOW-030 precondition that AC2 and AC3 emit the same
     * source MAC - which is what makes AC2 -> AC3 a local move rather than two
     * distinct hosts - cannot be expressed here. Those items still need either
     * a prebuilt .ixncfg or a new src-MAC proc in ixia_lib.tcl, which is
     * Exaware's file to extend. The per-item source MAC is carried in
     * EvpnParams so it is ready the moment either arrives.
     */
    public void createTrafficItems() throws Exception {
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            String name = ti[0], srcVport = ti[1], dstVport = ti[2], srcMac = ti[3];
            logMsg.info("Creating IXIA traffic item " + name
                    + " (" + srcVport + " -> " + dstVport + ")");
            // Source MAC is set below, after the item exists.
            // "null" - not "" - is how their TCL spells an unset argument:
            // every proc in ixia_lib.tcl guards with
            // `if {[string match $arg null] != 1}`. An empty Java string
            // collapses during TCL word-splitting and the proc is called with
            // too few arguments, which answers `wrong # args` while
            // performFunctions still reports "ended without errors".
            ixia.performFunctions(IxiaFunctions.CONFIGURE_NEW_TRAFFIC_ITEM.args(
                    name, "true", "null", "l2L3", "false", "false", "raw",
                    name, "interleaved", "null", "false", "false", "oneToOne"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_ENDPOINTS.args(
                    name, "1", srcVport, "null", "null", "null", "null", "null",
                    "null", dstVport, "null", "null", "null", "null", "null",
                    "null", "null", "null", "null", name, "null", "null"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_STREAM.args(
                    name, "1", "goodCRC", "manual", name, "8", "auto", "false"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_FRAME_RATE.args(
                    name, "stream", "1", "framesPerSecond",
                    params.TRAFFIC_RATE_FPS, "bytes", "bitsPerSec", "false"));
        }
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);

        // EVPN learns from SOURCE MACs, and ixia_lib.tcl exposes only
        // editTrafficRawDestMacAddr. It does not need a new proc: that one is a
        // single ixNet setAtt on the ethernet-1 stack, and the source field
        // sits beside the destination field on the same path. So the same
        // assignment is issued here as raw TCL, into the session where
        // ixia_lib.tcl is already sourced - their file is not modified.
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            setTrafficItemSourceMac(ti[0], ti[3]);
        }
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic items built on the chassis");
    }

    /**
     * Set a traffic item's source MAC, and CHECK the chassis took it.
     *
     * Mirrors ixia_lib.tcl's editTrafficRawDestMacAddr, with
     * ethernet.header.sourceAddress-1 in place of destinationAddress-1, and
     * reuses that file's own getTraffic helper. The value is read back rather
     * than assumed: an unapplied source MAC would leave the MAC-move flows
     * asserting something that never happened.
     */
    public void setTrafficItemSourceMac(String trafficItemName, String mac)
            throws Exception {
        final String field = "$ce/stack:\"ethernet-1\"/field:"
                + "\"ethernet.header.sourceAddress-1\"";
        ixia.runCommand(new RawTcl(
                "foreach ce [ixNet getL [getTraffic \"" + trafficItemName
                + "\"] configElement] { ixNet setAtt " + field
                + " -singleValue " + mac + " } ; ixNet commit"));

        String readBack = ixia.runCommand(new RawTcl(
                "set out {} ; foreach ce [ixNet getL [getTraffic \""
                + trafficItemName + "\"] configElement] { append out ["
                + "ixNet getAtt " + field + " -singleValue] } ; set out"));

        boolean applied = readBack != null
                && readBack.toLowerCase().contains(mac.toLowerCase());
        CompassReporter.passFailByCondition(applied,
                trafficItemName + ": source MAC " + mac + " applied on the chassis.",
                trafficItemName + ": source MAC " + mac + " was NOT applied - the"
                        + " chassis reports " + String.valueOf(readBack).trim()
                        + ". Any assertion that depends on this source MAC is"
                        + " unmet.");
    }

    /**
     * A raw TCL command for the IXIA session.
     *
     * Deliberately NOT an EvpnCommands constant: that enum is validated
     * against the EVPN CLI documentation at generation time, and TCL sent to
     * IxNetwork has no place in it.
     */
    private static final class RawTcl implements ICmpCliCmd {
        private final String tcl;

        RawTcl(String tcl) {
            this.tcl = tcl;
        }

        @Override
        public ICmpCliCmd args(Object... args) {
            return this;
        }

        @Override
        public String toString() {
            return this.tcl;
        }

        @Override
        public String stripArgs() {
            return this.tcl;
        }

        @Override
        public SessionMode getCmdSessionMode() {
            return SessionMode.CLI;
        }

        @Override
        public SessionType getCmdSessionType() {
            return SessionType.MGMT;
        }
    }

    /** Enable (unsuspend) or disable (suspend) one named IXIA traffic item. */
    public void setTrafficItemState(String trafficItemName, boolean enabled)
            throws Exception {
        ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_$_STATE_$
                .args(trafficItemName, String.valueOf(enabled)));
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic item " + trafficItemName + " enabled=" + enabled);
    }

    /**
     * How many assertions ran that COULD have failed.
     *
     * A suite that verified nothing must not be able to report success, so
     * this is counted rather than assumed, and checked at the end of the test.
     */
    private int falsifiableAssertions = 0;

    /**
     * Fail the test if nothing was actually verified.
     *
     * Called at the end of every generated test. A run in which every
     * verification step warned - because its expectation has never been
     * captured from a device - is not a pass; it is a run that proved the
     * plumbing works and checked no behaviour. Reporting that as green is how
     * a test suite stops being worth anything.
     */
    public void assertSomethingWasVerified() throws Exception {
        if (falsifiableAssertions == 0) {
            CompassReporter.fail("INCONCLUSIVE: this test made no assertion "
                    + "that could have failed. Every verification step ran its "
                    + "command and reported a warning, so the run says nothing "
                    + "about the feature. Capture the expectations "
                    + "(ate capture) and regenerate.");
            throw new Exception("no falsifiable assertion was made");
        }
        logMsg.info("Falsifiable assertions made: " + falsifiableAssertions);
    }

    /** Capture the current output of a command, for later no-change comparison. */
    public String snapshot(ICmpCliCmd command) throws Exception {
        return cmp.runCommandAndSwitch(command.toString(), command);
    }

    /**
     * Assert a command's output has NOT changed since the snapshot. Used for
     * the negative assertion that a purely local MAC move between two ACs on
     * the same PE triggers no new Type-2 advertisement.
     */
    public void verifyOutputUnchanged(String before, ICmpCliCmd command,
                                      String what) throws Exception {
        String after = cmp.runCommandAndSwitch(command.toString(), command);

        // An empty baseline makes this assertion vacuous: "nothing changed"
        // is trivially true when there was nothing to change, so it passes on
        // a device where the feature never worked. Seen for real - the
        // "no new Type-2 after a local MAC move" check compared
        // "% No entries found." with "% No entries found." and reported a pass.
        if (isEmptyTable(before)) {
            CompassReporter.warning(what + ": NOT ASSERTED - the baseline was "
                    + "empty (" + oneLine(before) + "), so 'unchanged' could "
                    + "not have failed. This needs a peer and traffic before it "
                    + "means anything.");
            return;
        }

        boolean unchanged = before.equals(after);
        falsifiableAssertions++;
        CompassReporter.passFailByCondition(unchanged,
                what + ": unchanged, as expected.",
                what + ": CHANGED unexpectedly.");
    }

    /** Did the device answer with no rows at all? */
    private boolean isEmptyTable(String output) {
        if (output == null) {
            return true;
        }
        String low = output.toLowerCase();
        return low.trim().isEmpty() || low.contains("no entries found");
    }

    /** Collapse output to one line, for a readable report message. */
    private String oneLine(String output) {
        if (output == null) {
            return "null";
        }
        String s = output.replace('\r', ' ').replace('\n', ' ').trim();
        return s.length() > 60 ? s.substring(0, 60) + "..." : s;
    }

    /**
     * IXIA per-port / per-flow statistics assertion.
     *
     * Left as an explicit gap: the expected rows depend on the port naming and
     * offered rate inside the .ixncfg that Exaware build for this rig, and
     * ShowIxiaStatistics drives them from a RowDataTable populated out of the
     * suite params table. Wiring that needs the real .ixncfg.
     */
    public void verifyIxiaStatistics(String what, String[] expectedRows)
            throws Exception {
        if (expectedRows == null || expectedRows.length == 0) {
            CompassReporter.warning("IXIA statistics check '" + what
                    + "' is not wired yet - needs the .ixncfg port naming and "
                    + "a RowDataTable in EvpnParams. See "
                    + "ShowIxiaStatistics.verifyDataPlanPortStatistics.");
            return;
        }
        CompassReporter.warning("IXIA statistics check '" + what
                + "' has expectations but no table binding yet.");
    }

    /** Sleep, reporting the wait so the run log explains the gap. */
    public void waitSeconds(int seconds, String why) throws Exception {
        logMsg.info("Waiting " + seconds + " sec: " + why);
        Thread.sleep(seconds * 1000L);
    }
}
