package cmp.tests.evpn;

import cmp.infra.ixia.tableHeader.TrafficItemStatisticsHeaders;
import cmp.tests.common.query.QueryCmdTime;
import common.params.ColDataTable;
import common.params.ISuiteParams;
import common.params.RowDataTable;
import common.params.SuiteTableParams;

/**
 * Expected values and lab bindings for the EVPN suite.
 *
 * Lab profile: lab-1dut-3ac-core - Single DUT on pc-3080/pc-3099. IXIA
 * vport1 is the core: an emulated BGP EVPN peer over a point-to-point L3
 * link. vport2 and vport3 carry THREE attachment circuits between them, as
 * tagged sub-interfaces - AC2 and AC3 share vport3 and differ only by VLAN.
 * Three ACs and a control plane on three links, per Exaware 2026-09-08.
 * Constants that are EMPTY are expectations that could not be derived from
 * the SFS/CLI documents - they need real device output. EvpnUtils reports a
 * warning for an empty expectation instead of passing, so an unvalidated
 * table can never show a green run.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class EvpnParams implements ISuiteParams {

    // ---- lab bindings (overridden from the SUT file at run time) ----
    public final String EVI_NAME = "evi-1";
    public final String BGP_NEIGHBOR = "PE2";
    public final String AC1_INTERFACE = "agg-eth-2";
    public final String AC2_INTERFACE = "agg-eth-3";
    public final String AC3_INTERFACE = "agg-eth-3";
    public final String AC1_VPORT = "vport2";
    public final String AC2_VPORT = "vport3";
    public final String AC3_VPORT = "vport3";
    public final String TI_AC1_TO_AC2 = "TI_AC1_TO_AC2";  // AC1 -> AC2
    public final String TI_AC2_TO_AC1 = "TI_AC2_TO_AC1";  // AC2 -> AC1
    public final String TI_AC3_TO_AC1 = "TI_AC3_TO_AC1";  // AC3 -> AC1

    // ---- traffic-item build parameters ----
    // Their suites load these from a prebuilt .ixncfg; we build
    // them over TCL instead, so the suite needs no binary file.
    public final String TI_AC1_TO_AC2_SRC_VPORT = "vport2";
    public final String TI_AC1_TO_AC2_DST_VPORT = "vport3";
    public final String TI_AC1_TO_AC2_SRC_MAC = "00:00:01:00:00:01";
    public final String TI_AC2_TO_AC1_SRC_VPORT = "vport3";
    public final String TI_AC2_TO_AC1_DST_VPORT = "vport2";
    public final String TI_AC2_TO_AC1_SRC_MAC = "00:00:02:00:00:01";
    public final String TI_AC3_TO_AC1_SRC_VPORT = "vport3";
    public final String TI_AC3_TO_AC1_DST_VPORT = "vport2";
    public final String TI_AC3_TO_AC1_SRC_MAC = "00:00:02:00:00:01";
    /** TI_AC2_TO_AC1 and TI_AC3_TO_AC1 share a source MAC on purpose:
     *  that is what makes moving between those ACs a LOCAL MAC move
     *  on one PE, which must not re-advertise a Type-2 route. */

    /** {name, srcVport, dstVport, srcMac, vlan} per item,
     *  for EvpnUtils.createTrafficItems(). The VLAN is the
     *  SOURCE circuit's: it is what the DUT classifies the
     *  frame by, and on a rig where two circuits share a
     *  vport it is the only thing that tells them apart. */
    public final String[][] TRAFFIC_ITEM_BUILD = {
        {"TI_AC1_TO_AC2", "vport2", "vport3", "00:00:01:00:00:01", "1001", "00:00:02:00:00:01"},
        {"TI_AC2_TO_AC1", "vport3", "vport2", "00:00:02:00:00:01", "1002", "00:00:01:00:00:01"},
        {"TI_AC3_TO_AC1", "vport3", "vport2", "00:00:02:00:00:01", "1003", "00:00:01:00:00:01"},
    };
    /** IXIA vports backing the ACs, one entry per port. */
    public final String[] AC_VPORTS = {"vport2", "vport3"};
    /** The SUT intPool index each of those vports takes. */
    public final int[] AC_VPORT_POOL_INDEX = {1, 2};
    /** VLAN enabled on each vport's interface (the first
     *  circuit's; the per-item tag is what classifies). */
    public final String[] AC_VPORT_VLAN = {"1001", "1002"};
    public final String TRAFFIC_RATE_FPS = "1000";

    // ---- traffic item statistics, VPLS-suite idiom ----
    // Shape taken from cmp/tests/vpls/VplsParams.java: a ColDataTable
    // of TrafficItemStatisticsHeaders, one RowDataTable per expected
    // row, and a SuiteTableParams binding them. EvpnUtils.
    // verifyTrafficItemStatistics() reads this table, so an expected
    // rate is a params edit rather than a code change.
    private final String TRAFFIC_STATISTICS_TABLE = "trafficTable";
    private final ColDataTable headersTraffic = new ColDataTable(
            TrafficItemStatisticsHeaders.Traffic_Item.getValue(),
            TrafficItemStatisticsHeaders.Tx_Frame_Rate,
            TrafficItemStatisticsHeaders.Rx_Frame_Rate);
    /** TI_AC1_TO_AC2 transmitting and being received. Unicast: Rx depends on the MAC table at that moment, so it is asserted by the step that follows, not here. */
    public final RowDataTable TI_AC1_TO_AC2_RUNNING = RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "1000", "");
    /** TI_AC2_TO_AC1 transmitting and being received. Unicast: Rx depends on the MAC table at that moment, so it is asserted by the step that follows, not here. */
    public final RowDataTable TI_AC2_TO_AC1_RUNNING = RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "1000", "");
    /** TI_AC3_TO_AC1 transmitting and being received. Unicast: Rx depends on the MAC table at that moment, so it is asserted by the step that follows, not here. */
    public final RowDataTable TI_AC3_TO_AC1_RUNNING = RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "1000", "");
    /** TI_AC1_TO_AC2 suspended: nothing sent, nothing received. */
    public final RowDataTable TI_AC1_TO_AC2_SUSPENDED = RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "0", "0");
    /** TI_AC2_TO_AC1 suspended: nothing sent, nothing received. */
    public final RowDataTable TI_AC2_TO_AC1_SUSPENDED = RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "0", "0");
    /** TI_AC3_TO_AC1 suspended: nothing sent, nothing received. */
    public final RowDataTable TI_AC3_TO_AC1_SUSPENDED = RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "0", "0");

    // ---- per-step IXIA statistics expectations ----
    /** FLOW-030.S03 - Verify unknown unicast from AC1 is flooded to BOTH AC2 and AC3 (rx 2000 = 2 x tx; DUT transmits on both) */
    public final RowDataTable[] FLOW030_S03_UNKNOWN_UNICAST_FLOODED_ROWS = {RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "1000", "2000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "0", "0"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "0", "0")};
    /** FLOW-030.S07 - Verify AC1 -> AC2 is now KNOWN unicast: rx 1000, out of AC2 only, nothing to AC3 */
    public final RowDataTable[] FLOW030_S07_KNOWN_UNICAST_ROWS = {RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "1000", "1000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "1000", "1000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "0", "0")};
    /** FLOW-030.S17 - Verify AC1 -> AC2 now follows the MAC: rx 1000, out of AC3 only, nothing to AC2 */
    public final RowDataTable[] FLOW030_S17_FOLLOWS_MOVE_ROWS = {RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "1000", "1000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "0", "0"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "1000", "1000")};
    /** FLOW-031.S01R - Verify AC1 -> AC2 is known unicast while 00:00:02:00:00:01 is learnt: rx 1000, AC2 only */
    public final RowDataTable[] FLOW031_S01R_KNOWN_UNICAST_ROWS = {RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "1000", "1000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "1000", "1000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "0", "0")};
    /** FLOW-031.S03 - Verify AC1 -> AC2 is flooded again now 00:00:02:00:00:01 is unknown: rx 2000, out of AC2 AND AC3 */
    public final RowDataTable[] FLOW031_S03_FLOODED_AFTER_AGING_ROWS = {RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC1_TO_AC2", "1000", "2000"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC2_TO_AC1", "0", "0"), RowDataTable.add(TRAFFIC_STATISTICS_TABLE, "TI_AC3_TO_AC1", "0", "0")};
    public SuiteTableParams trafficTable =
            new SuiteTableParams(TRAFFIC_STATISTICS_TABLE, headersTraffic);

    /** Frames-per-second tolerance, as VplsParams uses. */
    public final int DEVIATION_FOR_VERIFY_TRAFFIC = 5;
    public final int WAIT_FOR_TRAFFIC_ITEM_STATISTICS_IN_MSEC = 30000;
    public final QueryCmdTime TRAFFIC_ITEM_STATISTICS_QCT =
            new QueryCmdTime(WAIT_FOR_TRAFFIC_ITEM_STATISTICS_IN_MSEC);

    /** Every item, for the start-suspended prep step. */
    public final String[] ALL_TRAFFIC_ITEMS = {"TI_AC1_TO_AC2", "TI_AC2_TO_AC1", "TI_AC3_TO_AC1"};
    /** Running-rate rows for every item, in the same order. */
    public final RowDataTable[] ALL_TRAFFIC_ITEMS_RUNNING = {TI_AC1_TO_AC2_RUNNING, TI_AC2_TO_AC1_RUNNING, TI_AC3_TO_AC1_RUNNING};

    // ---- timing ----
    public final long VERIFY_TIMEOUT_IN_MSEC = 90000L;
    /** How long to keep asking, for something that ages out.
     *
     *  DEVICE-MEASURED on pc-3099, 2026-09-09: after the last frame
     *  at 15:44:52 the entry was still present at 15:50:34 (342 s)
     *  and gone by 15:52:14 (442 s), against a 300 s MAC aging time.
     *  The device sweeps on a coarser timer than it ages on, so
     *  asking once 30 s after the nominal wait is a race the test
     *  loses. 240 s covers what was measured, with margin, and still
     *  fails if aging stops working altogether. */
    public final long AGING_VERIFY_TIMEOUT_IN_MSEC = 240000L;
    public final long VERIFY_INTERVAL_IN_MSEC = 5000L;
    /** The aging time TC03 configures and then waits out. Inside the
     *  CLI doc's range 0, 40-2400 (default 300). */
    public final int MAC_AGING_TIME_IN_SEC = 60;
    /** How long verifyAcEgress watches the DUT's per-circuit counters. */
    public final long EGRESS_WINDOW_IN_MSEC = 10000L;

    // ---- expected output ----
    /** FLOW-010.S00A - Verify evi-1 does not exist before this test creates it
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S00A_EVI_ABSENT_LINES = new String[] {"evi-1"};

    /** FLOW-010.S00B - Verify OSPF adjacency to the tester (29.31.31.31) is Full
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S00B_OSPF_FULL_LINES = new String[] {"29\\.31\\.31\\.31\\s+Full"};

    /** FLOW-010.S00C - Verify the LDP session to the tester (29.60.0.2) is Operational
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S00C_LDP_OPERATIONAL_LINES = new String[] {"29\\.60\\.0\\.2\\s+.*Operational"};

    /** FLOW-010.S00D - Verify the BGP session loopback to loopback (29.30.30.30 - 29.31.31.31) is up
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S00D_BGP_UP_LINES = new String[] {"29\\.31\\.31\\.31\\s+up\\s+3029"};

    /** FLOW-010.S09 - Verify the EVPN MAC address-table has no learnt MAC yet
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S09_MAC_TABLE_EMPTY_LINES = new String[] {"([0-9a-f]{2}:){5}[0-9a-f]{2}\\s+L\\s"};

    /** FLOW-010.S10 - Verify the DUT originates the Type-3 IMET route for evi-1 (advertised to the tester 29.31.31.31)
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S10_TYPE3_ADVERTISED_LINES = new String[] {"Type=3:.*Originating Router's IP=29\\.30\\.30\\.30"};

    /** FLOW-010.S11 - Verify the BGP session to the tester negotiated L2VPN EVPN (advertised and received)
     *  Known at generation time, not captured. */
    public final String[] FLOW010_S11_EVPN_CAPABILITY_LINES = new String[] {"L2VPN EVPN:\\s+advertised and received"};

    /** FLOW-030.S00B - Verify OSPF adjacency to the tester (29.31.31.31) is Full
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S00B_OSPF_FULL_LINES = new String[] {"29\\.31\\.31\\.31\\s+Full"};

    /** FLOW-030.S00C - Verify the LDP session to the tester (29.60.0.2) is Operational
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S00C_LDP_OPERATIONAL_LINES = new String[] {"29\\.60\\.0\\.2\\s+.*Operational"};

    /** FLOW-030.S00D - Verify the BGP session loopback to loopback (29.30.30.30 - 29.31.31.31) is up
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S00D_BGP_UP_LINES = new String[] {"29\\.31\\.31\\.31\\s+up\\s+3029"};

    /** FLOW-030.S04 - Verify 00:00:01:00:00:01 is learnt on AC1 (VLAN 1001)
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S04_AC1_MACS_LEARNT_LINES = new String[] {"00:00:01:00:00:01\\s+L\\s"};

    /** FLOW-030.S05 - Verify the DUT originates a Type-2 route for 00:00:01:00:00:01 (advertised to the tester 29.31.31.31)
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S05_AC1_TYPE2_ADVERTISED_LINES = new String[] {"Type=2:.*MAC=00:00:01:00:00:01"};

    /** FLOW-030.S09 - Verify 00:00:02:00:00:01 is learnt on AC2 (VLAN 1002)
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S09_AC2_MACS_LEARNT_LINES = new String[] {"00:00:02:00:00:01\\s+L\\s"};

    /** FLOW-030.S10 - Verify the DUT originates a Type-2 route for 00:00:02:00:00:01 (advertised to the tester 29.31.31.31)
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S10_AC2_TYPE2_ADVERTISED_LINES = new String[] {"Type=2:.*MAC=00:00:02:00:00:01"};

    /** FLOW-030.S15 - Verify 00:00:02:00:00:01 has moved to AC3 (VLAN 1003)
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S15_MACS_MOVED_TO_AC3_LINES = new String[] {"00:00:02:00:00:01\\s+L\\s"};

    /** FLOW-030.S16B - Verify the Type-2 for 00:00:02:00:00:01 still carries MAC Mobility SeqNum=0 after the local move (advertised to the tester 29.31.31.31)
     *  Known at generation time, not captured. */
    public final String[] FLOW030_S16B_SEQNUM_UNCHANGED_LINES = new String[] {"MAC=00:00:02:00:00:01(?:(?!Type=)[\\s\\S])*?SeqNum=0\\b"};

    /** FLOW-031.S00B - Verify OSPF adjacency to the tester (29.31.31.31) is Full
     *  Known at generation time, not captured. */
    public final String[] FLOW031_S00B_OSPF_FULL_LINES = new String[] {"29\\.31\\.31\\.31\\s+Full"};

    /** FLOW-031.S00C - Verify the LDP session to the tester (29.60.0.2) is Operational
     *  Known at generation time, not captured. */
    public final String[] FLOW031_S00C_LDP_OPERATIONAL_LINES = new String[] {"29\\.60\\.0\\.2\\s+.*Operational"};

    /** FLOW-031.S00D - Verify the BGP session loopback to loopback (29.30.30.30 - 29.31.31.31) is up
     *  Known at generation time, not captured. */
    public final String[] FLOW031_S00D_BGP_UP_LINES = new String[] {"29\\.31\\.31\\.31\\s+up\\s+3029"};

    /** FLOW-031.S01Q - Verify 00:00:02:00:00:01 is learnt on AC2 before the aging test begins
     *  Known at generation time, not captured. */
    public final String[] FLOW031_S01Q_MACS_LEARNT_LINES = new String[] {"00:00:02:00:00:01\\s+L\\s"};

    /** FLOW-031.S04 - Verify 00:00:02:00:00:01 has aged out of the EVPN MAC table
     *  Known at generation time, not captured. */
    public final String[] FLOW031_S04_MACS_AGED_OUT_LINES = new String[] {"00:00:02:00:00:01"};

    /** FLOW-031.S05 - Verify the Type-2 route for 00:00:02:00:00:01 is withdrawn (advertised to the tester 29.31.31.31)
     *  Known at generation time, not captured. */
    public final String[] FLOW031_S05_TYPE2_WITHDRAWN_LINES = new String[] {"Type=2:.*MAC=00:00:02:00:00:01"};

    @Override
    public SuiteTableParams[] getSuiteParamsTableToUpdate() {
        return new SuiteTableParams[] {};
    }

    @Override
    public SuiteTableParams[] getSuitesTablesToPrint() {
        return new SuiteTableParams[] {};
    }
}
