package cmp.tests.evpn;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Pattern;

import cmp.infra.CmpRouter;
import cmp.infra.Session.ICmpCliCmd;
import cmp.infra.Session.SessionMode;
import cmp.infra.Session.SessionType;
import cmp.infra.common.General;
import cmp.infra.common.GlobalParam;
import cmp.infra.ixia.Ixia;
import cmp.infra.ixia.IxiaFunctions;
import cmp.infra.ixia.IxiaTypes;
import cmp.infra.ixia.tableHeader.TrafficItemStatisticsHeaders;
import cmp.infra.reporter.CompassReporter;
import cmp.infra.reporter.loggerImp;
import cmp.tests.common.query.QueryFieldItem;
import cmp.tests.common.query.QueryFieldList;
import cmp.tests.common.query.QueryUtils;
import common.params.RowDataTable;
import java.util.ArrayList;

/**
 * Verification helpers for the generated EVPN suite.
 *
 * Mirrors the shape of cmp.tests.vpls.VplsUtils: the test class stays a
 * readable sequence of numbered steps and every assertion lives here.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class EvpnUtils implements loggerImp {

    /** intPool in the SUT file that backs the attachment circuits. */
    private static final String AC_POOL = "data1";

    /** Attachment-circuit names, in lab-profile order. */
    private static final String[] AC_NAMES = {"AC1", "AC2", "AC3"};

    /**
     * The SUT intPool index each attachment circuit lives on.
     *
     * Not the position in the list. On a rig that spends a link on the EVPN
     * core the ACs start at index 1, and two circuits sharing a port repeat
     * the same index - that repetition is the point of the 2026-09-08
     * topology and is why this is a table rather than an offset.
     */
    private static final int[] AC_POOL_INDEX = {1, 2, 2};

    /**
     * The VLAN each attachment circuit carries.
     *
     * These come from the lab profile and are written literally into
     * EVPN_Base.cfg from the same values, so the DUT sub-interface and the
     * IXIA frame tag cannot disagree.
     *
     * They are deliberately NOT read from the SUT's `general/vlans` list any
     * more. Exaware, 2026-09-08 (Eyal Ozeri): "Vlan 3380 appears in the SUT
     * file because it is used on one of the interfaces to an external server
     * connection. The tool should be able to use entire 2-4094 range."
     * Reading that slot meant the suite ran on whatever VLAN the SUT happened
     * to declare first, and that VLAN belonged to something else.
     *
     * What replaces the old check is the opposite one, in
     * {@link #assertAcVlansAreFree()}: these VLANs must NOT collide with any
     * the SUT declares.
     */
    private static final String[] AC_VLAN = {"1001", "1002", "1003"};

    /**
     * The emulated protocols this rig's core link runs, from the lab profile.
     *
     * Named here so the running-state check knows what "all of them" means.
     * Asserting only that SOMETHING started would pass on a rig where BGP is
     * down and OSPF is up, which is the case that matters for EVPN.
     */
    private static final String[] TESTER_PROTOCOLS = {"ospf", "ldp", "bgp"};

    /**
     * The IXIA configuration bringUpParams.crt loads, or null if there is
     * none and the items must be built over TCL instead.
     */
    private static final String IXNCFG = "EVPN_3AC_CORE.ixncfg";

    /** Lowest and highest VLAN an attachment circuit may carry. */
    private static final int VLAN_MIN = 2;
    private static final int VLAN_MAX = 4094;

    /**
     * The attachment circuit as THIS testbed defines it, e.g.
     * "x-eth 0/0/8.1001" - the SUT's intPool entry plus its VLAN.
     *
     * A vlan-based EVI will not accept the bare port; see EVPN_Base.cfg.
     */
    public String acInterface(int ac) throws Exception {
        return cmp.getIntPool(AC_POOL).getInter(AC_POOL_INDEX[ac]).getIntName()
               + "." + AC_VLAN[ac];
    }

    /**
     * The same circuit in the form the device PRINTS it: no space.
     *
     * DEVICE QUIRK, verified on pc-3080 8.7.0 LAB 22. Configuration accepts
     * the spaced form:
     *     l2-services evpn evi-1 interface x-eth 0/0/8.1001      OK
     * but the show command's `source` filter does not:
     *     ... mac-address-table name evi-1 source x-eth 0/0/8.1001
     *         syntax error: unknown argument
     *     ... mac-address-table name evi-1 source x-eth0/0/8.1001   OK
     *
     * Same interface, same device, two spellings - which is why the capture
     * half and the assertion half of this step disagreed for a whole run.
     */
    public String acInterfaceCompact(int ac) throws Exception {
        return acInterface(ac).replace(" ", "");
    }

    /** The VLAN attachment circuit `ac` carries. */
    public String acVlan(int ac) {
        return AC_VLAN[ac];
    }

    /**
     * The lines `show evpn detail` must contain once the EVI is bound: the
     * EVI's own name, plus every attachment circuit AS THIS TESTBED NAMES IT.
     *
     * Resolved here rather than written into EvpnParams because the lab
     * profile's interface names are placeholders the SUT rebinds at bring-up.
     * The profile says agg-eth-2.1001; pc-3099 answers x-eth0/0/32.1001 and
     * pc-3080 answers x-eth0/0/18.1001. An expectation built from the
     * placeholder cannot pass on any real rig - on 2026-09-09 it failed on
     * pc-3099 with "Missing lines: [agg-eth-2.1001, agg-eth-3.1002,
     * agg-eth-3.1003]" while the device had all three bound correctly.
     *
     * Still falsifiable: it names the EVI and every circuit, so a service
     * that came up with a circuit missing fails here.
     */
    public String[] eviBoundLines(String evi) throws Exception {
        String[] lines = new String[AC_VLAN.length + 1];
        lines[0] = evi;
        for (int i = 0; i < AC_VLAN.length; i++) {
            lines[i + 1] = acInterfaceCompact(i);
        }
        return lines;
    }

    /**
     * Refuse to run on VLANs that are in use for something else.
     *
     * This is the run-time half of Exaware's 2026-09-08 point about VLAN
     * 3380. The SUT file lists the VLANs this testbed has committed to other
     * purposes - 3380 there is an external server connection - and a test
     * that quietly borrows one damages a link nobody was watching. Any
     * collision fails the run before a single command is typed.
     *
     * The range check is here for the same reason: 0, 1 and 4095 are not
     * usable service VLANs, and finding that out at the commit costs a
     * bring-up.
     */
    public void assertAcVlansAreFree() throws Exception {
        java.util.List<String> reserved = new java.util.ArrayList<String>();
        try {
            for (int i = 0; i < General.getInstanceByName().vlans.length; i++) {
                reserved.add(General.getInstanceByName().vlans[i].getNumber());
            }
        } catch (Exception e) {
            logMsg.info("SUT declares no general/vlans list: " + e.getMessage());
        }
        for (int i = 0; i < AC_VLAN.length; i++) {
            int v = Integer.parseInt(AC_VLAN[i]);
            boolean inRange = v >= VLAN_MIN && v <= VLAN_MAX;
            CompassReporter.passFailByCondition(inRange,
                    AC_NAMES[i] + ": VLAN " + v + " is a usable service VLAN.",
                    AC_NAMES[i] + ": VLAN " + v + " is outside " + VLAN_MIN
                            + "-" + VLAN_MAX + " and the device will refuse it.");
            if (!inRange) {
                throw new Exception("AC VLAN out of range: " + v);
            }
            boolean free = !reserved.contains(AC_VLAN[i]);
            CompassReporter.passFailByCondition(free,
                    AC_NAMES[i] + ": VLAN " + v + " is not claimed by the SUT.",
                    AC_NAMES[i] + ": VLAN " + v + " is declared in this SUT's "
                            + "general/vlans list, so it belongs to another "
                            + "link on this testbed. Regenerate with "
                            + "`ate codegen --ac-vlans` on VLANs the lab has "
                            + "free.");
            if (!free) {
                throw new Exception("AC VLAN " + v + " is reserved by the SUT");
            }
        }
    }

    /**
     * Run a configuration command and REQUIRE the device to accept it.
     *
     * `CmpRouter.configAndValidate` commits and warns when the commit had
     * nothing to do. That is the right default for their suites, but it means
     * a command the CLI rejected outright leaves the test green: nothing was
     * staged, so there is nothing to commit, so there is only a warning. Here
     * a rejected command is a failed step.
     */
    public void configAndVerifyAccepted(ICmpCliCmd command) throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);
        if (wasRejected(output)) {
            CompassReporter.fail("Device REJECTED '" + command.toString()
                    + "': " + String.valueOf(output).trim());
            throw new Exception("device rejected the command: " + command.toString());
        }
        cmp.commitAndVerification(command.getCmdSessionType(),
                GlobalParam.LOAD_CONF_FILE_TIMEOUT_DEFAULT_MSEC);
    }

    /** Did the CLI refuse the command it was given? */
    private boolean wasRejected(String output) {
        if (output == null) {
            return false;
        }
        // Their own pattern first, then the plain reading of the same thing,
        // so a change in the framework's regexp cannot quietly turn this
        // assertion off.
        if (Pattern.compile(GlobalParam.CLI_COMMAND_SYNTAX_ERROR_REGEXP)
                   .matcher(output).find()) {
            return true;
        }
        String low = output.toLowerCase();
        return low.contains("syntax error")
               || low.contains("% invalid input")
               || low.contains("is not a valid value");
    }


    private final EvpnParams params;
    private final CmpRouter cmp;
    private final Ixia ixia;

    public EvpnUtils(EvpnParams params, CmpRouter cmp, Ixia ixia) {
        this.params = params;
        this.cmp = cmp;
        this.ixia = ixia;
    }

    /**
     * Run a show command and assert every expected line (a regex) appears in
     * the output, polling until the verify timeout. Modelled on
     * ShowVplsDetail.verifyShowVplsDetail.
     *
     * An EMPTY expectation array means "not yet validated against a real
     * device": the command is still run and its output reported, but the
     * result is a warning, never a pass.
     */
    /**
     * Assert the given lines are GONE from the command's output.
     *
     * The mirror of verifyShowLines, for steps whose whole point is that
     * something stopped being there: MACs after the aging time, a Type-2
     * after withdrawal. Those cannot be expressed by a capture - `ate
     * capture` records state while it EXISTS and refuses empty output, so the
     * captured lines are exactly the rows that ought to disappear. Asserting
     * their presence asserts that aging never happened, which is how TC03
     * failed while the device was behaving correctly.
     *
     * Falsifiable in the right direction: it fails if the rows are still
     * there, and it refuses to pass on an empty expectation, because
     * "nothing was supposed to vanish" proves nothing.
     */
    public void verifyShowLinesAbsent(ICmpCliCmd command, String[] goneLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);
        if (goneLines == null || goneLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - nothing asserted absent.");
            logMsg.info(output);
            return;
        }
        java.util.List<String> stillThere = new java.util.ArrayList<String>();
        for (String pattern : goneLines) {
            java.util.regex.Pattern p = java.util.regex.Pattern.compile(pattern);
            if (p.matcher(output).find()) {
                stillThere.add(pattern);
            }
        }
        falsifiableAssertions++;
        CompassReporter.passFailByCondition(stillThere.isEmpty(),
                "The output of " + command.toString()
                        + " no longer contains the expected-gone lines.",
                "The output of " + command.toString()
                        + " STILL contains lines that should have gone: "
                        + stillThere);
    }

    public void verifyShowLines(ICmpCliCmd command, String[] expectedLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);

        if (expectedLines == null || expectedLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - output captured for "
                    + "review, nothing asserted.");
            logMsg.info(output);
            return;
        }

        Set<String> missing = new LinkedHashSet<String>();
        boolean asExpected = false;
        long endTime = System.currentTimeMillis() + params.VERIFY_TIMEOUT_IN_MSEC;

        while (!asExpected && System.currentTimeMillis() < endTime) {
            missing.clear();
            asExpected = true;
            for (int i = 0; i < expectedLines.length; i++) {
                String expected = expectedLines[i];
                if (output == null
                        || !Pattern.compile(expected).matcher(output).find()) {
                    missing.add(expected);
                    asExpected = false;
                }
            }
            if (!asExpected) {
                Thread.sleep(params.VERIFY_INTERVAL_IN_MSEC);
                output = cmp.runCommandAndSwitch(command.toString(), command);
            }
        }

        falsifiableAssertions++;
        CompassReporter.passFailByCondition(asExpected,
                "The output of " + command.toString() + " is as expected.",
                "The output of " + command.toString()
                        + " is not as expected. Missing lines: " + missing);
    }

    /**
     * Build the suite's traffic items on the chassis.
     *
     * Exaware's own suites load a prebuilt binary .ixncfg at bring-up and only
     * suspend/unsuspend what it contains. That binary cannot be generated from
     * documents, so this suite stands up its own traffic over TCL instead -
     * the same chassis objects, no file to be handed.
     *
     * Idempotency is the chassis's business: call this once, before the first
     * setTrafficItemState. Every argument comes from EvpnParams, so a different
     * rig is a params change, not a code change.
     *
     * Argument order is VERIFIED against the proc signatures in
     * cmp-infra-project/src/main/java/cmp/infra/tcl/ixia_lib.tcl (2026-08-12),
     * not merely against the $arg help strings.
     *
     * LIMIT - the SOURCE MAC cannot be set from this library. ixia_lib.tcl
     * offers editTrafficRawDestMacAddr and no source equivalent, and
     * configTrafficItemStream takes only destinationMacMode. EVPN learns from
     * SOURCE MACs, so the FLOW-030 precondition that AC2 and AC3 emit the same
     * source MAC - which is what makes AC2 -> AC3 a local move rather than two
     * distinct hosts - cannot be expressed here. Those items still need either
     * a prebuilt .ixncfg or a new src-MAC proc in ixia_lib.tcl, which is
     * Exaware's file to extend. The per-item source MAC is carried in
     * EvpnParams so it is ready the moment either arrives.
     */
    /**
     * The items the loaded .ixncfg is expected to carry, by name.
     *
     * Verified rather than assumed: `loadIxiaFile` reports success for a file
     * that loaded nothing useful, and an absent traffic item shows up much
     * later as an empty statistics view rather than as an error.
     */
    private void verifyTrafficItemsLoaded() throws Exception {{
        String names = ixia.runCommand(new RawTcl(
                "set ateNames {}; "
                + "foreach it [ixNet getL [ixNet getRoot]/traffic trafficItem] "
                + "{ lappend ateNames [ixNet getAtt $it -name] }; "
                + "join $ateNames { }"));
        logMsg.info("traffic items in the loaded " + IXNCFG + ": " + names);
        StringBuilder missing = new StringBuilder();
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {{
            if (names == null || !names.contains(ti[0])) {{
                missing.append(ti[0]).append(' ');
            }}
        }}
        CompassReporter.passFailByCondition(missing.length() == 0,
                "the loaded " + IXNCFG + " carries every traffic item this "
                + "test drives: " + names,
                "the loaded " + IXNCFG + " is MISSING traffic item(s) ["
                + missing.toString().trim() + "] - read back: '" + names
                + "'. Every traffic assertion below would read an empty "
                + "statistics view.");
    }}

    /**
     * Start the tester's emulated protocols, then PROVE they are running.
     *
     * DEVICE-VERIFIED 2026-09-09 on chassis 10.1.70.108 (IxNetwork 9.00).
     * Loading the .ixncfg restores OSPF, LDP and BGP on the core vport, but
     * every one of them comes back with runningState=stopped. The DUT then
     * speaks into a port that answers nothing and its BGP neighbour sits in
     * Active for the whole run, which is exactly how the underlay looked
     * "configured" and was not established.
     *
     * The read-back is the point. `performFunctions` reports "ended without
     * errors" for a TCL call that never ran, so starting and believing the
     * return value is how 34 calls once did nothing in silence.
     */
    public void startTesterProtocolsAndVerify() throws Exception {{
        ixia.performFunctions(IxiaFunctions.START_ALL_PROTOCOLS);
        // Protocols need time to come up before anything is asserted about
        // them; adjacency formation is seconds, not milliseconds.
        Thread.sleep(45000);
        ixia.performFunctions(IxiaFunctions.LOAD_IXIA_OBJECT);

        // Read the running state back off the chassis. ixia_lib has no proc
        // that returns it, and inventing an IxiaFunctions entry would be an
        // ungrounded template, so this is a raw ixNet query - the same escape
        // hatch the VLAN and source-MAC helpers use.
        String running = ixia.runCommand(new RawTcl(
                "set ateStates {}; "
                + "foreach vp [ixNet getL [ixNet getRoot] vport] { "
                + "  foreach p {ospf ldp bgp} { "
                + "    if {![catch {set en [ixNet getAtt $vp/protocols/$p -enabled]}]} { "
                + "      if {$en} { lappend ateStates "
                + "$p=[ixNet getAtt $vp/protocols/$p -runningState] } } } }; "
                + "join $ateStates { }"));
        logMsg.info("tester protocol running states: " + running);
        // Every protocol the profile declares must be RUNNING, and the check
        // must not pass on empty output. The first version asked only
        // `contains("started")`, which reported
        //     Pass: tester protocols are running:
        // with nothing after the colon - a pass on a string that said
        // nothing. That is the fake-pass rule, arriving through an assertion
        // written to confirm the fake-pass rule.
        boolean allStarted = running != null;
        StringBuilder missing = new StringBuilder();
        for (String proto : TESTER_PROTOCOLS) {{
            if (running == null || !running.contains(proto + "=started")) {{
                allStarted = false;
                missing.append(proto).append(' ');
            }}
        }}
        CompassReporter.passFailByCondition(allStarted,
                "tester protocols are running: " + running,
                "tester protocol(s) NOT started [" + missing.toString().trim()
                + "] - read back: '" + running + "'. The DUT will speak "
                + "OSPF/LDP/BGP into a port that answers nothing and every "
                + "control-plane assertion below is meaningless");
        // Deliberately NOT counted as a falsifiable assertion. It can fail,
        // but it checks the RIG, not the feature: a test whose only "proof"
        // was that the tester's protocols came up has verified nothing about
        // EVPN. See assertSomethingWasVerified().
    }}

    public void createTrafficItems() throws Exception {
        // Before anything: the VLANs this suite is about to put on the wire
        // must be ours to use. See assertAcVlansAreFree().
        assertAcVlansAreFree();

        // With an .ixncfg loaded at bring-up the items already exist, and
        // rebuilding them is wrong: it is their VPLS idiom that a suite loads
        // a saved configuration and then only suspends and unsuspends NAMED
        // items. Rebuilding on top leaves the new items unapplied, which is
        // how a run reached the statistics view and got
        //     No results where: TRAFFIC_ITEM: TI_AC1_TO_AC2
        // with every attachment circuit still counting zero frames.
        if (IXNCFG != null) {{
            verifyTrafficItemsLoaded();
            // Their VPLS prep, and the piece that was missing: unsuspending
            // an item does NOT start the traffic engine. Without this the
            // items sit at state=stopped, every attachment circuit counts
            // zero frames, and the statistics view answers
            //     No results where: TRAFFIC_ITEM: TI_AC1_TO_AC2
            // Start the whole set once, then hold it silent; each step
            // unsuspends only what it needs.
            enableTrafficItemsAndStartSuspended(params.ALL_TRAFFIC_ITEMS);
            return;
        }}

        // No .ixncfg: build the items over TCL instead. The vports have to
        // exist before they can be tagged or used as endpoints, and whatever
        // vports are left in the chassis session from an earlier run are not
        // ours.
        assignAcVports();
        tagVportsWithAcVlan();
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            String name = ti[0], srcVport = ti[1], dstVport = ti[2], srcMac = ti[3];
            String vlan = ti[4];
            logMsg.info("Creating IXIA traffic item " + name
                    + " (" + srcVport + " VLAN " + vlan + " -> " + dstVport + ")");
            // Source MAC is set below, after the item exists.
            // "null" - not "" - is how their TCL spells an unset argument:
            // every proc in ixia_lib.tcl guards with
            // `if {[string match $arg null] != 1}`. An empty Java string
            // collapses during TCL word-splitting and the proc is called with
            // too few arguments, which answers `wrong # args` while
            // performFunctions still reports "ended without errors".
            ixia.performFunctions(IxiaFunctions.CONFIGURE_NEW_TRAFFIC_ITEM.args(
                    name, "true", "null", "l2L3", "false", "false", "raw",
                    name, "interleaved", "null", "false", "false", "oneToOne"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_ENDPOINTS.args(
                    name, "1", srcVport, "null", "null", "null", "null", "null",
                    "null", dstVport, "null", "null", "null", "null", "null",
                    "null", "null", "null", "null", name, "null", "null"));
            bindRawEndpoints(name, srcVport, dstVport);
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_STREAM.args(
                    name, "1", "goodCRC", "manual", name, "8", "auto", "false"));
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_FRAME_RATE.args(
                    name, "stream", "1", "framesPerSecond",
                    params.TRAFFIC_RATE_FPS, "bytes", "bitsPerSec", "false"));
        }
        // A raw item's frame is whatever its protocol stack says, and that
        // stack is ethernet + fcs: UNTAGGED. Tagging the vport's interface
        // does not change it - that governs protocol emulation, not raw frame
        // content. Untagged frames never match a `vlan-id` sub-interface, so
        // the DUT counted 219k frames on the port and 0 on the circuit, and
        // the EVI learnt nothing while every call reported success.
        tagTrafficItemsWithAcVlan();

        // GENERATE binds the physical MACs and interfaces onto each raw item -
        // their own enum says so ("generate traffic item to apply physical mac
        // and interfaces to traffic source and destanation"). Without it the
        // items are configured but unresolved, and nothing is transmitted. It
        // runs BEFORE the source MAC is set; generating afterwards would
        // overwrite it.
        ixia.performFunctions(IxiaFunctions.GENERATE_TRAFFIC);

        // EVPN learns from SOURCE MACs, and ixia_lib.tcl exposes only
        // editTrafficRawDestMacAddr. It does not need a new proc: that one is a
        // single ixNet setAtt on the ethernet-1 stack, and the source field
        // sits beside the destination field on the same path. So the same
        // assignment is issued here as raw TCL, into the session where
        // ixia_lib.tcl is already sourced - their file is not modified.
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            setTrafficItemSourceMac(ti[0], ti[3]);
        }
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic items built on the chassis");
    }

    /**
     * Point a raw traffic item's endpoints at the vports, and verify it.
     *
     * `configTrafficItemEndpoints` only emits the `/vport:{id}/protocols` form
     * that a RAW item requires when it decides the source vport's interface
     * has a VLAN - and it decides that with
     * `ixNet getAtt [ixNet getL $vport interface]/vlan -vlanEnable`, which is
     * only a valid path when the vport has EXACTLY ONE interface. A vport
     * carrying more than one makes that read fail, the heuristic falls through
     * to the interface-list form, and the chassis answers
     * "ERROR-6301-The endpoint is not correct for this type of trafficItem" -
     * which performFunctions reports as a warning and the run survives.
     *
     * Rather than depend on that heuristic, set the endpoints explicitly and
     * read them back.
     */
    public void bindRawEndpoints(String trafficItemName, String srcVport,
                                 String dstVport) throws Exception {
        String readBack = ixia.runCommand(new RawTcl(
                "set ti [getTraffic \"" + trafficItemName + "\"] ; "
                + "set es [lindex [ixNet getL $ti endpointSet] 0] ; "
                + "ixNet setMultiAttr $es "
                +   "-sources [list $ixia(" + srcVport + ")/protocols] "
                +   "-destinations [list $ixia(" + dstVport + ")/protocols] ; "
                + "ixNet commit ; "
                + "puts \"\" ; "
                + "puts \"ENDPOINTS=[ixNet getAtt $es -sources]"
                +   "|[ixNet getAtt $es -destinations]\" ; "
                + "puts \"\""));

        boolean bound = readBack != null && readBack.contains("/protocols")
                && !readBack.contains("ERROR");
        CompassReporter.passFailByCondition(bound,
                trafficItemName + ": endpoints bound to " + srcVport + " -> "
                        + dstVport + ".",
                trafficItemName + ": endpoints NOT bound (" + oneLine(readBack)
                        + ") - the item will transmit nothing.");
        if (!bound) {
            throw new Exception("could not bind endpoints for " + trafficItemName);
        }
    }

    /**
     * Set a traffic item's source MAC, and CHECK the chassis took it.
     *
     * Mirrors ixia_lib.tcl's editTrafficRawDestMacAddr, with
     * ethernet.header.sourceAddress-1 in place of destinationAddress-1, and
     * reuses that file's own getTraffic helper. The value is read back rather
     * than assumed: an unapplied source MAC would leave the MAC-move flows
     * asserting something that never happened.
     */
    /**
     * Push a VLAN header onto every raw traffic item, carrying the AC VLAN.
     *
     * DEVICE-VERIFIED on pc-3080: with the header appended the circuit
     * counters move off zero and the EVI learns; without it they stay at zero
     * while the port counts hundreds of thousands of frames.
     *
     * Reads the stacks back afterwards rather than trusting the append.
     */
    public void tagTrafficItemsWithAcVlan() throws Exception {
        int tagged = 0;
        for (String[] ti : params.TRAFFIC_ITEM_BUILD) {
            tagged += tagTrafficItemVlan(ti[0], ti[4]) ? 1 : 0;
        }
        boolean all = tagged == params.TRAFFIC_ITEM_BUILD.length;
        CompassReporter.passFailByCondition(all,
                "All " + tagged + " traffic items carry their AC VLAN.",
                "Only " + tagged + " of " + params.TRAFFIC_ITEM_BUILD.length
                        + " traffic items were VLAN-tagged - untagged frames "
                        + "never reach a vlan-id sub-interface, so the EVI "
                        + "will learn nothing.");
        if (!all) {
            throw new Exception("could not VLAN-tag the traffic items");
        }
    }

    /**
     * Push a VLAN header onto ONE raw traffic item and set its VLAN ID.
     *
     * Per item, not per suite. Two attachment circuits may share a vport and
     * be told apart by nothing but this tag (Exaware, 2026-09-08: "An AC can
     * reside as a tagged interface"), so tagging every item with one VLAN
     * would put both circuits' traffic on the same sub-interface and the
     * MAC-move assertion would be meaningless.
     *
     * The same TCL, in readable form and with the same proc names, is in
     * configurations/ixia/EVPN_traffic.tcl, so the file a reviewer opens and
     * the suite that runs build identical items.
     */
    private boolean tagTrafficItemVlan(String itemName, String vlan)
            throws Exception {
        String tcl =
            "set tpl {} ; "
            + "foreach t [ixNet getL [ixNet getRoot]/traffic protocolTemplate] { "
            +   "if {[string equal -nocase [ixNet getAtt $t -displayName] {VLAN}]} { "
            +     "set tpl $t } } ; "
            + "set ti [getTraffic \"" + itemName + "\"] ; "
            + "set tagged 0 ; "
            + "foreach ce [ixNet getL $ti configElement] { "
            +   "set has 0 ; "
            +   "foreach st [ixNet getL $ce stack] { "
            +     "if {[string match {*vlan*} $st]} { set has 1 } } ; "
            +   "if {$has == 0 && $tpl ne {}} { "
            +     "ixNet exec appendProtocol [lindex [ixNet getL $ce stack] 0] $tpl ; "
            +     "ixNet commit } ; "
            +   "foreach st [ixNet getL $ce stack] { "
            +     "if {![string match {*vlan*} $st]} { continue } ; "
            +     "incr tagged ; "
            +     "foreach fld [ixNet getL $st field] { "
            +       "if {[string match -nocase {*vlan-id*} "
            +         "[ixNet getAtt $fld -displayName]]} { "
            +         "ixNet setMultiAttr $fld -singleValue " + vlan
            +           " -fieldValue " + vlan + " -valueType singleValue } } } ; "
            +   "ixNet commit } ; "
            + "puts \"\" ; "
            + "puts \"VLANTAGGED=$tagged VLANID=" + vlan + "\" ; "
            + "puts \"\"";
        String readBack = ixia.runCommand(new RawTcl(tcl));
        boolean ok = readBack != null && readBack.contains("VLANTAGGED=")
                && !readBack.contains("VLANTAGGED=0")
                && readBack.contains("VLANID=" + vlan);
        logMsg.info(itemName + ": VLAN " + vlan + " -> " + oneLine(readBack));
        return ok;
    }

    public void setTrafficItemSourceMac(String trafficItemName, String mac)
            throws Exception {
        // Find the field by NAME, do not guess its index. ixia_lib.tcl writes
        // the destination MAC to `ethernet.header.destinationAddress-1`, and
        // the obvious mirror `...sourceAddress-1` does not exist - the chassis
        // answers "ERROR-7009-Could not find the requested item" with a
        // NullReferenceException in StackFieldHandler.InsertMissingField,
        // because field suffixes are positions within the stack, not names.
        // So walk the ethernet stack's fields and match on the display name.
        String tcl =
            "set ti [getTraffic \"" + trafficItemName + "\"] ; "
            + "set names {} ; set done 0 ; "
            + "foreach ce [ixNet getL $ti configElement] { "
            +   "foreach st [ixNet getL $ce stack] { "
            +     "if {![string match *ethernet* $st]} { continue } ; "
            +     "foreach fld [ixNet getL $st field] { "
            +       "set nm [ixNet getAtt $fld -displayName] ; "
            +       "lappend names $nm ; "
            +       "if {[string match -nocase {*source*} $nm]} { "
            +         "ixNet setMultiAttr $fld -singleValue " + mac
            +           " -fieldValue " + mac + " -valueType singleValue ; "
            +         "incr done } } } } ; "
            + "ixNet commit ; "
            + "set got {} ; "
            + "foreach ce [ixNet getL $ti configElement] { "
            +   "foreach st [ixNet getL $ce stack] { "
            +     "if {![string match *ethernet* $st]} { continue } ; "
            +     "foreach fld [ixNet getL $st field] { "
            +       "if {[string match -nocase {*source*} "
            +         "[ixNet getAtt $fld -displayName]]} { "
            +         "append got [ixNet getAtt $fld -singleValue] } } } } ; "
            + "puts \"\" ; "
            + "puts \"SRCMAC=$got SET=$done FIELDS=$names\" ; "
            + "puts \"\"";
        String readBack = ixia.runCommand(new RawTcl(tcl));

        boolean applied = readBack != null
                && readBack.toLowerCase().contains("srcmac=" + mac.toLowerCase());
        CompassReporter.passFailByCondition(applied,
                trafficItemName + ": source MAC " + mac + " applied on the chassis.",
                trafficItemName + ": source MAC " + mac + " was NOT applied - the"
                        + " chassis reports " + oneLine(readBack)
                        + ". Any assertion that depends on this source MAC is"
                        + " unmet.");
    }

    /**
     * A raw TCL command for the IXIA session.
     *
     * Deliberately NOT an EvpnCommands constant: that enum is validated
     * against the EVPN CLI documentation at generation time, and TCL sent to
     * IxNetwork has no place in it.
     */
    private static final class RawTcl implements ICmpCliCmd {
        private final String tcl;

        RawTcl(String tcl) {
            this.tcl = tcl;
        }

        @Override
        public ICmpCliCmd args(Object... args) {
            return this;
        }

        @Override
        public String toString() {
            return this.tcl;
        }

        @Override
        public String stripArgs() {
            return this.tcl;
        }

        @Override
        public SessionMode getCmdSessionMode() {
            return SessionMode.CLI;
        }

        @Override
        public SessionType getCmdSessionType() {
            return SessionType.MGMT;
        }
    }

    /**
     * Enable the AC VLAN on every IXIA vport, and verify the chassis took it.
     *
     * Two things depend on this and both fail silently without it:
     *
     *  * frames must carry the AC VLAN or they never reach the sub-interface
     *    the EVI is bound to;
     *  * a RAW traffic item only accepts endpoints of the form
     *    `/vport:{id}/protocols`, and `configTrafficItemEndpoints` only builds
     *    that form when the vport's interface has a VLAN enabled. Without it
     *    the chassis answers "ERROR-6301-The endpoint is not correct for this
     *    type of trafficItem" - and performFunctions still reports the call as
     *    "ended without errors".
     *
     * The .crt carries `vlan` rows for the same purpose, but they are applied
     * by `Ixia.loadConfigurationFile`, which only runs for a device that has a
     * configuration file row - and this suite deliberately references no
     * .ixncfg. So the tagging is done here, where it is also verified.
     */
    public void assignAcVports() throws Exception {
        // `loadIxiaObj` names $ixia(vport1..N) from the vports ALREADY present
        // in the IxNetwork configuration (`ixNet getL [ixNet getRoot] vport`).
        // A session that never loaded an .ixncfg has however many a previous
        // run happened to leave behind, so the names the suite uses may simply
        // not exist - "can't read ixia(vport3): no such element in array".
        // Create them up to the HIGHEST vport the suite names, then reload the
        // object map. Counting only the ACs is not enough once a link is spent
        // on the core: the ACs are then vport2 and vport3, so creating two
        // vports leaves $ixia(vport3) undefined and the chassis answers
        // "can't read ixia(vport3): no such element in array".
        int want = 0;
        for (int idx : params.AC_VPORT_POOL_INDEX) {
            want = Math.max(want, idx + 1);
        }
        String created = ixia.runCommand(new RawTcl(
                "set n [llength [ixNet getL [ixNet getRoot] vport]] ; "
                + "while {$n < " + want + "} { ixNet add [ixNet getRoot] vport ; "
                + "incr n } ; ixNet commit ; "
                + "puts \"\" ; "
                + "puts \"VPORTS=[llength [ixNet getL [ixNet getRoot] vport]]\" ; "
                + "puts \"\""));
        boolean enough = created != null && created.contains("VPORTS=")
                && !created.contains("VPORTS=0");
        CompassReporter.passFailByCondition(enough,
                "IXIA has at least " + want + " vports (" + oneLine(created) + ").",
                "IXIA does not have " + want + " vports (" + oneLine(created)
                        + ") - the traffic items cannot be built.");
        if (!enough) {
            throw new Exception("could not create the IXIA vports");
        }
        ixia.performFunctions(IxiaFunctions.LOAD_IXIA_OBJECT);

        for (int i = 0; i < params.AC_VPORTS.length; i++) {
            int poolIdx = params.AC_VPORT_POOL_INDEX[i];
            String card = ixia.getIntPool(AC_POOL).getInter(poolIdx).getCard();
            String port = ixia.getIntPool(AC_POOL).getInter(poolIdx).getPort();
            logMsg.info("Assigning " + params.AC_VPORTS[i]
                    + " to card " + card + " port " + port);
            ixia.performFunctions(
                    IxiaFunctions.ASSIGN_VPORT_$_WITH_CARD_$_AND_PORT_$.args(
                            params.AC_VPORTS[i], card, port, "true"));
        }
    }

    /**
     * Enable the AC VLAN on every IXIA vport, and verify the chassis took it.
     */
    public void tagVportsWithAcVlan() throws Exception {
        for (int v = 0; v < params.AC_VPORTS.length; v++) {
            String vport = params.AC_VPORTS[v];
            // The vport's own interface carries ONE VLAN, and a vport may
            // back more than one attachment circuit. This is the first of
            // them, and it is a hint rather than the classifier: what
            // actually tells two circuits on one port apart is the VLAN
            // header pushed onto each traffic item, which is per item and set
            // in tagTrafficItemsWithAcVlan(). The interface VLAN exists so a
            // raw endpoint resolves to the /vport:N/protocols form at all.
            String vlan = params.AC_VPORT_VLAN[v];
            // NOT IxiaFunctions.SET_AND_VERIFY_INTERFACE_$_VLAN_$: its proc
            // does `ixNet getL $vport vlan`, and the chassis rejects that -
            // "is not a valid child of /vport (possible options are: l1Config
            // capture protocols discoveredNeighbor interface ...)". The VLAN
            // hangs off the vport's INTERFACE, which is how their own
            // configTrafficItemEndpoints reaches it ($int/vlan). A vport with
            // no interface object gets one first; their suites get theirs from
            // the .ixncfg we deliberately do not load.
            String tcl =
                "set vp $ixia(" + vport + ") ; "
                + "set il [ixNet getL $vp interface] ; "
                + "if {[llength $il] == 0} { "
                +   "ixNet add $vp interface ; ixNet commit ; "
                +   "set il [ixNet getL $vp interface] ; "
                +   "ixNet setAtt [lindex $il 0] -enabled true ; ixNet commit "
                + "} ; "
                + "set int [lindex $il 0] ; "
                + "ixNet setMultiAtt $int/vlan -vlanEnable true ; ixNet commit ; "
                + "ixNet setMultiAtt $int/vlan -vlanId " + vlan + " ; ixNet commit ; "
                + "puts \"\" ; "
                + "puts \"ACVLAN=[ixNet getAtt $int/vlan -vlanId]"
                +   "/[ixNet getAtt $int/vlan -vlanEnable]\" ; "
                + "puts \"\"";
            String readBack = ixia.runCommand(new RawTcl(tcl));

            boolean ok = readBack != null
                    && readBack.contains("ACVLAN=" + vlan + "/true");
            CompassReporter.passFailByCondition(ok,
                    vport + ": VLAN " + vlan + " enabled on the IXIA interface.",
                    vport + ": VLAN " + vlan + " was NOT enabled (chassis said "
                            + oneLine(readBack) + ") - raw traffic endpoints "
                            + "will be rejected and no frame will reach the EVI.");
            if (!ok) {
                throw new Exception("could not tag " + vport + " with VLAN " + vlan);
            }
        }
    }

    /**
     * Start the traffic engine.
     *
     * Unsuspending an item is not the same as transmitting. Their suites load
     * an .ixncfg whose traffic is already running and only suspend/unsuspend
     * it; a suite that builds its own items must start them, or the chassis
     * holds three correctly configured items and sends nothing.
     */
    public void startTraffic() throws Exception {
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        ixia.performFunctions(IxiaFunctions.START_TRAFFIC);
        logMsg.info("Traffic started");
    }

    /** Stop the traffic engine. */
    public void stopTraffic() throws Exception {
        ixia.performFunctions(IxiaFunctions.STOP_TRAFFIC);
        logMsg.info("Traffic stopped");
    }

    // ===================================================================
    // Traffic-item lifecycle, in the VPLS suite's idiom
    //
    // Exaware, 2026-08-16 (Eyal Ozeri): "The Ixia Traffic Items are built
    // in an 'unfriendly' raw manner which will make an investigator's life
    // very hard. Need to train the model with how to build traffic items.
    // An example can be take from the VPLS suite."
    //
    // Their VplsUtils.java drives traffic through four methods, and a test
    // never touches a TCL call directly:
    //
    //     changeSuspendStatus(boolean, String... items)
    //     enableTrafficItemsAndStart(String... items)
    //     enableTrafficItemsAndStartSuspended(String... items)
    //     verifyTrafficItemsAreSuspended(String[] items)
    //     verifyTrafficItemStatistics(RowDataTable... rows)
    //
    // The same five are below, with the same names and semantics, so a
    // VPLS-literate investigator reads this suite without relearning
    // anything. The raw construction that remains is confined to
    // createTrafficItems(), called once, because we have no .ixncfg to
    // load - see that method for what would replace it.
    // ===================================================================

    /**
     * Suspend or unsuspend named traffic items, as VplsUtils does.
     *
     * `true` suspends. That reads backwards, and it is theirs: the flag is
     * the flow group's "suspend" attribute, not an enable.
     */
    public void changeSuspendStatus(boolean suspend, String... trafficItems)
            throws Exception {
        for (String trafficItem : trafficItems) {
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_STREAM
                    .args(trafficItem, 1, "null", "null", "null", "null",
                          "null", suspend));
        }
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info((suspend ? "Suspended" : "Unsuspended")
                + " traffic items: " + String.join(", ", trafficItems));
    }

    /** Enable the named items and start the traffic engine. */
    public void enableTrafficItemsAndStart(String... trafficItems)
            throws Exception {
        for (String trafficItem : trafficItems) {
            ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_$_STATE_$
                    .args(trafficItem, true));
        }
        startTraffic();
    }

    /**
     * Enable and start every item, then suspend them all.
     *
     * The prep step of every VPLS test: bring the whole traffic set up once,
     * hold it silent, and let each step unsuspend only what it needs. It
     * makes each step's traffic change small and its statistics readable,
     * which is the property Eyal was asking for.
     */
    public void enableTrafficItemsAndStartSuspended(String... trafficItems)
            throws Exception {
        enableTrafficItemsAndStart(trafficItems);
        changeSuspendStatus(true, trafficItems);
    }

    /**
     * Assert the named items are transmitting and receiving nothing.
     *
     * This is a real assertion, not a log line: a suspended item that is in
     * fact still sending would make every later "the MAC moved" step
     * meaningless, and nothing else in the run would notice.
     */
    public void verifyTrafficItemsAreSuspended(String[] trafficItems)
            throws Exception {
        ArrayList<QueryFieldList> fields = new ArrayList<QueryFieldList>();
        for (String trafficItemName : trafficItems) {
            fields.add(trafficItemStatisticsQuery(0, 0, trafficItemName));
        }
        runTrafficStatisticsQuery(fields,
                "traffic items suspended (" + String.join(", ", trafficItems) + ")");
    }

    /**
     * Assert the Traffic Item Statistics table matches the expected rows.
     *
     * Mirrors VplsUtils.verifyTrafficItemStatistics: expected Tx/Rx frame
     * rates come from the suite params table, Rx is compared with a
     * tolerance, and the query runs against the chassis's own
     * "Traffic Item Statistics" view.
     *
     * This is what a generated traffic step should have been asserting all
     * along. Before it, a traffic step logged TCL and proved nothing about
     * whether frames moved.
     */
    public void verifyTrafficItemStatistics(RowDataTable... rows)
            throws Exception {
        ArrayList<QueryFieldList> fields = new ArrayList<QueryFieldList>();
        for (RowDataTable row : rows) {
            String trafficItem = params.trafficTable.getValueStr(
                    row, TrafficItemStatisticsHeaders.Traffic_Item);
            Integer tx = intOrNull(params.trafficTable.getValueStr(
                    row, TrafficItemStatisticsHeaders.Tx_Frame_Rate));
            Integer rx = intOrNull(params.trafficTable.getValueStr(
                    row, TrafficItemStatisticsHeaders.Rx_Frame_Rate));
            fields.add(trafficItemStatisticsQuery(tx, rx, trafficItem));
        }
        runTrafficStatisticsQuery(fields, "traffic item statistics");
    }

    private Integer intOrNull(String value) {
        return value == null ? null : Integer.valueOf(Integer.parseInt(value));
    }

    /** One item's expected row, as a query. Rx carries the tolerance. */
    private QueryFieldList trafficItemStatisticsQuery(
            Integer txFrameRate, Integer rxFrameRate, String trafficItem)
            throws Exception {
        QueryFieldList itemList = new QueryFieldList();
        itemList.addQueryItem(QueryFieldItem.CONDITION_EQUAL$.args(
                TrafficItemStatisticsHeaders.Traffic_Item.getValue(),
                trafficItem));
        if (txFrameRate != null) {
            itemList.addQueryItem(QueryFieldItem.EXPECTED_VALUE_EQUAL$.args(
                    TrafficItemStatisticsHeaders.Tx_Frame_Rate.getValue(),
                    txFrameRate));
        }
        if (rxFrameRate != null) {
            int low = rxFrameRate - params.DEVIATION_FOR_VERIFY_TRAFFIC;
            if (low < 0) {
                low = 0;
            }
            itemList.addQueryItem(
                QueryFieldItem.EXPECTED_VALUE_IS_GREATER_THAN_AND_LESS_THAN$.args(
                    TrafficItemStatisticsHeaders.Rx_Frame_Rate.getValue(),
                    low,
                    rxFrameRate + params.DEVIATION_FOR_VERIFY_TRAFFIC));
        }
        return itemList;
    }

    /**
     * Run a Traffic Item Statistics query and count it as a real assertion.
     *
     * The falsifiable-assertion counter is bumped here because this check CAN
     * fail - unlike the warning-only stub that stood in for it, which is
     * exactly the kind of step the no-fake-pass rule exists to catch.
     */
    private void runTrafficStatisticsQuery(ArrayList<QueryFieldList> fields,
                                           String what) throws Exception {
        if (fields.isEmpty()) {
            CompassReporter.warning("No expected rows for " + what
                    + " - nothing was asserted.");
            return;
        }
        falsifiableAssertions++;
        QueryUtils.verifyOutputQueryResult(ixia,
                (ICmpCliCmd) IxiaFunctions.GET_TRAFFIC_PAGE_VIEW_$.args(
                        IxiaTypes.VIEW_TRAFFIC_ITEM_STATISTICS.getValue()),
                params.TRAFFIC_ITEM_STATISTICS_QCT,
                fields);
        logMsg.info("Verified " + what);
    }

    /** Enable (unsuspend) or disable (suspend) one named IXIA traffic item. */
    public void setTrafficItemState(String trafficItemName, boolean enabled)
            throws Exception {
        ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_$_STATE_$
                .args(trafficItemName, String.valueOf(enabled)));
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        if (enabled) {
            // ENABLING AN ITEM IS NOT TRANSMITTING. `-enabled true` plus
            // `trafficApply` leaves the chassis configured and silent: every
            // DUT circuit counted zero frames and the EVI learnt nothing,
            // while each call reported success. Transmission needs an
            // explicit global start.
            ixia.performFunctions(IxiaFunctions.START_TRAFFIC);
            // ...and "start" is a request, not evidence. Read the state back
            // before any assertion depends on frames having moved.
            String state = ixia.runCommand(new RawTcl(
                    "puts \"\" ; "
                    + "puts \"TRAFFICSTATE=[ixNet getAtt "
                    + "[ixNet getRoot]/traffic -state]\" ; "
                    + "puts \"\""));
            boolean running = state != null
                    && state.toLowerCase().contains("trafficstate=started");
            CompassReporter.passFailByCondition(running,
                    "Traffic is transmitting (" + oneLine(state) + ").",
                    "Traffic did NOT start (" + oneLine(state)
                            + ") - no frame reaches the EVI and nothing can "
                            + "be learnt.");
            if (!running) {
                throw new Exception("traffic did not start");
            }
        }
        logMsg.info("Traffic item " + trafficItemName + " enabled=" + enabled);
    }

    /**
     * How many assertions ran that COULD have failed.
     *
     * A suite that verified nothing must not be able to report success, so
     * this is counted rather than assumed, and checked at the end of the test.
     */
    private int falsifiableAssertions = 0;

    /**
     * Fail the test if nothing was actually verified.
     *
     * Called at the end of every generated test. A run in which every
     * verification step warned - because its expectation has never been
     * captured from a device - is not a pass; it is a run that proved the
     * plumbing works and checked no behaviour. Reporting that as green is how
     * a test suite stops being worth anything.
     */
    public void assertSomethingWasVerified() throws Exception {
        if (falsifiableAssertions == 0) {
            CompassReporter.fail("INCONCLUSIVE: this test made no assertion "
                    + "that could have failed. Every verification step ran its "
                    + "command and reported a warning, so the run says nothing "
                    + "about the feature. Capture the expectations "
                    + "(ate capture) and regenerate.");
            throw new Exception("no falsifiable assertion was made");
        }
        logMsg.info("Falsifiable assertions made: " + falsifiableAssertions);
    }

    /** Capture the current output of a command, for later no-change comparison. */
    public String snapshot(ICmpCliCmd command) throws Exception {
        return cmp.runCommandAndSwitch(command.toString(), command);
    }

    /**
     * Assert a command's output has NOT changed since the snapshot. Used for
     * the negative assertion that a purely local MAC move between two ACs on
     * the same PE triggers no new Type-2 advertisement.
     */
    public void verifyOutputUnchanged(String before, ICmpCliCmd command,
                                      String what) throws Exception {
        String after = cmp.runCommandAndSwitch(command.toString(), command);

        // An empty baseline makes this assertion vacuous: "nothing changed"
        // is trivially true when there was nothing to change, so it passes on
        // a device where the feature never worked. Seen for real - the
        // "no new Type-2 after a local MAC move" check compared
        // "% No entries found." with "% No entries found." and reported a pass.
        if (isEmptyTable(before)) {
            CompassReporter.warning(what + ": NOT ASSERTED - the baseline was "
                    + "empty (" + oneLine(before) + "), so 'unchanged' could "
                    + "not have failed. This needs a peer and traffic before it "
                    + "means anything.");
            return;
        }

        boolean unchanged = before.equals(after);
        falsifiableAssertions++;
        CompassReporter.passFailByCondition(unchanged,
                what + ": unchanged, as expected.",
                what + ": CHANGED unexpectedly.");
    }

    /** Did the device answer with no rows at all? */
    private boolean isEmptyTable(String output) {
        if (output == null) {
            return true;
        }
        String low = output.toLowerCase();
        return low.trim().isEmpty() || low.contains("no entries found");
    }

    /** Collapse output to one line, for a readable report message. */
    private String oneLine(String output) {
        if (output == null) {
            return "null";
        }
        String s = output.replace('\r', ' ').replace('\n', ' ').trim();
        return s.length() > 240 ? s.substring(0, 240) + "..." : s;
    }

    /**
     * IXIA statistics assertion for a named set of traffic items.
     *
     * This used to be a stub that only ever warned, on the grounds that the
     * expected rows needed the port naming inside an .ixncfg we do not have.
     * That was wrong twice over: the Traffic Item Statistics view is keyed by
     * the traffic item's NAME, which this suite chooses itself, and a step
     * that can only warn is a step that cannot fail.
     *
     * Reading their VPLS suite settled the shape (Eyal Ozeri, 2026-08-16:
     * "take the example from the VPLS suite"). Expected rates now live in
     * EvpnParams.trafficTable and are asserted here.
     */
    public void verifyIxiaStatistics(String what, RowDataTable[] expectedRows)
            throws Exception {
        if (expectedRows == null || expectedRows.length == 0) {
            CompassReporter.warning("IXIA statistics check '" + what
                    + "' has no expected rows in EvpnParams.trafficTable, so "
                    + "nothing was asserted.");
            return;
        }
        verifyTrafficItemStatistics(expectedRows);
    }

    /** Sleep, reporting the wait so the run log explains the gap. */
    public void waitSeconds(int seconds, String why) throws Exception {
        logMsg.info("Waiting " + seconds + " sec: " + why);
        Thread.sleep(seconds * 1000L);
    }
}
