package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-010 - EVPN VLAN-based bring-up with three local ACs
 *
 * Check the underlay from the DUT, configure a vlan-based EVI with all three
 * IXIA-backed access circuits in one commit, and confirm the service comes
 * up and originates its Type-3 IMET route. Advertisement is asserted against
 * what the DUT SENT to the IXIA peer, which negotiates L2VPN EVPN over a
 * loopback-to-loopback session carried by an LDP LSP. The peer advertises no
 * EVPN routes of its own: emulating them needs a BGP EVPN licence chassis
 * 10.1.70.108 does not have (ERROR-1005).
 * Covers: EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380,
 * RFC7432bis-section 7.3, RFC7432bis-section 11.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC01_EvpnVlanBasedBringUp extends CmpTestCase {

    @Test
    public void evpnVlanBasedBringUp() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        // The VLANs this suite puts on the wire must be ours to use:
        // in 2-4094, and not one the SUT has declared for another
        // link on this testbed. Exaware, 2026-09-08: VLAN 3380 in the
        // SUT file is an external server connection.
        evpnUtils.assertAcVlansAreFree();

        int level = 0;

        // FLOW-010.S00A - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 does not exist before this test creates it");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_SUMMARY, testParams.FLOW010_S00A_EVI_ABSENT_LINES);

        // FLOW-010.S00B - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify OSPF adjacency to the tester (29.31.31.31) is Full");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_OSPF_NEIGHBORS, testParams.FLOW010_S00B_OSPF_FULL_LINES);

        // FLOW-010.S00C - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the LDP session to the tester (29.60.0.2) is Operational");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_LDP_NEIGHBORS, testParams.FLOW010_S00C_LDP_OPERATIONAL_LINES);

        // FLOW-010.S00D - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the BGP session loopback to loopback (29.30.30.30 - 29.31.31.31) is up");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_NEIGHBORS, testParams.FLOW010_S00D_BGP_UP_LINES);

        // FLOW-010.S01 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Create evi-1 (vlan-based, import-rt and export-rt 65000:1, 3 attachment circuits) in one commit");
        evpnUtils.stageConfig(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_SERVICE_TYPE_$.args("evi-1", "vlan-based"));
        evpnUtils.stageConfig(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_IMPORT_RT_$.args("evi-1", "65000:1"));
        evpnUtils.stageConfig(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_EXPORT_RT_$.args("evi-1", "65000:1"));
        evpnUtils.stageConfig(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(0)));
        evpnUtils.stageConfig(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(1)));
        evpnUtils.stageConfig(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(2)));
        evpnUtils.commitStaged();

        // FLOW-010.S08 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 is up and all 3 attachment circuits are bound");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_DETAIL, evpnUtils.eviBoundLines("evi-1"));

        // FLOW-010.S09 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the EVPN MAC address-table has no learnt MAC yet");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"), testParams.FLOW010_S09_MAC_TABLE_EMPTY_LINES);

        // FLOW-010.S10 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the DUT originates the Type-3 IMET route for evi-1 (advertised to the tester 29.31.31.31)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), testParams.FLOW010_S10_TYPE3_ADVERTISED_LINES);

        // FLOW-010.S11 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the BGP session to the tester negotiated L2VPN EVPN (advertised and received)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_NEIGHBOR_$_EVPN_CAPABILITY.args("29.31.31.31"), testParams.FLOW010_S11_EVPN_CAPABILITY_LINES);

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
