package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-010 - EVPN VLAN-based bring-up with three local ACs
 *
 * Configure a vlan-based EVI on the DUT, bind all three IXIA-backed access
 * circuits, and confirm the service comes up and advertises its Type-3 IMET
 * route. Prerequisite for TC02 and TC03. Advertisement is asserted against
 * the local EVI table, which proves ORIGINATION but not transmission. A BGP
 * session to the IXIA-emulated peer does exist and reaches Established; what
 * it cannot carry is the EVPN address family, because chassis 10.1.70.108
 * answers ERROR-1005 'no license available for BGP EVPN'. Adding that
 * licence is what upgrades these steps to transmission.
 * Covers: EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380,
 * RFC7432bis-section 7.3, RFC7432bis-section 11.
 * 4 of 12 steps still need real device output before their assertions are
 * meaningful; those steps report a warning rather than a pass.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC01_EvpnVlanBasedBringUp extends CmpTestCase {

    @Test
    public void evpnVlanBasedBringUp() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        // The VLANs this suite puts on the wire must be ours to use:
        // in 2-4094, and not one the SUT has declared for another
        // link on this testbed. Exaware, 2026-09-08: VLAN 3380 in the
        // SUT file is an external server connection.
        evpnUtils.assertAcVlansAreFree();

        int level = 0;

        // FLOW-010.S00A - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 does not exist before this test creates it");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_SUMMARY, testParams.FLOW010_S00A_EVI_ABSENT_LINES);

        // FLOW-010.S01 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Create EVPN instance evi-1 with service-type vlan-based");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_SERVICE_TYPE_$.args("evi-1", "vlan-based"));

        // FLOW-010.S02 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Enable auto-discovery on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_AUTO_DISCOVERY.args("evi-1"));

        // FLOW-010.S03 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Set import-rt / export-rt on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_IMPORT_RT_$.args("evi-1", "65000:1"));

        // FLOW-010.S04 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Set export-rt on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_EXPORT_RT_$.args("evi-1", "65000:1"));

        // FLOW-010.S05 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC1 (agg-eth-2.1001) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(0)));

        // FLOW-010.S06 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC2 (agg-eth-3.1002) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(1)));

        // FLOW-010.S07 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC3 (agg-eth-3.1003) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(2)));

        // FLOW-010.S08 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 is up and all 3 attachment circuits are bound");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_DETAIL, testParams.FLOW010_S08_EVPN_DETAIL_LINES);

        // FLOW-010.S09 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the EVPN MAC address-table starts empty");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"), testParams.FLOW010_S09_MAC_TABLE_EMPTY_LINES);
        CompassReporter.warning("FLOW-010.S09: Needs real `show evpn mac-address-table` output.");

        // FLOW-010.S10 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the Type-3 IMET route for this EVI is originated into the local EVI table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW010_S10_TYPE3_ADVERTISED_LINES);

        // FLOW-010.S11 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the BGP session to the peer carries the L2VPN EVPN address family in its negotiated capabilities");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_NEIGHBOR_$_EVPN_CAPABILITY.args("29.60.0.2"), testParams.FLOW010_S11_EVPN_CAPABILITY_LINES);

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
