package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-030 - EVPN Route Type-2 MAC/IP advertisement, learning and local move
 *
 * Learn MACs on AC1 and AC2, confirm each is advertised as a Type-2 route,
 * then move the AC2 MACs to AC3 and confirm a purely local interface move
 * updates forwarding WITHOUT re-advertising.
 * Prerequisite: FLOW-010. Those flows must have run (or their configuration
 * be present in the bring-up) before this test.
 * Covers: RFC7432bis-section 7.2, RFC7432bis-section 7.3, RFC7432bis-section
 * 11.
 * 10 of 18 steps still need real device output before their assertions are
 * meaningful; those steps report a warning rather than a pass.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC02_EvpnType2MacIpAdvertisement extends CmpTestCase {

    @Test
    public void evpnType2MacIpAdvertisement() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        int level = 0;
        String routesBefore = null;

        // FLOW-030.S00
        CompassReporter.stopAndStartLevel(++level + ". Build the IXIA traffic items this test drives");
        evpnUtils.createTrafficItems();
        CompassReporter.warning("FLOW-030.S00: Traffic items are built over TCL rather than loaded from an .ixncfg (argument order verified against ixia_lib.tcl). The SOURCE MAC cannot be set from that library, so any assertion needing AC2 and AC3 to share a source MAC is still unmet.");

        // FLOW-030.S01 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Clear the EVPN MAC address-table so learning starts clean");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CLEAR_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"));

        // FLOW-030.S02 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC1 -> AC2");
        evpnUtils.setTrafficItemState(testParams.TI_AC1_TO_AC2, true);

        // FLOW-030.S03 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the unknown-unicast from AC1 floods to BOTH AC2 and AC3 (IXIA rx counters)");
        evpnUtils.verifyIxiaStatistics("Verify the unknown-unicast from AC1 floods to BOTH AC2 and AC3 (IXIA rx counters)", testParams.FLOW030_S03_FLOOD_TO_AC2_AC3_ROWS);
        CompassReporter.warning("FLOW-030.S03: Expected per-port rx rows depend on the .ixncfg port naming and offered rate.");

        // FLOW-030.S04 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 source MACs are learnt on agg-eth-1.100");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(0)), testParams.FLOW030_S04_AC1_MACS_LEARNT_LINES);

        // FLOW-030.S05 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 source MACs are emitted as Type-2 routes, originated into the local EVI table (no BGP peer on this rig)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW030_S05_AC1_TYPE2_ADVERTISED_LINES);
        CompassReporter.warning("FLOW-030.S05: Needs real output of the route table above.");

        // FLOW-030.S06 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC2 -> AC1");
        evpnUtils.setTrafficItemState(testParams.TI_AC2_TO_AC1, true);

        // FLOW-030.S07 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify flooding to AC3 ceases once AC2's MACs are known (AC3 rx returns to zero)");
        evpnUtils.verifyIxiaStatistics("Verify flooding to AC3 ceases once AC2's MACs are known (AC3 rx returns to zero)", testParams.FLOW030_S07_NO_FLOOD_TO_AC3_ROWS);
        CompassReporter.warning("FLOW-030.S07: Expected rows depend on .ixncfg port naming.");

        // FLOW-030.S08 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 source MACs are still intact in the MAC table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(0)), testParams.FLOW030_S04_AC1_MACS_LEARNT_LINES);

        // FLOW-030.S09 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC2 source MACs are learnt on agg-eth-2.100");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(1)), testParams.FLOW030_S09_AC2_MACS_LEARNT_LINES);
        CompassReporter.warning("FLOW-030.S09: Needs real MAC-table output plus the AC2 source-MAC range.");

        // FLOW-030.S10 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC2 source MACs are also emitted as Type-2 routes, originated into the local EVI table (no BGP peer on this rig)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW030_S10_AC2_TYPE2_ADVERTISED_LINES);
        CompassReporter.warning("FLOW-030.S10: Needs real output of the route table above.");

        // FLOW-030.S11 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Stop traffic AC2 -> AC1");
        evpnUtils.setTrafficItemState(testParams.TI_AC2_TO_AC1, false);

        // FLOW-030.S12 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 traffic still forwards to AC2 (no flooding)");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 traffic still forwards to AC2 (no flooding)", testParams.FLOW030_S12_UNICAST_TO_AC2_ROWS);
        CompassReporter.warning("FLOW-030.S12: Expected rows depend on .ixncfg port naming.");

        // FLOW-030.S13 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Snapshot the advertised Type-2 routes before moving the MACs to AC3");
        routesBefore = evpnUtils.snapshot(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL);

        // FLOW-030.S14 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC3 -> AC1 (AC3 sources the same MACs as AC2, so this is a local MAC move)");
        evpnUtils.setTrafficItemState(testParams.TI_AC3_TO_AC1, true);

        // FLOW-030.S15 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC2 MACs have shifted to agg-eth-3.100");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(2)), testParams.FLOW030_S15_MACS_MOVED_TO_AC3_LINES);

        // FLOW-030.S16 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify NO new Type-2 was triggered by the local AC2 -> AC3 move (route table unchanged vs the snapshot)");
        evpnUtils.verifyOutputUnchanged(routesBefore, EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, "Verify NO new Type-2 was triggered by the local AC2 -> AC3 move (route table unchanged vs the snapshot)");

        // FLOW-030.S17 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 traffic now forwards out AC3");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 traffic now forwards out AC3", testParams.FLOW030_S17_UNICAST_TO_AC3_ROWS);
        CompassReporter.warning("FLOW-030.S17: Expected rows depend on .ixncfg port naming.");

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
