package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-030 - EVPN Route Type-2 MAC/IP advertisement, learning and local move
 *
 * Learn MACs on AC1 and AC2, confirm each is advertised as a Type-2 route,
 * then move the AC2 MACs to AC3 and confirm a purely local interface move
 * updates forwarding WITHOUT re-advertising. Advertisement is asserted
 * against the local EVI table, which proves ORIGINATION but not
 * transmission. A BGP session to the IXIA-emulated peer does exist and
 * reaches Established; what it cannot carry is the EVPN address family,
 * because chassis 10.1.70.108 answers ERROR-1005 'no license available for
 * BGP EVPN'. Adding that licence is what upgrades these steps to
 * transmission.
 * Prerequisite: FLOW-010. Those flows must have run before this test. The
 * EVPN service is created by TC01 and is deliberately NOT in the bring-up
 * configuration file, so that TC01's create steps can fail; the first step
 * here asserts it is present.
 * Covers: EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380,
 * RFC7432bis-section 7.2, RFC7432bis-section 7.3, RFC7432bis-section 11.
 * 9 of 27 steps still need real device output before their assertions are
 * meaningful; those steps report a warning rather than a pass.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC02_EvpnType2MacIpAdvertisement extends CmpTestCase {

    @Test
    public void evpnType2MacIpAdvertisement() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        // The VLANs this suite puts on the wire must be ours to use:
        // in 2-4094, and not one the SUT has declared for another
        // link on this testbed. Exaware, 2026-09-08: VLAN 3380 in the
        // SUT file is an external server connection.
        evpnUtils.assertAcVlansAreFree();

        int level = 0;
        String routesBefore = null;

        // FLOW-030.S00P - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 does not exist before this test creates it (bring-up reloads the .cfg before every test)");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_SUMMARY, testParams.FLOW030_S00P_EVI_ABSENT_LINES);

        // FLOW-030.S00Q - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Create EVPN instance evi-1 with service-type vlan-based");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_SERVICE_TYPE_$.args("evi-1", "vlan-based"));

        // FLOW-030.S00R - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Enable auto-discovery on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_AUTO_DISCOVERY.args("evi-1"));

        // FLOW-030.S00S - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Set import-rt on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_IMPORT_RT_$.args("evi-1", "65000:1"));

        // FLOW-030.S00T - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Set export-rt on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_EXPORT_RT_$.args("evi-1", "65000:1"));

        // FLOW-030.S00U1 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC1 (agg-eth-2.1001) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(0)));

        // FLOW-030.S00U2 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC2 (agg-eth-3.1002) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(1)));

        // FLOW-030.S00U3 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC3 (agg-eth-3.1003) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(2)));

        // FLOW-030.S00V - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 is up and all 3 attachment circuits are bound before the test proper begins");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_DETAIL, evpnUtils.eviBoundLines("evi-1"));

        // FLOW-030.S00
        CompassReporter.stopAndStartLevel(++level + ". Build the IXIA traffic items this test drives");
        evpnUtils.createTrafficItems();

        // FLOW-030.S01 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Clear the EVPN MAC address-table so learning starts clean");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CLEAR_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"));

        // FLOW-030.S02 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC1 -> AC2");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC1_TO_AC2);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC1_TO_AC2_RUNNING);

        // FLOW-030.S03 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the unknown-unicast from AC1 floods to BOTH AC2 and AC3 (IXIA rx counters)");
        evpnUtils.verifyIxiaStatistics("Verify the unknown-unicast from AC1 floods to BOTH AC2 and AC3 (IXIA rx counters)", testParams.ALL_TRAFFIC_ITEMS_RUNNING);
        CompassReporter.warning("FLOW-030.S03: Expected per-port rx rows depend on the .ixncfg port naming and offered rate.");

        // FLOW-030.S04 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 source MACs are learnt on agg-eth-2.1001");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(0)), testParams.FLOW030_S04_AC1_MACS_LEARNT_LINES);
        CompassReporter.warning("FLOW-030.S04: Needs real MAC-table output plus the AC1 source-MAC range.");

        // FLOW-030.S05 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 source MACs are emitted as Type-2 routes, originated into the local EVI table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW030_S05_AC1_TYPE2_ADVERTISED_LINES);
        CompassReporter.warning("FLOW-030.S05: Needs real output of the route table above.");

        // FLOW-030.S06 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC2 -> AC1");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC2_TO_AC1);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC2_TO_AC1_RUNNING);

        // FLOW-030.S07 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify flooding to AC3 ceases once AC2's MACs are known (AC3 rx returns to zero)");
        evpnUtils.verifyIxiaStatistics("Verify flooding to AC3 ceases once AC2's MACs are known (AC3 rx returns to zero)", testParams.ALL_TRAFFIC_ITEMS_RUNNING);
        CompassReporter.warning("FLOW-030.S07: Expected rows depend on .ixncfg port naming.");

        // FLOW-030.S08 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 source MACs are still intact in the MAC table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(0)), testParams.FLOW030_S04_AC1_MACS_LEARNT_LINES);

        // FLOW-030.S09 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC2 source MACs are learnt on agg-eth-3.1002");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(1)), testParams.FLOW030_S09_AC2_MACS_LEARNT_LINES);
        CompassReporter.warning("FLOW-030.S09: Needs real MAC-table output plus the AC2 source-MAC range.");

        // FLOW-030.S10 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC2 source MACs are also emitted as Type-2 routes, originated into the local EVI table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW030_S10_AC2_TYPE2_ADVERTISED_LINES);
        CompassReporter.warning("FLOW-030.S10: Needs real output of the route table above.");

        // FLOW-030.S11 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Stop traffic AC2 -> AC1");
        evpnUtils.changeSuspendStatus(true, testParams.TI_AC2_TO_AC1);
        evpnUtils.verifyTrafficItemsAreSuspended(new String[] {testParams.TI_AC2_TO_AC1});

        // FLOW-030.S12 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 traffic still forwards to AC2 (no flooding)");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 traffic still forwards to AC2 (no flooding)", testParams.ALL_TRAFFIC_ITEMS_RUNNING);
        CompassReporter.warning("FLOW-030.S12: Expected rows depend on .ixncfg port naming.");

        // FLOW-030.S13 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Snapshot the advertised Type-2 routes before moving the MACs to AC3");
        routesBefore = evpnUtils.snapshot(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL);

        // FLOW-030.S14 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC3 -> AC1 (AC3 sources the same MACs as AC2, so this is a local MAC move)");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC3_TO_AC1);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC3_TO_AC1_RUNNING);

        // FLOW-030.S15 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC2 MACs have shifted to agg-eth-3.1003");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(2)), testParams.FLOW030_S15_MACS_MOVED_TO_AC3_LINES);
        CompassReporter.warning("FLOW-030.S15: Needs real MAC-table output.");

        // FLOW-030.S16 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify NO new Type-2 was triggered by the local AC2 -> AC3 move (route table unchanged vs the snapshot)");
        evpnUtils.verifyOutputUnchanged(routesBefore, EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, "Verify NO new Type-2 was triggered by the local AC2 -> AC3 move (route table unchanged vs the snapshot)");

        // FLOW-030.S17 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 traffic now forwards out AC3");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 traffic now forwards out AC3", testParams.ALL_TRAFFIC_ITEMS_RUNNING);
        CompassReporter.warning("FLOW-030.S17: Expected rows depend on .ixncfg port naming.");

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
