package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-030 - EVPN Type-2 MAC learning, known-unicast forwarding and local
 * MAC move
 *
 * Unknown unicast from AC1 floods to AC2 and AC3; once AC2's MAC is learnt
 * the same traffic goes to AC2 alone; after AC3 takes over the MAC it goes
 * to AC3 alone, and the purely local move does not re-originate the Type-2
 * route. Advertisement is asserted against what the DUT SENT to the IXIA
 * peer, which negotiates L2VPN EVPN over a loopback-to-loopback session
 * carried by an LDP LSP. The peer advertises no EVPN routes of its own:
 * emulating them needs a BGP EVPN licence chassis 10.1.70.108 does not have
 * (ERROR-1005).
 * Prerequisite: FLOW-010. Those flows must have run before this test. The
 * EVPN service is created by TC01 and is deliberately NOT in the bring-up
 * configuration file, so that TC01's create steps can fail; the first step
 * here asserts it is present.
 * Covers: EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380,
 * RFC7432bis-section 7.2, RFC7432bis-section 7.3, RFC7432bis-section 11.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC02_EvpnType2MacIpAdvertisement extends CmpTestCase {

    @Test
    public void evpnType2MacIpAdvertisement() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        // The VLANs this suite puts on the wire must be ours to use:
        // in 2-4094, and not one the SUT has declared for another
        // link on this testbed. Exaware, 2026-09-08: VLAN 3380 in the
        // SUT file is an external server connection.
        evpnUtils.assertAcVlansAreFree();

        int level = 0;
        String routesBefore = null;

        // FLOW-030.S00V - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 from the bring-up configuration is up with all 3 attachment circuits bound");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_DETAIL, evpnUtils.eviBoundLines("evi-1"));

        // FLOW-030.S00B - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify OSPF adjacency to the tester (29.31.31.31) is Full");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_OSPF_NEIGHBORS, testParams.FLOW030_S00B_OSPF_FULL_LINES);

        // FLOW-030.S00C - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the LDP session to the tester (29.60.0.2) is Operational");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_LDP_NEIGHBORS, testParams.FLOW030_S00C_LDP_OPERATIONAL_LINES);

        // FLOW-030.S00D - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the BGP session loopback to loopback (29.30.30.30 - 29.31.31.31) is up");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_NEIGHBORS, testParams.FLOW030_S00D_BGP_UP_LINES);

        // FLOW-030.S00
        CompassReporter.stopAndStartLevel(++level + ". Load the IXIA traffic items this test drives");
        evpnUtils.createTrafficItems();

        // FLOW-030.S01 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Clear the EVPN MAC address-table so learning starts clean");
        evpnUtils.execAndVerifyAccepted(EvpnCommands.CLEAR_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"));

        // FLOW-030.S02 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC1 -> AC2 (unicast to 00:00:02:00:00:01, not yet learnt)");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC1_TO_AC2);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC1_TO_AC2_RUNNING);

        // FLOW-030.S03 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify unknown unicast from AC1 is flooded to BOTH AC2 and AC3 (rx 2000 = 2 x tx; DUT transmits on both)");
        evpnUtils.verifyIxiaStatistics("Verify unknown unicast from AC1 is flooded to BOTH AC2 and AC3 (rx 2000 = 2 x tx; DUT transmits on both)", testParams.FLOW030_S03_UNKNOWN_UNICAST_FLOODED_ROWS);
        evpnUtils.verifyAcEgress(new int[] {1, 2}, new int[] {});

        // FLOW-030.S04 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify 00:00:01:00:00:01 is learnt on AC1 (VLAN 1001)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(0)), testParams.FLOW030_S04_AC1_MACS_LEARNT_LINES);

        // FLOW-030.S05 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the DUT originates a Type-2 route for 00:00:01:00:00:01 (advertised to the tester 29.31.31.31)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), testParams.FLOW030_S05_AC1_TYPE2_ADVERTISED_LINES);

        // FLOW-030.S06 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC2 -> AC1 (AC2 sources 00:00:02:00:00:01)");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC2_TO_AC1);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC2_TO_AC1_RUNNING);

        // FLOW-030.S07 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 is now KNOWN unicast: rx 1000, out of AC2 only, nothing to AC3");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 is now KNOWN unicast: rx 1000, out of AC2 only, nothing to AC3", testParams.FLOW030_S07_KNOWN_UNICAST_ROWS);
        evpnUtils.verifyAcEgress(new int[] {1}, new int[] {2});

        // FLOW-030.S09 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify 00:00:02:00:00:01 is learnt on AC2 (VLAN 1002)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(1)), testParams.FLOW030_S09_AC2_MACS_LEARNT_LINES);

        // FLOW-030.S10 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the DUT originates a Type-2 route for 00:00:02:00:00:01 (advertised to the tester 29.31.31.31)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), testParams.FLOW030_S10_AC2_TYPE2_ADVERTISED_LINES);

        // FLOW-030.S13 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Snapshot the DUT's Type-2 route for 00:00:02:00:00:01 before moving it to AC3");
        routesBefore = evpnUtils.snapshot(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"));

        // FLOW-030.S11 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Stop traffic AC2 -> AC1");
        evpnUtils.changeSuspendStatus(true, testParams.TI_AC2_TO_AC1);
        evpnUtils.verifyTrafficItemsAreSuspended(new String[] {testParams.TI_AC2_TO_AC1});

        // FLOW-030.S14 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC3 -> AC1 (AC3 sources 00:00:02:00:00:01, the same MAC as AC2: a local MAC move)");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC3_TO_AC1);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC3_TO_AC1_RUNNING);

        // FLOW-030.S15 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify 00:00:02:00:00:01 has moved to AC3 (VLAN 1003)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(2)), testParams.FLOW030_S15_MACS_MOVED_TO_AC3_LINES);

        // FLOW-030.S16 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the local AC2 -> AC3 move did not re-originate the Type-2 route for 00:00:02:00:00:01 (route unchanged vs the snapshot)");
        evpnUtils.verifyOutputUnchanged(routesBefore, EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), "Verify the local AC2 -> AC3 move did not re-originate the Type-2 route for 00:00:02:00:00:01 (route unchanged vs the snapshot)");

        // FLOW-030.S16B - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the Type-2 for 00:00:02:00:00:01 still carries MAC Mobility SeqNum=0 after the local move (advertised to the tester 29.31.31.31)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), testParams.FLOW030_S16B_SEQNUM_UNCHANGED_LINES);

        // FLOW-030.S17 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 now follows the MAC: rx 1000, out of AC3 only, nothing to AC2");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 now follows the MAC: rx 1000, out of AC3 only, nothing to AC2", testParams.FLOW030_S17_FOLLOWS_MOVE_ROWS);
        evpnUtils.verifyAcEgress(new int[] {2}, new int[] {1});

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
