package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-031 - EVPN Route Type-3 IMET flooding and Type-2 withdrawal on aging
 *
 * After the AC3 source stops, wait out MAC aging and confirm the service
 * reverts to flooding, the MAC table drops the aged entries, and their
 * Type-2 routes are withdrawn.
 * Prerequisite: FLOW-010, FLOW-030. Those flows must have run (or their
 * configuration be present in the bring-up) before this test.
 * Covers: RFC7432bis-section 7.3, RFC7432bis-section 11, RFC7432bis-section
 * 7.2.
 * 4 of 7 steps still need real device output before their assertions are
 * meaningful; those steps report a warning rather than a pass.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC03_EvpnType3ImetFlooding extends CmpTestCase {

    @Test
    public void evpnType3ImetFlooding() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        int level = 0;

        // FLOW-031.S00
        CompassReporter.stopAndStartLevel(++level + ". Build the IXIA traffic items this test drives");
        evpnUtils.createTrafficItems();
        CompassReporter.warning("FLOW-031.S00: Traffic items are built over TCL rather than loaded from an .ixncfg (argument order verified against ixia_lib.tcl). The SOURCE MAC cannot be set from that library, so any assertion needing AC2 and AC3 to share a source MAC is still unmet.");

        // FLOW-031.S01 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Stop traffic AC3 -> AC1");
        evpnUtils.setTrafficItemState(testParams.TI_AC3_TO_AC1, false);

        // FLOW-031.S02 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Wait out the 300s MAC aging time (CLI doc default; range 0, 40-2400)");
        evpnUtils.waitSeconds(testParams.MAC_AGING_TIME_IN_SEC, "Wait out the 300s MAC aging time (CLI doc default; range 0, 40-2400)");

        // FLOW-031.S03 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 traffic floods to BOTH AC2 and AC3 again now the MACs have aged out");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 traffic floods to BOTH AC2 and AC3 again now the MACs have aged out", testParams.FLOW030_S03_FLOOD_TO_AC2_AC3_ROWS);

        // FLOW-031.S04 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC2 MACs are removed from the EVPN MAC table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"), testParams.FLOW031_S04_MACS_AGED_OUT_LINES);
        CompassReporter.warning("FLOW-031.S04: Needs real MAC-table output.");

        // FLOW-031.S05 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC2 MACs' Type-2 routes are withdrawn from the BGP table");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW031_S05_TYPE2_WITHDRAWN_LINES);
        CompassReporter.warning("FLOW-031.S05: Needs real BGP EVPN table output.");

        // FLOW-031.S06 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the BUM routing table still lists the flood list");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_BROADCAST_DOMAINS_NAME_$.args("evi-1"), testParams.FLOW031_S06_BUM_BROADCAST_DOMAIN_LINES);
        CompassReporter.warning("FLOW-031.S06: Needs real `show evpn broadcast-domains` output with an EVI configured; `show evpn bum routing-table` does not exist on this build.");

        CompassReporter.stopLevel();
    }
}
