package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-031 - EVPN MAC aging: Type-2 withdrawal and return to flooding
 *
 * Learn AC2's MAC and show AC1's unicast to it reaches AC2 alone; stop AC2,
 * let the MAC age out, and confirm the entry and its Type-2 route are gone
 * and the same unicast is flooded to AC2 and AC3 again. Advertisement is
 * asserted against what the DUT SENT to the IXIA peer, which negotiates
 * L2VPN EVPN over a loopback-to-loopback session carried by an LDP LSP. The
 * peer advertises no EVPN routes of its own: emulating them needs a BGP EVPN
 * licence chassis 10.1.70.108 does not have (ERROR-1005).
 * Prerequisite: FLOW-010. Those flows must have run before this test. The
 * EVPN service is created by TC01 and is deliberately NOT in the bring-up
 * configuration file, so that TC01's create steps can fail; the first step
 * here asserts it is present.
 * Covers: EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380,
 * RFC7432bis-section 7.2, RFC7432bis-section 7.3, RFC7432bis-section 11.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC03_EvpnType3ImetFlooding extends CmpTestCase {

    @Test
    public void evpnType3ImetFlooding() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        // The VLANs this suite puts on the wire must be ours to use:
        // in 2-4094, and not one the SUT has declared for another
        // link on this testbed. Exaware, 2026-09-08: VLAN 3380 in the
        // SUT file is an external server connection.
        evpnUtils.assertAcVlansAreFree();

        int level = 0;

        // FLOW-031.S00V - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 from the bring-up configuration is up with all 3 attachment circuits bound");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_DETAIL, evpnUtils.eviBoundLines("evi-1"));

        // FLOW-031.S00B - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify OSPF adjacency to the tester (29.31.31.31) is Full");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_OSPF_NEIGHBORS, testParams.FLOW031_S00B_OSPF_FULL_LINES);

        // FLOW-031.S00C - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the LDP session to the tester (29.60.0.2) is Operational");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_LDP_NEIGHBORS, testParams.FLOW031_S00C_LDP_OPERATIONAL_LINES);

        // FLOW-031.S00D - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify the BGP session loopback to loopback (29.30.30.30 - 29.31.31.31) is up");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_NEIGHBORS, testParams.FLOW031_S00D_BGP_UP_LINES);

        // FLOW-031.S00
        CompassReporter.stopAndStartLevel(++level + ". Load the IXIA traffic items this test drives");
        evpnUtils.createTrafficItems();

        // FLOW-031.S01A - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Set mac-aging-time 60 on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_MAC_AGING_TIME_$.args("evi-1", "60"));

        // FLOW-031.S01P - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start traffic AC1 -> AC2 and AC2 -> AC1 so 00:00:02:00:00:01 is learnt on AC2");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC1_TO_AC2, testParams.TI_AC2_TO_AC1);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC1_TO_AC2_RUNNING, testParams.TI_AC2_TO_AC1_RUNNING);

        // FLOW-031.S01Q - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify 00:00:02:00:00:01 is learnt on AC2 before the aging test begins");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(1)), testParams.FLOW031_S01Q_MACS_LEARNT_LINES);

        // FLOW-031.S01R - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 is known unicast while 00:00:02:00:00:01 is learnt: rx 1000, AC2 only");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 is known unicast while 00:00:02:00:00:01 is learnt: rx 1000, AC2 only", testParams.FLOW031_S01R_KNOWN_UNICAST_ROWS);
        evpnUtils.verifyAcEgress(new int[] {1}, new int[] {2});

        // FLOW-031.S01S - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the DUT originates a Type-2 route for 00:00:02:00:00:01 before it ages (advertised to the tester 29.31.31.31)");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), testParams.FLOW031_S01S_TYPE2_ADVERTISED_LINES);

        // FLOW-031.S01 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Stop traffic AC2 -> AC1, so nothing refreshes its MAC");
        evpnUtils.changeSuspendStatus(true, testParams.TI_AC2_TO_AC1);
        evpnUtils.verifyTrafficItemsAreSuspended(new String[] {testParams.TI_AC2_TO_AC1});

        // FLOW-031.S02 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Wait out the 60 s MAC aging time");
        evpnUtils.waitSeconds(testParams.MAC_AGING_TIME_IN_SEC, "Wait out the 60 s MAC aging time");

        // FLOW-031.S04 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify 00:00:02:00:00:01 has aged out of the EVPN MAC table");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$.args("evi-1"), testParams.FLOW031_S04_MACS_AGED_OUT_LINES, testParams.AGING_VERIFY_TIMEOUT_IN_MSEC);

        // FLOW-031.S05 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the Type-2 route for 00:00:02:00:00:01 is withdrawn (advertised to the tester 29.31.31.31)");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_BGP_L2VPN_EVPN_NEIGHBORS_ADVERTISED_ROUTES_$_DETAIL.args("29.31.31.31"), testParams.FLOW031_S05_TYPE2_WITHDRAWN_LINES, testParams.AGING_VERIFY_TIMEOUT_IN_MSEC);

        // FLOW-031.S03 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1 -> AC2 is flooded again now 00:00:02:00:00:01 is unknown: rx 2000, out of AC2 AND AC3");
        evpnUtils.verifyIxiaStatistics("Verify AC1 -> AC2 is flooded again now 00:00:02:00:00:01 is unknown: rx 2000, out of AC2 AND AC3", testParams.FLOW031_S03_FLOODED_AFTER_AGING_ROWS);
        evpnUtils.verifyAcEgress(new int[] {1, 2}, new int[] {});

        // FLOW-031.S06 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the broadcast domain still lists all 3 circuits as flood targets");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_BROADCAST_DOMAINS_NAME_$.args("evi-1"), evpnUtils.eviBoundLines("evi-1"));

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
