package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-031 - EVPN Route Type-3 IMET flooding and Type-2 withdrawal on aging
 *
 * After the AC3 source stops, wait out MAC aging and confirm the service
 * reverts to flooding, the MAC table drops the aged entries, and their
 * Type-2 routes are withdrawn. Advertisement is asserted against the local
 * EVI table, which proves ORIGINATION but not transmission. A BGP session to
 * the IXIA-emulated peer does exist and reaches Established; what it cannot
 * carry is the EVPN address family, because chassis 10.1.70.108 answers
 * ERROR-1005 'no license available for BGP EVPN'. Adding that licence is
 * what upgrades these steps to transmission.
 * Prerequisite: FLOW-010, FLOW-030. Those flows must have run before this
 * test. The EVPN service is created by TC01 and is deliberately NOT in the
 * bring-up configuration file, so that TC01's create steps can fail; the
 * first step here asserts it is present.
 * Covers: EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380,
 * RFC7432bis-section 7.2, RFC7432bis-section 7.3, RFC7432bis-section 11.
 * 4 of 19 steps still need real device output before their assertions are
 * meaningful; those steps report a warning rather than a pass.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TC03_EvpnType3ImetFlooding extends CmpTestCase {

    @Test
    public void evpnType3ImetFlooding() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        // The VLANs this suite puts on the wire must be ours to use:
        // in 2-4094, and not one the SUT has declared for another
        // link on this testbed. Exaware, 2026-09-08: VLAN 3380 in the
        // SUT file is an external server connection.
        evpnUtils.assertAcVlansAreFree();

        int level = 0;

        // FLOW-031.S00P - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 does not exist before this test creates it (bring-up reloads the .cfg before every test)");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_SUMMARY, testParams.FLOW031_S00P_EVI_ABSENT_LINES);

        // FLOW-031.S00Q - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Create EVPN instance evi-1 with service-type vlan-based");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_SERVICE_TYPE_$.args("evi-1", "vlan-based"));

        // FLOW-031.S00R - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Enable auto-discovery on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_AUTO_DISCOVERY.args("evi-1"));

        // FLOW-031.S00S - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Set import-rt on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_IMPORT_RT_$.args("evi-1", "65000:1"));

        // FLOW-031.S00T - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Set export-rt on evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_EXPORT_RT_$.args("evi-1", "65000:1"));

        // FLOW-031.S00U1 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC1 (agg-eth-2.1001) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(0)));

        // FLOW-031.S00U2 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC2 (agg-eth-3.1002) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(1)));

        // FLOW-031.S00U3 - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Bind access circuit AC3 (agg-eth-3.1003) to evi-1");
        evpnUtils.configAndVerifyAccepted(EvpnCommands.CONFIGURE_L2_SERVICES_EVPN_$_INTERFACE_$.args("evi-1", evpnUtils.acInterface(2)));

        // FLOW-031.S00V - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Verify evi-1 is up and all 3 attachment circuits are bound before the test proper begins");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_DETAIL, evpnUtils.eviBoundLines("evi-1"));

        // FLOW-031.S00
        CompassReporter.stopAndStartLevel(++level + ". Load the IXIA traffic items this test drives");
        evpnUtils.createTrafficItems();

        // FLOW-031.S00X - covers EVPNS-REQ#30, EVPNS-REQ#40, EVPNS-REQ#50, EVPNS-REQ#380
        CompassReporter.stopAndStartLevel(++level + ". Start the tester's OSPF, LDP and BGP and verify they are running");
        evpnUtils.startTesterProtocolsAndVerify();

        // FLOW-031.S01P - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Start AC1 and AC3 traffic so there are MACs to age out");
        evpnUtils.changeSuspendStatus(false, testParams.TI_AC1_TO_AC2, testParams.TI_AC3_TO_AC1);
        evpnUtils.verifyTrafficItemStatistics(testParams.TI_AC1_TO_AC2_RUNNING, testParams.TI_AC3_TO_AC1_RUNNING);

        // FLOW-031.S01Q - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC3 MACs ARE learnt before the aging test begins");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(2)), testParams.FLOW031_S01Q_MACS_LEARNT_LINES);

        // FLOW-031.S01 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Stop traffic AC3 -> AC1");
        evpnUtils.changeSuspendStatus(true, testParams.TI_AC3_TO_AC1);
        evpnUtils.verifyTrafficItemsAreSuspended(new String[] {testParams.TI_AC3_TO_AC1});

        // FLOW-031.S02 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Wait out the 300s MAC aging time (CLI doc default; range 0, 40-2400)");
        evpnUtils.waitSeconds(testParams.MAC_AGING_TIME_IN_SEC, "Wait out the 300s MAC aging time (CLI doc default; range 0, 40-2400)");

        // FLOW-031.S03 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify AC1's traffic still floods to BOTH AC2 and AC3 while AC3 stays silent after aging");
        evpnUtils.verifyIxiaStatistics("Verify AC1's traffic still floods to BOTH AC2 and AC3 while AC3 stays silent after aging", testParams.FLOW031_S03_FLOOD_AFTER_AGING_ROWS);

        // FLOW-031.S04 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC3 MACs are removed from the EVPN MAC table once their traffic stopped and they aged out");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_EVPN_MAC_ADDRESS_TABLE_NAME_$_SOURCE_$.args("evi-1", evpnUtils.acInterfaceCompact(2)), testParams.FLOW031_S04_MACS_AGED_OUT_LINES);

        // FLOW-031.S05 - covers RFC7432bis-section 7.2
        CompassReporter.stopAndStartLevel(++level + ". Verify the AC2 MACs' Type-2 routes are withdrawn from the BGP table");
        evpnUtils.verifyShowLinesAbsent(EvpnCommands.SHOW_BGP_L2VPN_EVPN_TABLE_EVI_DETAIL, testParams.FLOW031_S05_TYPE2_WITHDRAWN_LINES);

        // FLOW-031.S06 - covers RFC7432bis-section 7.3, RFC7432bis-section 11
        CompassReporter.stopAndStartLevel(++level + ". Verify the BUM routing table still lists the flood list");
        evpnUtils.verifyShowLines(EvpnCommands.SHOW_EVPN_BROADCAST_DOMAINS_NAME_$.args("evi-1"), testParams.FLOW031_S06_BUM_BROADCAST_DOMAIN_LINES);

        // PIPELINE RULE: a test that verified nothing is not a pass.
        evpnUtils.assertSomethingWasVerified();
        CompassReporter.stopLevel();
    }
}
