package cmp.tests.evpn;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Pattern;

import cmp.infra.CmpRouter;
import cmp.infra.Session.ICmpCliCmd;
import cmp.infra.ixia.Ixia;
import cmp.infra.ixia.IxiaFunctions;
import cmp.infra.reporter.CompassReporter;
import cmp.infra.reporter.loggerImp;

/**
 * Verification helpers for the generated EVPN suite.
 *
 * Mirrors the shape of cmp.tests.vpls.VplsUtils: the test class stays a
 * readable sequence of numbered steps and every assertion lives here.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class EvpnUtils implements loggerImp {

    private final EvpnParams params;
    private final CmpRouter cmp;
    private final Ixia ixia;

    public EvpnUtils(EvpnParams params, CmpRouter cmp, Ixia ixia) {
        this.params = params;
        this.cmp = cmp;
        this.ixia = ixia;
    }

    /**
     * Run a show command and assert every expected line (a regex) appears in
     * the output, polling until the verify timeout. Modelled on
     * ShowVplsDetail.verifyShowVplsDetail.
     *
     * An EMPTY expectation array means "not yet validated against a real
     * device": the command is still run and its output reported, but the
     * result is a warning, never a pass.
     */
    public void verifyShowLines(ICmpCliCmd command, String[] expectedLines)
            throws Exception {
        String output = cmp.runCommandAndSwitch(command.toString(), command);

        if (expectedLines == null || expectedLines.length == 0) {
            CompassReporter.warning("No validated expectation for '"
                    + command.toString() + "' yet - output captured for "
                    + "review, nothing asserted.");
            logMsg.info(output);
            return;
        }

        Set<String> missing = new LinkedHashSet<String>();
        boolean asExpected = false;
        long endTime = System.currentTimeMillis() + params.VERIFY_TIMEOUT_IN_MSEC;

        while (!asExpected && System.currentTimeMillis() < endTime) {
            missing.clear();
            asExpected = true;
            for (int i = 0; i < expectedLines.length; i++) {
                String expected = expectedLines[i];
                if (output == null
                        || !Pattern.compile(expected).matcher(output).find()) {
                    missing.add(expected);
                    asExpected = false;
                }
            }
            if (!asExpected) {
                Thread.sleep(params.VERIFY_INTERVAL_IN_MSEC);
                output = cmp.runCommandAndSwitch(command.toString(), command);
            }
        }

        CompassReporter.passFailByCondition(asExpected,
                "The output of " + command.toString() + " is as expected.",
                "The output of " + command.toString()
                        + " is not as expected. Missing lines: " + missing);
    }

    /** Enable (unsuspend) or disable (suspend) one named IXIA traffic item. */
    public void setTrafficItemState(String trafficItemName, boolean enabled)
            throws Exception {
        ixia.performFunctions(IxiaFunctions.CONFIGURE_TRAFFIC_ITEM_$_STATE_$
                .args(trafficItemName, String.valueOf(enabled)));
        ixia.performFunctions(IxiaFunctions.APPLY_TRAFFIC);
        logMsg.info("Traffic item " + trafficItemName + " enabled=" + enabled);
    }

    /** Capture the current output of a command, for later no-change comparison. */
    public String snapshot(ICmpCliCmd command) throws Exception {
        return cmp.runCommandAndSwitch(command.toString(), command);
    }

    /**
     * Assert a command's output has NOT changed since the snapshot. Used for
     * the negative assertion that a purely local MAC move between two ACs on
     * the same PE triggers no new Type-2 advertisement.
     */
    public void verifyOutputUnchanged(String before, ICmpCliCmd command,
                                      String what) throws Exception {
        String after = cmp.runCommandAndSwitch(command.toString(), command);
        boolean unchanged = (before == null)
                ? (after == null) : before.equals(after);
        CompassReporter.passFailByCondition(unchanged,
                what + ": unchanged, as expected.",
                what + ": CHANGED unexpectedly.");
    }

    /**
     * IXIA per-port / per-flow statistics assertion.
     *
     * Left as an explicit gap: the expected rows depend on the port naming and
     * offered rate inside the .ixncfg that Exaware build for this rig, and
     * ShowIxiaStatistics drives them from a RowDataTable populated out of the
     * suite params table. Wiring that needs the real .ixncfg.
     */
    public void verifyIxiaStatistics(String what, String[] expectedRows)
            throws Exception {
        if (expectedRows == null || expectedRows.length == 0) {
            CompassReporter.warning("IXIA statistics check '" + what
                    + "' is not wired yet - needs the .ixncfg port naming and "
                    + "a RowDataTable in EvpnParams. See "
                    + "ShowIxiaStatistics.verifyDataPlanPortStatistics.");
            return;
        }
        CompassReporter.warning("IXIA statistics check '" + what
                + "' has expectations but no table binding yet.");
    }

    /** Sleep, reporting the wait so the run log explains the gap. */
    public void waitSeconds(int seconds, String why) throws Exception {
        logMsg.info("Waiting " + seconds + " sec: " + why);
        Thread.sleep(seconds * 1000L);
    }
}
