package cmp.tests.evpn;

import org.junit.Test;

import cmp.infra.CmpRouter;
import cmp.infra.CmpTestCase;
import cmp.infra.bringUp.DevicesSut;
import cmp.infra.ixia.Ixia;
import cmp.infra.reporter.CompassReporter;

/**
 * FLOW-020 - All-active multi-homing bring-up + DF election
 *
 * FLOW-020 - All-active multi-homing bring-up + DF election. Generated
 * MECHANICALLY from the test plan: every step below was derived by pattern
 * matching over the plan's own rows, with commands grounded in the EVPN CLI
 * doc via EvpnCommands. No step was hand-written. Expectations are empty
 * pending real device output, so every step reports a warning rather than a
 * pass.
 * Covers: EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260,
 * EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4,
 * RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5,
 * RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1,
 * RFC9785-section 4.2, RFC9785-section 4.3.
 * 28 of 28 steps still need real device output before their assertions are
 * meaningful; those steps report a warning rather than a pass.
 *
 * Generated by the ATE test-plan pipeline from the EVPN SFS, the EVPN CLI
 * doc and RFC 7432bis.
 */
public class TCM020_EvpnAllActiveMultiHomingBringUpDfElection extends CmpTestCase {

    @Test
    public void evpnAllActiveMultiHomingBringUpDfElection() throws Exception {

        CmpRouter cmp1 = getDevices().getCmpRouter(DevicesSut.CMP1);
        Ixia ixia = getDevices().getIxiaRouter(DevicesSut.IXIA1);
        EvpnParams testParams = (EvpnParams) getSuiteParams();
        EvpnUtils evpnUtils = new EvpnUtils(testParams, cmp1, ixia);

        int level = 0;

        // FLOW-020.M001
        CompassReporter.stopAndStartLevel(++level + ". Problem: Validate that PEs with mismatched DF Election algorithms fall back to Default (RFC7432bis section 8.5) to prevent DF split-brain in all-active multi-homing.");
        CompassReporter.warning("FLOW-020.M001: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M002
        CompassReporter.stopAndStartLevel(++level + ". Method: Build a two-PE all-active ES with mismatched `service-carving` values, capture BGP route advertisements, and verify DF election converges using Default algorithm.");
        CompassReporter.warning("FLOW-020.M002: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M003.1 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `ethernet-segment`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT.args("0"));
        CompassReporter.warning("FLOW-020.M003.1: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.2 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `identifier 1`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT_IDENTIFIER_1.args("0"));
        CompassReporter.warning("FLOW-020.M003.2: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.3 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `load-balancing-mode all-active`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT_LOAD_BALANCING_MODE_ALL_ACTIVE.args("0"));
        CompassReporter.warning("FLOW-020.M003.3: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.4 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `service-carving highest-preference preference 50000`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT_SERVICE_CARVING_HIGHEST_PREFERENCE_$.args("0", "preference"));
        CompassReporter.warning("FLOW-020.M003.4: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.5 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `interface agg-eth 0`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT.args("0"));
        CompassReporter.warning("FLOW-020.M003.5: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.6 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `ethernet-segment`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT.args("0"));
        CompassReporter.warning("FLOW-020.M003.6: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.7 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `identifier 1`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT_IDENTIFIER_1.args("0"));
        CompassReporter.warning("FLOW-020.M003.7: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.8 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `load-balancing-mode all-active`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT_LOAD_BALANCING_MODE_ALL_ACTIVE.args("0"));
        CompassReporter.warning("FLOW-020.M003.8: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M003.9 - covers EVPNS-REQ#120, EVPNS-REQ#150, EVPNS-REQ#250, EVPNS-REQ#260, EVPNS-REQ#300, RFC7432bis-section 5, RFC7432bis-section 7.4, RFC7432bis-section 7.6, RFC7432bis-section 8.1.1, RFC7432bis-section 8.5, RFC7432bis-section 14.1.2, RFC9785-section 3, RFC9785-section 4.1, RFC9785-section 4.2, RFC9785-section 4.3
        CompassReporter.stopAndStartLevel(++level + ". Configure `service-carving default`");
        cmp1.configAndValidate(EvpnCommands.INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT_SERVICE_CARVING_DEFAULT.args("0"));
        CompassReporter.warning("FLOW-020.M003.9: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output.");

        // FLOW-020.M004
        CompassReporter.stopAndStartLevel(++level + ". Bring up the ES on both PEs; both derive identical ESI from LACP; PE1 advertises Type 4 (ES) route with DF Election Extended Community 'DF Alg'=Highest Preference; PE2 advertises Type 4 with 'DF Alg'=");
        CompassReporter.warning("FLOW-020.M004: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M007
        CompassReporter.stopAndStartLevel(++level + ". Capture BGP UPDATEs on the PE<->PE link and access-side frames on ingress / egress ACs (tcpdump / wireshark or IXIA capture)");
        evpnUtils.verifyIxiaStatistics("Capture BGP UPDATEs on the PE<->PE link and access-side frames on ingress / egress ACs (tcpdump / wireshark or IXIA capture)", new String[] {});
        CompassReporter.warning("FLOW-020.M007: Derived by pattern matching from plan prose; the command binding and expected values still need review.");

        // FLOW-020.M008
        CompassReporter.stopAndStartLevel(++level + ". Decode each captured packet and compare every NLRI / extended-community / label field against RFC 7432bis section 8, RFC 8584");
        CompassReporter.warning("FLOW-020.M008: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M009
        CompassReporter.stopAndStartLevel(++level + ". A neighbor feature (BGP convergence, MPLS encap, QoS, or another EVPN service) configured alongside on the same DUT");
        CompassReporter.warning("FLOW-020.M009: No pattern rule recognised this row; it is carried through verbatim so the step is not silently lost.");

        // FLOW-020.M011
        CompassReporter.stopAndStartLevel(++level + ". Bring up the neighbor feature first; verify its baseline `show` output");
        CompassReporter.warning("FLOW-020.M011: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M012
        CompassReporter.stopAndStartLevel(++level + ". Bring up the flow on top: Configure ES on both PEs: `interface agg-eth-1 ethernet-segment` with matching `identifier 1` (LACP); `load-balancing-mode all-active`; `service-carving preference 40000` on ");
        CompassReporter.warning("FLOW-020.M012: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. Row matches INTERFACE_AGG_ETH_$_ETHERNET_SEGMENT, but the plan text supplies 0 of the 1 argument(s) the documented command needs, so no CLI is emitted.");

        // FLOW-020.M013
        CompassReporter.stopAndStartLevel(++level + ". Drive traffic through both features simultaneously for >= 1 minute");
        CompassReporter.warning("FLOW-020.M013: Derived by pattern matching from plan prose; the command binding and expected values still need review.");

        // FLOW-020.M014
        CompassReporter.stopAndStartLevel(++level + ". IXIA traffic flowing through the flow's data path for >= 1 minute");
        evpnUtils.verifyIxiaStatistics("IXIA traffic flowing through the flow's data path for >= 1 minute", new String[] {});
        CompassReporter.warning("FLOW-020.M014: Derived by pattern matching from plan prose; the command binding and expected values still need review.");

        // FLOW-020.M016
        CompassReporter.stopAndStartLevel(++level + ". While traffic continues, revert each modified parameter to its original value and commit");
        CompassReporter.warning("FLOW-020.M016: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M017
        CompassReporter.stopAndStartLevel(++level + ". IXIA generating background traffic on the flow's data path");
        evpnUtils.verifyIxiaStatistics("IXIA generating background traffic on the flow's data path", new String[] {});
        CompassReporter.warning("FLOW-020.M017: Derived by pattern matching from plan prose; the command binding and expected values still need review.");

        // FLOW-020.M019
        CompassReporter.stopAndStartLevel(++level + ". Identify the relevant control-plane process via `show platform process | include evpn` (or `bgp`)");
        CompassReporter.warning("FLOW-020.M019: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M020
        CompassReporter.stopAndStartLevel(++level + ". Reset that process using the documented platform reset / debug CLI");
        CompassReporter.warning("FLOW-020.M020: No pattern rule recognised this row; it is carried through verbatim so the step is not silently lost.");

        // FLOW-020.M021
        CompassReporter.stopAndStartLevel(++level + ". Watch IXIA loss histogram during the reset");
        evpnUtils.verifyIxiaStatistics("Watch IXIA loss histogram during the reset", new String[] {});
        CompassReporter.warning("FLOW-020.M021: Derived by pattern matching from plan prose; the command binding and expected values still need review.");

        // FLOW-020.M022
        CompassReporter.stopAndStartLevel(++level + ". IXIA traffic running on the flow's data path");
        evpnUtils.verifyIxiaStatistics("IXIA traffic running on the flow's data path", new String[] {});
        CompassReporter.warning("FLOW-020.M022: Derived by pattern matching from plan prose; the command binding and expected values still need review.");

        // FLOW-020.M024
        CompassReporter.stopAndStartLevel(++level + ". Identify the control-plane process that owns this flow - for EVPN, the BGP/EVPN routing daemon (`bgpd`) - via `show platform process | include bgp` (or `evpn`)");
        CompassReporter.warning("FLOW-020.M024: Derived mechanically from the test plan by pattern matching. The command binding and every expected value still need review against real device output. No command in EvpnCommands matches this row, so no CLI is emitted rather than inventing one.");

        // FLOW-020.M025
        CompassReporter.stopAndStartLevel(++level + ". Kill that process via the documented platform debug command (not graceful restart)");
        CompassReporter.warning("FLOW-020.M025: No pattern rule recognised this row; it is carried through verbatim so the step is not silently lost.");

        // FLOW-020.M026
        CompassReporter.stopAndStartLevel(++level + ". Wait for supervisor-initiated restart");
        CompassReporter.warning("FLOW-020.M026: No pattern rule recognised this row; it is carried through verbatim so the step is not silently lost.");

        CompassReporter.stopLevel();
    }
}
